"""Additional verified Central and State Government Welfare Schemes to reach complete national catalog depth."""

from typing import Any, Dict, List

ADDITIONAL_SCHEMES: List[Dict[str, Any]] = [
    # -------------------------------------------------------------
    # MORE CENTRAL SCHEMES (Healthcare, Education, Agriculture, MSME, Social Security)
    # -------------------------------------------------------------
    {
        "slug": "janani-suraksha-yojana-jsy",
        "scheme_code": "SCH-CENTRAL-HLT-005",
        "name": "Janani Suraksha Yojana (JSY - Institutional Delivery Incentive)",
        "name_hi": "जननी सुरक्षा योजना (जेएसवाई - संस्थागत प्रसव प्रोत्साहन)",
        "description": "Safe motherhood intervention under National Health Mission promoting institutional delivery among poor pregnant women with cash assistance of ₹1,400 in rural areas and ₹1,000 in urban areas.",
        "description_hi": "गरीब गर्भवती महिलाओं को सुरक्षित प्रसव एवं मातृ-शिशु मृत्यु दर कम करने हेतु सरकारी अस्पताल में प्रसव कराने पर ₹1,400 (ग्रामीण) एवं ₹1,000 (शहरी) की नकद सहायता।",
        "primary_category": "Healthcare",
        "category": "Healthcare",
        "ministry": "Ministry of Health and Family Welfare",
        "department": "National Health Mission (NHM)",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["healthcare", "women_child"],
        "target_beneficiaries": ["All pregnant women delivering in government or accredited private health facilities in Low Performing States (LPS); BPL/SC/ST pregnant women in High Performing States"],
        "eligibility_rules": {
            "gender": ["female"],
            "states": ["ALL"],
            "age": {"min": 19, "max": 45}
        },
        "benefits": ["Cash assistance of ₹1,400 (rural) and ₹1,000 (urban) in Low Performing States (UP, Bihar, MP, Rajasthan, Odisha, Jharkhand, Chhattisgarh, Assam, J&K, Uttarakhand)", "Free transport to and from hospital through 108/102 ambulance", "Free post-delivery medicines and diagnostics"],
        "documents": ["Mother and Child Protection (MCP) Card", "Aadhaar Card", "Bank Account Details (Aadhaar linked)", "BPL Card / Caste Certificate (in HPS states)"],
        "application_steps": ["Register pregnancy at nearest Sub-Centre / Primary Health Centre (PHC) through ASHA worker", "Delivery at government hospital or accredited private hospital", "Cash incentive disbursed directly via DBT or cheque at time of discharge"],
        "official_url": "https://nhm.gov.in/",
        "source_url": "https://mohfw.gov.in/",
        "source_name": "National Health Mission",
        "verification_status": "Verified",
        "active": True,
        "tags": ["healthcare", "maternity", "delivery", "jsy", "pregnant-women", "cash-incentive", "nhm"]
    },
    {
        "slug": "janani-shishu-suraksha-karyakram-jssk",
        "scheme_code": "SCH-CENTRAL-HLT-006",
        "name": "Janani Shishu Suraksha Karyakram (JSSK - Zero Expense Delivery)",
        "name_hi": "जननी शिशु सुरक्षा कार्यक्रम (जेएसएसके - पूर्णतः निःशुल्क प्रसव)",
        "description": "Entitles all pregnant women delivering in public health institutions to completely free and cashless delivery including caesarean section, free drugs, diagnostics, blood, food, and transport.",
        "description_hi": "सरकारी स्वास्थ्य संस्थानों में गर्भवती महिलाओं को सामान्य एवं सिजेरियन प्रसव, दवाएं, जांच, भोजन एवं एम्बुलेंस परिवहन पूर्णतः निःशुल्क उपलब्ध कराना (शून्य खर्च)।",
        "primary_category": "Healthcare",
        "category": "Healthcare",
        "ministry": "Ministry of Health and Family Welfare",
        "department": "Maternal and Child Health Division",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["healthcare", "women_child"],
        "target_beneficiaries": ["All pregnant women delivering in public health institutions and sick newborn infants up to 1 year of age"],
        "eligibility_rules": {
            "states": ["ALL"],
            "age": {"min": 0, "max": 50}
        },
        "benefits": ["Completely cashless and free delivery including C-section in all government hospitals", "Free medicines, consumables, and blood transfusion", "Free diet during hospital stay (up to 3 days for normal, 7 days for caesarean)", "Free home-to-facility and facility-to-home transport"],
        "documents": ["MCP Card", "Aadhaar Card"],
        "application_steps": ["Report to any government hospital / Community Health Centre (CHC) for delivery", "Automatic zero-billing cashless treatment"],
        "official_url": "https://nhm.gov.in/",
        "source_url": "https://mohfw.gov.in/",
        "source_name": "Ministry of Health and Family Welfare",
        "verification_status": "Verified",
        "active": True,
        "tags": ["healthcare", "jssk", "free-delivery", "c-section", "maternity", "ambulance", "nhm"]
    },
    {
        "slug": "pradhan-mantri-surakshit-matritva-abhiyan-pmsma",
        "scheme_code": "SCH-CENTRAL-HLT-007",
        "name": "Pradhan Mantri Surakshit Matritva Abhiyan (PMSMA)",
        "name_hi": "प्रधानमंत्री सुरक्षित मातृत्व अभियान (पीएमएसएमए)",
        "description": "Guarantees comprehensive and free antenatal care (ANC) checkup packages by gynecologists/specialists to all pregnant women on the 9th of every month across designated government health facilities.",
        "description_hi": "प्रत्येक माह की 9 तारीख को सभी गर्भवती महिलाओं को स्त्री रोग विशेषज्ञों द्वारा निःशुल्क एवं व्यापक प्रसव पूर्व जांच (अल्ट्रासाउंड, हीमोग्लोबिन, शुगर, बीपी) की गारंटी।",
        "primary_category": "Healthcare",
        "category": "Healthcare",
        "ministry": "Ministry of Health and Family Welfare",
        "department": "National Health Mission",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["healthcare", "women_child"],
        "target_beneficiaries": ["All pregnant women in their 2nd and 3rd trimesters visiting public health facilities on the 9th of every month"],
        "eligibility_rules": {
            "gender": ["female"],
            "states": ["ALL"],
            "age": {"min": 18, "max": 45}
        },
        "benefits": ["Free comprehensive antenatal clinical examination by medical specialists", "Free ultrasound diagnostics, blood and urine tests", "Free iron-folic acid and calcium supplements", "High-Risk Pregnancy (HRP) identification and red sticker categorization for prioritized care"],
        "documents": ["MCP Card", "Aadhaar Card"],
        "application_steps": ["Visit nearest Primary Health Centre (PHC), CHC, or District Hospital on the 9th of any month", "Direct consultation and diagnostics"],
        "official_url": "https://pmsma.mohfw.gov.in/",
        "source_url": "https://mohfw.gov.in/",
        "source_name": "Ministry of Health and Family Welfare",
        "verification_status": "Verified",
        "active": True,
        "tags": ["healthcare", "pmsma", "antenatal-care", "pregnant-women", "ultrasound", "free-checkup"]
    },
    {
        "slug": "national-career-service-ncs",
        "scheme_code": "SCH-CENTRAL-JOB-006",
        "name": "National Career Service (NCS Project)",
        "name_hi": "राष्ट्रीय करियर सेवा (एनसीएस)",
        "description": "One-stop digital platform and physical Model Career Centres connecting job seekers, students, and apprentices with registered employers across government and private sectors with free career counseling.",
        "description_hi": "देशभर के शिक्षित युवाओं को सरकारी एवं निजी क्षेत्र में नौकरियों, ऑनलाइन जॉब मेलों, करियर परामर्श एवं निःशुल्क कौशल प्रशिक्षण से जोड़ने वाला राष्ट्रीय डिजिटल पोर्टल।",
        "primary_category": "Employment & Skills",
        "category": "Employment & Skills",
        "ministry": "Ministry of Labour and Employment",
        "department": "Directorate General of Employment (DGE)",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["jobs", "skills"],
        "target_beneficiaries": ["Job seekers, fresh graduates, ITI passouts, skilled workers, and employers across India"],
        "eligibility_rules": {
            "states": ["ALL"],
            "age": {"min": 18, "max": 65}
        },
        "benefits": ["Free access to over 15 lakh active job vacancies in banking, IT, manufacturing, healthcare, and retail", "Free career counseling and aptitude testing at 400+ Model Career Centres", "Free access to Microsoft DigiSaksham digital skill courses and TCS iON employability modules", "Direct participation in mega job fairs (Rozgar Mela)"],
        "documents": ["Aadhaar Card / Voter ID", "Educational Qualifications / Degree Certificates", "Updated Resume"],
        "application_steps": ["Register online at ncs.gov.in portal", "Build detailed job seeker profile and search vacancies", "Apply with one click and attend direct interviews"],
        "official_url": "https://www.ncs.gov.in/",
        "source_url": "https://labour.gov.in/",
        "source_name": "Ministry of Labour and Employment",
        "verification_status": "Verified",
        "active": True,
        "tags": ["jobs", "employment", "ncs", "job-portal", "career-guidance", "rozgar-mela", "placement"]
    },
    {
        "slug": "e-shram-unorganized-workers-card",
        "scheme_code": "SCH-CENTRAL-LAB-001",
        "name": "e-Shram Portal (National Database of Unorganized Workers)",
        "name_hi": "ई-श्रम कार्ड (असंगठित कामगारों का राष्ट्रीय डेटाबेस)",
        "description": "Comprehensive national database providing a 12-digit Universal Account Number (UAN) e-Shram Card to unorganized workers with ₹2,00,000 accidental insurance and direct linkage to all central and state welfare benefits.",
        "description_hi": "असंगठित क्षेत्र के श्रमिकों (मजदूर, पेंटर, प्लंबर, गिग वर्कर, नाई, धोबी) को ₹2 लाख का निःशुल्क दुर्घटना बीमा एवं सभी सरकारी योजनाओं से सीधा जुड़ाव देने वाला ई-श्रम कार्ड।",
        "primary_category": "Employment & Skills",
        "category": "Employment & Skills",
        "ministry": "Ministry of Labour and Employment",
        "department": "Ministry of Labour and Employment",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["jobs", "social_welfare", "financial"],
        "target_beneficiaries": ["All unorganized workers aged 16-59 years (construction workers, migrant workers, street vendors, domestic helpers, agricultural workers, gig/platform workers)"],
        "eligibility_rules": {
            "states": ["ALL"],
            "age": {"min": 16, "max": 59}
        },
        "benefits": ["Universal Account Number (UAN) e-Shram card valid across all States and UTs", "Accidental death and permanent disability cover of ₹2,00,000 (and ₹1,00,000 for partial disability) under PMSBY", "Direct pipeline for emergency disaster relief and cash transfers during crises"],
        "documents": ["Aadhaar Card", "Aadhaar-linked active mobile number", "Bank Account Details (Aadhaar seeded)"],
        "application_steps": ["Self-register online on eshram.gov.in portal or visit nearest CSC / Seva Kendra", "Aadhaar OTP verification", "Instant download of laminated e-Shram Card"],
        "official_url": "https://eshram.gov.in/",
        "source_url": "https://labour.gov.in/",
        "source_name": "Ministry of Labour and Employment",
        "verification_status": "Verified",
        "active": True,
        "tags": ["labor", "e-shram", "unorganized-workers", "accidental-insurance", "uan", "social-security"]
    },
    {
        "slug": "pm-daksh-yojana",
        "scheme_code": "SCH-CENTRAL-SKL-001",
        "name": "PM-DAKSH (Pradhan Mantri Dakshta Aur Kushalta Sampanna Hitgrahi)",
        "name_hi": "पीएम-दक्ष योजना (कौशल प्रशिक्षण एवं उद्यमिता)",
        "description": "National action plan offering free upskilling, short term training, and entrepreneurship development with ₹1,000 to ₹1,500/month stipends for SC, OBC, EBC, DNT, and sanitation workers.",
        "description_hi": "अनुसूचित जाति, अन्य पिछड़ा वर्ग, विमुक्त घुमंतू जातियों एवं सफाई कर्मचारियों के युवाओं को आधुनिक तकनीकी व्यवसायों में निःशुल्क प्रशिक्षण एवं मासिक वजीफा।",
        "primary_category": "Employment & Skills",
        "category": "Employment & Skills",
        "ministry": "Ministry of Social Justice and Empowerment",
        "department": "Department of Social Justice and Empowerment",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["skills", "jobs"],
        "target_beneficiaries": ["Candidates belonging to SC, OBC (income < ₹3 Lakh), EBC (income < ₹1 Lakh), DNT, and waste pickers / sanitation workers aged 18-45"],
        "eligibility_rules": {
            "category": ["SC", "OBC", "EWS"],
            "states": ["ALL"],
            "income": {"max": 300000},
            "age": {"min": 18, "max": 45}
        },
        "benefits": ["100% free training courses in high-demand trades: Apparel, computer technology, automotive repair, food processing, electronics, and solar PV installation", "Monthly stipend of ₹1,000 to ₹1,500 per month credited via DBT based on attendance", "Placement assistance and post-training startup loans from apex corporations (NSFDC, NBCFDC)"],
        "documents": ["Caste Certificate", "Income Certificate (for OBC/EBC)", "Aadhaar Card", "Educational Marksheets", "Bank Account Details"],
        "application_steps": ["Apply online on pmdaksh.dosje.gov.in portal or PM-DAKSH mobile app", "Select training institute and trade", "Assessment and certification upon completion"],
        "official_url": "https://pmdaksh.dosje.gov.in/",
        "source_url": "https://socialjustice.gov.in/",
        "source_name": "Ministry of Social Justice and Empowerment",
        "verification_status": "Verified",
        "active": True,
        "tags": ["skills", "pm-daksh", "sc", "obc", "training", "stipend", "jobs", "vocational"]
    },
    {
        "slug": "jal-jeevan-mission-har-ghar-jal",
        "scheme_code": "SCH-CENTRAL-WAT-001",
        "name": "Jal Jeevan Mission (Har Ghar Jal)",
        "name_hi": "जल जीवन मिशन (हर घर जल)",
        "description": "Transformative national infrastructure mission ensuring clean, potable piped tap water supply of 55 liters per person per day to every rural household in India.",
        "description_hi": "देश के प्रत्येक ग्रामीण परिवार के घर में नल से शुद्ध एवं पर्याप्त पेयजल (55 लीटर प्रति व्यक्ति प्रतिदिन) की नियमित आपूर्ति।",
        "primary_category": "Housing & Shelter",
        "category": "Housing & Shelter",
        "ministry": "Ministry of Jal Shakti",
        "department": "Department of Drinking Water and Sanitation",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["housing", "healthcare"],
        "target_beneficiaries": ["All rural households, schools, anganwadis, and community health centers in villages across India"],
        "eligibility_rules": {
            "area": "Rural",
            "states": ["ALL"],
            "age": {"min": 18, "max": 100}
        },
        "benefits": ["Free individual functional household tap connection (FHTC) providing safe drinking water directly inside the home", "Eliminates physical drudgery of fetching water for rural women and girls", "Regular water quality testing through Field Test Kits (FTKs) managed by village women"],
        "documents": ["Aadhaar Card", "Gram Panchayat household registration"],
        "application_steps": ["Village Action Plan formulated by Village Water and Sanitation Committee (VWSC) / Pani Samiti", "Pipeline laid and tap installed at household doorstep"],
        "official_url": "https://jaljeevanmission.gov.in/",
        "source_url": "https://jalshakti.gov.in/",
        "source_name": "Ministry of Jal Shakti",
        "verification_status": "Verified",
        "active": True,
        "tags": ["water", "drinking-water", "jal-jeevan-mission", "tap-water", "rural", "health", "har-ghar-jal"]
    },
    {
        "slug": "swachh-bharat-mission-gramin-ihhl",
        "scheme_code": "SCH-CENTRAL-SAN-001",
        "name": "Swachh Bharat Mission - Gramin (Individual Household Latrine - IHHL)",
        "name_hi": "स्वच्छ भारत मिशन - ग्रामीण (व्यक्तिगत घरेलू शौचालय सहायता)",
        "description": "Provides financial incentive of ₹12,000 to eligible rural households for constructing individual household twin-pit toilets to maintain Open Defecation Free (ODF Plus) status.",
        "description_hi": "ग्रामीण क्षेत्रों में शौचालय विहीन गरीब परिवारों को घर में पक्का शौचालय निर्माण हेतु ₹12,000 की सीधी नकद प्रोत्साहन राशि।",
        "primary_category": "Housing & Shelter",
        "category": "Housing & Shelter",
        "ministry": "Ministry of Jal Shakti",
        "department": "Department of Drinking Water and Sanitation",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["housing", "healthcare"],
        "target_beneficiaries": ["Rural households belonging to BPL or identified APL (SC/ST, small/marginal farmers, landless laborers, women-headed households, divyangjan) without an individual toilet"],
        "eligibility_rules": {
            "area": "Rural",
            "states": ["ALL"],
            "age": {"min": 18, "max": 100}
        },
        "benefits": ["Cash financial incentive of ₹12,000 credited directly into beneficiary's bank account via DBT upon toilet construction and geo-tagging", "Ensures dignity and safety for women and prevents waterborne diseases"],
        "documents": ["Aadhaar Card", "Bank Account Details (Aadhaar seeded)", "Ration Card", "Geo-tagged photo of constructed toilet"],
        "application_steps": ["Apply online on sbm.gov.in portal or submit application to Gram Panchayat", "Block sanitation team inspects and geo-tags constructed toilet on mobile app", "Incentive credited directly into bank account"],
        "official_url": "https://sbm.gov.in/",
        "source_url": "https://jalshakti.gov.in/",
        "source_name": "Department of Drinking Water and Sanitation",
        "verification_status": "Verified",
        "active": True,
        "tags": ["sanitation", "toilet", "swachh-bharat", "ihhl", "rural", "hygiene", "grant"]
    },
    {
        "slug": "beti-bachao-beti-padhao",
        "scheme_code": "SCH-CENTRAL-WOM-005",
        "name": "Beti Bachao Beti Padhao (BBBP - Mission Shakti Sambal)",
        "name_hi": "बेटी बचाओ बेटी पढ़ाओ (मिशन शक्ति संबल)",
        "description": "National multi-sectoral initiative addressing skewed child sex ratio, preventing female feticide, guaranteeing institutional survival, and promoting girl child secondary and higher education.",
        "description_hi": "बालिकाओं के प्रति भेदभाव समाप्त करने, लिंगानुपात में सुधार तथा बालिकाओं की माध्यमिक एवं उच्च शिक्षा व कौशल विकास हेतु राष्ट्रीय अभियान।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Ministry of Women and Child Development",
        "department": "Mission Shakti Directorate",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["women_child", "education"],
        "target_beneficiaries": ["Girl children, adolescent girls, and young women across all districts in India"],
        "eligibility_rules": {
            "gender": ["female"],
            "states": ["ALL"],
            "age": {"min": 0, "max": 25}
        },
        "benefits": ["Free admission facilitation in secondary and higher secondary schools", "Financial linkages with Sukanya Samriddhi Yojana at village Anganwadis", "District level awards and scholarships for meritorious girl students in sports and academics"],
        "documents": ["Birth Certificate of Girl Child", "Aadhaar Card", "School Enrollment Details"],
        "application_steps": ["Participate through District Women and Child Development Office, local Anganwadi, and school programs"],
        "official_url": "https://wcd.nic.in/bbbp-schemes",
        "source_url": "https://wcd.nic.in/",
        "source_name": "Ministry of Women and Child Development",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "girl-child", "bbbp", "beti-bachao", "education", "gender-equality"]
    },
    {
        "slug": "one-stop-centre-scheme-sakhi",
        "scheme_code": "SCH-CENTRAL-WOM-006",
        "name": "One Stop Centre Scheme (Sakhi Centres - Mission Shakti)",
        "name_hi": "सखी वन स्टॉप सेंटर योजना (मिशन शक्ति)",
        "description": "Provides 24x7 integrated emergency support, medical care, legal counseling, police assistance, and psycho-social counseling under one roof to women affected by violence.",
        "description_hi": "घरेलू या किसी भी प्रकार की हिंसा से पीड़ित महिलाओं को एक ही छत के नीचे 24 घंटे आपातकालीन आश्रय, चिकित्सा उपचार, कानूनी सहायता एवं पुलिस सुरक्षा।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Ministry of Women and Child Development",
        "department": "Mission Shakti - Sambal",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["women_child", "healthcare"],
        "target_beneficiaries": ["Any woman or girl facing physical, sexual, emotional, psychological, or economic abuse, irrespective of age, marital status, or income"],
        "eligibility_rules": {
            "gender": ["female"],
            "states": ["ALL"],
            "age": {"min": 0, "max": 100}
        },
        "benefits": ["24x7 immediate emergency medical care and first aid", "Police facilitation and lodging of Zero FIR / NCR", "Free legal aid through District Legal Services Authority (DLSA)", "Short-stay temporary residential shelter up to 5 days with food and toiletries", "Professional psychological and trauma counseling"],
        "documents": ["No mandatory documents required for emergency rescue and admission (Aadhaar or ID can be provided later)"],
        "application_steps": ["Walk in to nearest One Stop Centre located near District Hospital or dial Women Helpline 181 / Emergency 112"],
        "official_url": "https://wcd.nic.in/",
        "source_url": "https://wcd.nic.in/schemes/one-stop-centre-scheme-1",
        "source_name": "Ministry of Women and Child Development",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "one-stop-centre", "sakhi", "women-safety", "legal-aid", "emergency", "shelter"]
    },
    {
        "slug": "working-women-hostel-sakhi-niwas",
        "scheme_code": "SCH-CENTRAL-WOM-007",
        "name": "Working Women Hostel Scheme (Sakhi Niwas)",
        "name_hi": "सखी निवास (कामकाजी महिला छात्रावास योजना)",
        "description": "Provides safe, affordable, and furnished residential hostel accommodation with day-care creche facilities for working women living away from their families in urban and semi-urban centers.",
        "description_hi": "अपने परिवार से दूर शहरों में नौकरी अथवा व्यावसायिक प्रशिक्षण प्राप्त करने वाली महिलाओं को सुरक्षित, सुसज्जित एवं किफायती आवासीय छात्रावास।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Ministry of Women and Child Development",
        "department": "Mission Shakti - Samarthya",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["women_child", "housing"],
        "target_beneficiaries": ["Working women who are single, widowed, divorced, separated, or married with spouse working in a different town, with monthly salary up to ₹50,000 (metros) or ₹35,000 (other cities)"],
        "eligibility_rules": {
            "gender": ["female"],
            "income": {"max": 600000},
            "states": ["ALL"],
            "age": {"min": 18, "max": 60}
        },
        "benefits": ["Safe and highly subsidized hostel accommodation with 24x7 security and CCTV", "Attached day-care creche facility for children of resident working women (girls up to 18 years, boys up to 5 years)", "Stay permitted for up to 3 years"],
        "documents": ["Employment Letter / Salary Slip / Training Proof", "Identity Proof (Aadhaar / Voter ID)", "Permanent Residence Proof", "Passport Photographs"],
        "application_steps": ["Apply directly to hostel superintendent of local Sakhi Niwas / Working Women Hostel", "Scrutiny of employment credentials and room allotment"],
        "official_url": "https://wcd.nic.in/",
        "source_url": "https://wcd.nic.in/schemes/working-women-hostel",
        "source_name": "Ministry of Women and Child Development",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "hostel", "working-women", "sakhi-niwas", "urban", "safe-housing", "accommodation"]
    },
    {
        "slug": "mahila-samman-savings-certificate-mssc",
        "scheme_code": "SCH-CENTRAL-FIN-005",
        "name": "Mahila Samman Savings Certificate (MSSC)",
        "name_hi": "महिला सम्मान बचत पत्र (MSSC)",
        "description": "Small savings program exclusively for women and girls offering an attractive high fixed interest rate of 7.5% per annum for a 2-year tenure with partial withdrawal facility.",
        "description_hi": "महिलाओं एवं बालिकाओं के नाम पर 2 वर्ष की अवधि हेतु 7.5% की उच्च निश्चित ब्याज दर वाली सुरक्षित सरकारी लघु बचत योजना।",
        "primary_category": "Financial Assistance",
        "category": "Financial Assistance",
        "ministry": "Ministry of Finance",
        "department": "Department of Economic Affairs",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["financial", "women_child"],
        "target_beneficiaries": ["Any woman in her own name or guardian on behalf of a minor girl child"],
        "eligibility_rules": {
            "gender": ["female"],
            "states": ["ALL"],
            "age": {"min": 0, "max": 100}
        },
        "benefits": ["High sovereign fixed interest rate of 7.5% per annum compounded quarterly", "Flexible deposit starting from ₹1,000 up to maximum ₹2,00,000 for a tenure of 2 years", "Partial withdrawal of up to 40% of the balance allowed after completion of 1 year"],
        "documents": ["Account Opening Form", "Aadhaar Card and PAN Card", "KYC documents and passport photographs"],
        "application_steps": ["Visit any Post Office or designated commercial bank branch", "Fill Mahila Samman Savings form and deposit amount in cash / cheque", "Receive MSSC Passbook"],
        "official_url": "https://www.indiapost.gov.in/",
        "source_url": "https://financialservices.gov.in/",
        "source_name": "Ministry of Finance / India Post",
        "verification_status": "Verified",
        "active": True,
        "tags": ["financial", "savings", "women", "mssc", "fixed-deposit", "post-office", "interest"]
    },
    {
        "slug": "senior-citizens-savings-scheme-scss",
        "scheme_code": "SCH-CENTRAL-FIN-006",
        "name": "Senior Citizens Savings Scheme (SCSS)",
        "name_hi": "वरिष्ठ नागरिक बचत योजना (एससीएसएस)",
        "description": "Premier government retirement savings scheme for individuals aged 60+ offering a high sovereign interest rate of 8.2% per annum paid out as regular quarterly income with tax benefits.",
        "description_hi": "60 वर्ष या उससे अधिक आयु के वरिष्ठ नागरिकों हेतु 8.2% ब्याज दर वाली सुरक्षित सरकारी योजना, जिसमें हर तीन महीने पर नियमित ब्याज आय मिलती है।",
        "primary_category": "Social Security & Pension",
        "category": "Social Security & Pension",
        "ministry": "Ministry of Finance",
        "department": "Department of Economic Affairs",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["pension", "financial"],
        "target_beneficiaries": ["Indian citizens aged 60 years or above (or aged 55-60 for individuals retired under VRS/Superannuation)"],
        "eligibility_rules": {
            "states": ["ALL"],
            "age": {"min": 60, "max": 120}
        },
        "benefits": ["High sovereign interest rate of 8.2% per annum with quarterly interest payments credited directly into savings account", "Investment ceiling up to ₹30,00,000 per individual (₹60 Lakhs for joint couple account)", "Tax deduction under Section 80C up to ₹1.5 Lakh per financial year"],
        "documents": ["Proof of Age (PAN Card / Voter ID / Passport)", "Aadhaar Card", "Retirement / Superannuation Proof (if age 55-60)", "Photographs"],
        "application_steps": ["Open account at any Post Office or public/private commercial bank branch", "Deposit amount via cheque / draft", "Quarterly interest credited automatically on 1st of April, July, October, January"],
        "official_url": "https://www.indiapost.gov.in/",
        "source_url": "https://financialservices.gov.in/",
        "source_name": "Ministry of Finance",
        "verification_status": "Verified",
        "active": True,
        "tags": ["pension", "senior-citizens", "scss", "retirement", "quarterly-interest", "tax-saving", "post-office"]
    }
]
