"""Additional Curated Central Government Flagship Schemes for complete national coverage."""

from typing import Any, Dict, List

CENTRAL_SCHEMES_MORE: List[Dict[str, Any]] = [
    # -------------------------------------------------------------
    # SCHOOL & HIGHER EDUCATION (Central)
    # -------------------------------------------------------------
    {
        "slug": "samagra-shiksha-abhiyan",
        "scheme_code": "SCH-CENTRAL-EDU-011",
        "name": "Samagra Shiksha Abhiyan (Universal School Education)",
        "name_hi": "समग्र शिक्षा अभियान (सार्वभौमिक स्कूली शिक्षा)",
        "description": "Overarching program for school education from pre-school to class 12 providing free textbooks, uniforms, digital classrooms, science labs, and transport subsidies in government schools.",
        "description_hi": "प्री-स्कूल से 12वीं तक सभी सरकारी विद्यालयों में निःशुल्क पाठ्यपुस्तकें, यूनिफॉर्म, डिजिटल स्मार्ट क्लास और समग्र शैक्षणिक सुविधाएं।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Ministry of Education",
        "department": "Department of School Education and Literacy",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["education"],
        "target_beneficiaries": ["Children aged 4 to 18 years enrolled in Government and Government-aided schools across India"],
        "eligibility_rules": {
            "occupation": ["student"],
            "states": ["ALL"],
            "age": {"min": 4, "max": 18}
        },
        "benefits": ["Free textbooks up to Class 8 under RTE Act", "Two sets of free school uniforms per child per year up to Class 8", "Kasturba Gandhi Balika Vidyalaya (KGBV) residential schools for girls from disadvantaged groups", "Special educator support for Children with Special Needs (CwSN)"],
        "documents": ["School Admission Record / UDISE+ student ID", "Aadhaar Card", "Birth Certificate / Age Proof"],
        "application_steps": ["Admission in any government or local body school", "Entitlements delivered directly through school on opening day"],
        "official_url": "https://samagra.education.gov.in/",
        "source_url": "https://dsel.education.gov.in/",
        "source_name": "Ministry of Education",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "school", "free-books", "uniform", "rte", "samagra-shiksha", "children"]
    },
    {
        "slug": "pm-poshan-shakti-nirman-mid-day-meal",
        "scheme_code": "SCH-CENTRAL-EDU-012",
        "name": "PM POSHAN (Pradhan Mantri Poshan Shakti Nirman / Mid-Day Meal)",
        "name_hi": "पीएम पोषण शक्ति निर्माण योजना (मध्याह्न भोजन)",
        "description": "Provides hot cooked nutritious lunch every school day to over 11.8 crore children enrolled in pre-primary (Balvatika) and classes 1 to 8 in government and aided schools.",
        "description_hi": "सरकारी एवं सहायता प्राप्त विद्यालयों के कक्षा 1 से 8वीं तक के सभी विद्यार्थियों को प्रतिदिन निःशुल्क ताजा गर्म एवं पौष्टिक भोजन।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Ministry of Education",
        "department": "Department of School Education and Literacy",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["education", "healthcare"],
        "target_beneficiaries": ["All children attending Classes 1 to 8 and Balvatika in government, local body, and government-aided schools"],
        "eligibility_rules": {
            "occupation": ["student"],
            "states": ["ALL"],
            "age": {"min": 5, "max": 14}
        },
        "benefits": ["Hot cooked meal providing minimum 450 calories and 12g protein (Primary) and 700 calories and 20g protein (Upper Primary)", "Fortified rice with iron, folic acid, and Vitamin B12 to eliminate childhood anemia", "Increases school attendance and nutritional status"],
        "documents": ["School enrollment / Student register entry in government school"],
        "application_steps": ["Automatic entitlement for every student attending classes daily at school"],
        "official_url": "https://pmposhan.education.gov.in/",
        "source_url": "https://dsel.education.gov.in/",
        "source_name": "Ministry of Education",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "nutrition", "mid-day-meal", "pm-poshan", "school", "lunch", "children"]
    },
    {
        "slug": "top-class-education-for-sc-students",
        "scheme_code": "SCH-CENTRAL-EDU-013",
        "name": "Central Sector Scheme of Top Class Education for SC Students",
        "name_hi": "अनुसूचित जाति के छात्रों हेतु टॉप क्लास शिक्षा योजना",
        "description": "Full financial support covering full tuition fees, living expenses, and computer allowances for meritorious SC students admitted into 266 premier institutions (IITs, IIMs, NITs, AIIMS, NLUs).",
        "description_hi": "आईआईटी, आईआईएम, एम्स, एनआईटी एवं नेशनल लॉ यूनिवर्सिटी में प्रवेश पाने वाले एससी वर्ग के मेधावी छात्रों की पूर्ण फीस एवं लैपटॉप भत्ता।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Ministry of Social Justice and Empowerment",
        "department": "Department of Social Justice and Empowerment",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["education"],
        "target_beneficiaries": ["SC students securing admission into notified premier institutes with total family income up to ₹8.00 Lakh/year"],
        "eligibility_rules": {
            "category": ["SC"],
            "occupation": ["student"],
            "income": {"max": 800000},
            "states": ["ALL"],
            "age": {"min": 17, "max": 32}
        },
        "benefits": ["Full non-refundable tuition fees and academic charges directly paid to institute (up to ₹2 Lakh/year in private institutes; unlimited in government)", "Living expenses of ₹3,000 per month (₹36,000/year)", "One-time computer/laptop allowance of ₹45,000 and ₹5,000/year for books and stationery"],
        "documents": ["SC Caste Certificate", "Income Certificate (≤ ₹8 Lakh/yr)", "Admission Letter of premier institute", "Fee Demand Letter", "Aadhaar Card"],
        "application_steps": ["Apply online through National Scholarship Portal (NSP)", "Select Top Class Education Scheme for SC Students", "Institute head e-verifies credentials"],
        "official_url": "https://scholarships.gov.in/",
        "source_url": "https://socialjustice.gov.in/",
        "source_name": "Ministry of Social Justice and Empowerment",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "scholarship", "sc", "top-class", "iit", "iim", "aiims", "merit", "tuition"]
    },
    {
        "slug": "national-overseas-scholarship-sc",
        "scheme_code": "SCH-CENTRAL-EDU-014",
        "name": "National Overseas Scholarship for SC and Landless Agricultural Labourers",
        "name_hi": "अनुसूचित जाति एवं भूमिहीन कृषि मजदूरों हेतु राष्ट्रीय विदेशी छात्रवृत्ति",
        "description": "Centrally funded scholarship covering 100% tuition fees, living allowances, visa, and airfare for SC students, de-notified tribes, and children of landless agricultural workers to pursue Masters/Ph.D. abroad.",
        "description_hi": "एससी एवं भूमिहीन खेतिहर परिवारों के मेधावी छात्रों को विदेश के शीर्ष विश्वविद्यालयों से मास्टर्स व पीएचडी की उच्च शिक्षा हेतु पूर्ण वित्तीय छात्रवृत्ति।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Ministry of Social Justice and Empowerment",
        "department": "Department of Social Justice and Empowerment",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["education"],
        "target_beneficiaries": ["SC candidates, traditional artisans, and children of landless agricultural laborers with family income up to ₹8 Lakh having confirmed foreign admission in top 500 QS universities"],
        "eligibility_rules": {
            "category": ["SC"],
            "occupation": ["student"],
            "income": {"max": 800000},
            "states": ["ALL"],
            "age": {"min": 20, "max": 35}
        },
        "benefits": ["100% actual tuition fees paid directly to foreign university", "Annual maintenance allowance of US $15,400 (or £9,900 in UK)", "Economy class return international airfare, health insurance, and visa application fee"],
        "documents": ["SC Caste Certificate", "Unconditional Admission Offer from Foreign University (QS top 500)", "Bachelor/Master Degree Marksheets (minimum 60% marks)", "Family Income Certificate (≤ ₹8 Lakh/yr)", "Valid Passport"],
        "application_steps": ["Apply online on nosmsje.gov.in portal", "Screening Committee evaluates QS ranking of host institution", "Award letter issued and Indian mission abroad disburses fee directly to university"],
        "official_url": "https://nosmsje.gov.in/",
        "source_url": "https://socialjustice.gov.in/",
        "source_name": "Ministry of Social Justice and Empowerment",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "scholarship", "overseas", "sc", "study-abroad", "foreign-education", "phd", "masters"]
    },
    {
        "slug": "free-coaching-scheme-for-sc-and-obc-students",
        "scheme_code": "SCH-CENTRAL-EDU-015",
        "name": "Free Coaching Scheme for SC and OBC Students",
        "name_hi": "अनुसूचित जाति एवं अन्य पिछड़ा वर्ग के छात्रों हेतु निःशुल्क कोचिंग योजना",
        "description": "Provides high-quality free coaching and monthly stipends of up to ₹6,000 for competitive examinations (UPSC, State PSCs, SSC, Banking, JEE, NEET, GATE, CLAT) for SC and OBC candidates.",
        "description_hi": "एससी एवं ओबीसी वर्ग के निर्धन विद्यार्थियों को सिविल सेवा, जेईई, नीट, बैंक एवं क्लैट की तैयारी हेतु प्रतिष्ठित कोचिंग संस्थानों में निःशुल्क कोचिंग एवं मासिक वजीफा।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Ministry of Social Justice and Empowerment",
        "department": "Department of Social Justice and Empowerment",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["education", "jobs"],
        "target_beneficiaries": ["SC and OBC students with family income not exceeding ₹8.00 Lakh/year preparing for premier competitive examinations"],
        "eligibility_rules": {
            "category": ["SC", "OBC"],
            "occupation": ["student", "unemployed"],
            "income": {"max": 800000},
            "states": ["ALL"],
            "age": {"min": 18, "max": 35}
        },
        "benefits": ["100% coaching course fee paid directly to empanelled premier coaching institutes by Central Government", "Monthly stipend of ₹4,000 for local students and ₹6,000 for outstation students throughout the coaching duration (up to 12 months)", "Special incentives for Divyangjan"],
        "documents": ["Caste Certificate (SC/OBC)", "Family Income Certificate (≤ ₹8 Lakh/yr)", "Class 10 and 12 Marksheets and Degree Certificate", "Aadhaar Card and Bank Account Details"],
        "application_steps": ["Apply online on coaching.dosje.gov.in portal", "Merit list prepared based on Class 12 / Degree marks", "Allotment to empanelled coaching institute with DBT stipend release"],
        "official_url": "https://coaching.dosje.gov.in/",
        "source_url": "https://socialjustice.gov.in/",
        "source_name": "Ministry of Social Justice and Empowerment",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "coaching", "upsc", "neet", "jee", "sc", "obc", "stipend", "competitive-exams"]
    },

    # -------------------------------------------------------------
    # AGRICULTURE, IRRIGATION & HORTICULTURE (Central)
    # -------------------------------------------------------------
    {
        "slug": "paramparagat-krishi-vikas-yojana-pkvy",
        "scheme_code": "SCH-CENTRAL-AGRI-009",
        "name": "Paramparagat Krishi Vikas Yojana (PKVY - Organic Farming)",
        "name_hi": "परंपरागत कृषि विकास योजना (पीकेवीवाई - जैविक खेती)",
        "description": "Promotes chemical-free organic farming through cluster approach with financial assistance of ₹50,000 per hectare for cluster formation, organic inputs, certification, and packaging.",
        "description_hi": "किसानों को जैविक खाद, वर्मीकम्पोस्ट, बायो-पेस्टीसाइड एवं पीजीएस जैविक प्रमाणीकरण हेतु प्रति हेक्टेयर ₹50,000 की वित्तीय सहायता।",
        "primary_category": "Agriculture & Rural Development",
        "category": "Agriculture & Rural Development",
        "ministry": "Ministry of Agriculture and Farmers Welfare",
        "department": "National Centre of Organic Farming (NCOF)",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["agriculture"],
        "target_beneficiaries": ["Farmers willing to form clusters of 20 or more farmers having 50 acres of contiguous land for certified organic farming"],
        "eligibility_rules": {
            "occupation": ["farmer"],
            "states": ["ALL"],
            "age": {"min": 18, "max": 80}
        },
        "benefits": ["Financial assistance of ₹50,000 per hectare for 3-year transition period: ₹31,000/ha for on-farm organic inputs via DBT + ₹8,800/ha for post-harvest value addition and packaging", "Free Participatory Guarantee System (PGS-India) organic certification enabling premium crop prices"],
        "documents": ["Land Ownership Documents (Khasra/Khatauni)", "Aadhaar Card", "Cluster membership resolution", "Bank Account Details"],
        "application_steps": ["Join village farmer cluster through District Agriculture Officer or Regional Centre of Organic Farming", "Register on Jaivik Kheti portal (jaivikkheti.in)", "Participatory peer inspection and certification"],
        "official_url": "https://pgsindia-ncof.gov.in/",
        "source_url": "https://agricoop.nic.in/",
        "source_name": "Ministry of Agriculture and Farmers Welfare",
        "verification_status": "Verified",
        "active": True,
        "tags": ["agriculture", "organic-farming", "pkvy", "bio-fertilizer", "vermicompost", "farmer", "subsidy"]
    },
    {
        "slug": "mission-for-integrated-development-of-horticulture-midh",
        "scheme_code": "SCH-CENTRAL-AGRI-010",
        "name": "Mission for Integrated Development of Horticulture (MIDH)",
        "name_hi": "एकीकृत बागवानी विकास मिशन (MIDH)",
        "description": "Comprehensive horticulture development mission providing 40% to 50% capital subsidies for establishing fruit orchards, polyhouses, shade nets, mushroom units, and pack-houses.",
        "description_hi": "फल, सब्जी, मसाला, मशरूम एवं पुष्प उत्पादन हेतु पॉलीहाउस, शेडनेट, नर्सरी एवं कोल्ड स्टोरेज स्थापना पर 50% तक सरकारी अनुदान।",
        "primary_category": "Agriculture & Rural Development",
        "category": "Agriculture & Rural Development",
        "ministry": "Ministry of Agriculture and Farmers Welfare",
        "department": "Horticulture Division",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["agriculture", "business"],
        "target_beneficiaries": ["Horticulture farmers, farmer groups, cooperatives, and agribusiness entrepreneurs"],
        "eligibility_rules": {
            "occupation": ["farmer", "entrepreneur"],
            "states": ["ALL"],
            "age": {"min": 18, "max": 75}
        },
        "benefits": ["Up to 50% capital subsidy for erecting Polyhouses and Shade Net Houses", "Subsidies for establishing high-density apple, mango, citrus, and banana orchards", "Financial assistance for mushroom spawn labs, pack-houses, and reefer transport vans"],
        "documents": ["Land Revenue Records", "Aadhaar Card", "Detailed Project Plan / Quotations from empaneled manufacturers", "Bank Sanction Letter (for credit linked projects)"],
        "application_steps": ["Submit project to District Horticulture Officer (DHO) or State Horticulture Mission portal", "Technical inspection and work permit issuance", "Direct subsidy release upon post-installation verification"],
        "official_url": "https://midh.gov.in/",
        "source_url": "https://agricoop.nic.in/",
        "source_name": "Ministry of Agriculture and Farmers Welfare",
        "verification_status": "Verified",
        "active": True,
        "tags": ["agriculture", "horticulture", "polyhouse", "orchard", "midh", "shade-net", "subsidy", "farmer"]
    },
    {
        "slug": "national-beekeeping-and-honey-mission-nbhm",
        "scheme_code": "SCH-CENTRAL-AGRI-011",
        "name": "National Beekeeping and Honey Mission (NBHM - Sweet Revolution)",
        "name_hi": "राष्ट्रीय मधुमक्खी पालन एवं शहद मिशन (मीठी क्रांति)",
        "description": "Provides up to 80% financial subsidy for scientific beekeeping, purchase of bee colonies and beehives, honey testing laboratories, and honey processing units.",
        "description_hi": "किसानों एवं ग्रामीण युवाओं को अतिरिक्त आय हेतु मधुमक्खी बक्से, मधुमक्खी कालोनियां एवं शहद प्रसंस्करण इकाइयां स्थापित करने पर 80% तक अनुदान।",
        "primary_category": "Agriculture & Rural Development",
        "category": "Agriculture & Rural Development",
        "ministry": "Ministry of Agriculture and Farmers Welfare",
        "department": "National Bee Board (NBB)",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["agriculture", "business"],
        "target_beneficiaries": ["Beekeepers, farmers, landless rural youth, SHGs, and beekeeping cooperatives"],
        "eligibility_rules": {
            "occupation": ["farmer", "self_employed", "entrepreneur"],
            "states": ["ALL"],
            "age": {"min": 18, "max": 65}
        },
        "benefits": ["Financial assistance up to 80% of cost for 10 to 50 beehive boxes and colonies for small farmers/SHGs", "Increases agricultural crop pollination by 20-30%", "Substantial ancillary income through sale of raw honey, beeswax, royal jelly, and propolis"],
        "documents": ["Aadhaar Card", "Beekeeping Training Certificate from NBB / KVIC / ICAR", "Bank Account Details", "Photograph"],
        "application_steps": ["Register on Madhukranti portal (madhukranti.in) of National Bee Board", "Submit subsidy claim through District Horticulture / Khadi Board", "Subsidy credited to bank account"],
        "official_url": "https://nbhm.gov.in/",
        "source_url": "https://agricoop.nic.in/",
        "source_name": "National Bee Board",
        "verification_status": "Verified",
        "active": True,
        "tags": ["agriculture", "beekeeping", "honey", "nbhm", "sweet-revolution", "subsidy", "rural-income"]
    },

    # -------------------------------------------------------------
    # MSME, INNOVATION & ENTERPRISE (Central)
    # -------------------------------------------------------------
    {
        "slug": "msme-zed-certification-scheme",
        "scheme_code": "SCH-CENTRAL-MSM-001",
        "name": "MSME Champions Scheme - ZED (Zero Defect Zero Effect) Certification",
        "name_hi": "एमएसएमई जेड (जीरो डिफेक्ट जीरो इफेक्ट) प्रमाणन योजना",
        "description": "Provides financial subsidy of up to 80% on certification cost to MSMEs to adopt sustainable manufacturing, reduce industrial waste, enhance quality, and obtain ZED ratings (Bronze, Silver, Gold).",
        "description_hi": "सूक्ष्म, लघु एवं मध्यम उद्योगों को गुणवत्ता सुधार, शून्य खराबी एवं पर्यावरण सुरक्षा प्रमाणन हेतु 80% तक की सरकारी वित्तीय प्रतिपूर्ति।",
        "primary_category": "Business & Self Employment",
        "category": "Business & Self Employment",
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "department": "Office of Development Commissioner MSME",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["business"],
        "target_beneficiaries": ["Udyam registered manufacturing Micro, Small, and Medium Enterprises in India"],
        "eligibility_rules": {
            "occupation": ["entrepreneur"],
            "states": ["ALL"],
            "age": {"min": 18, "max": 75}
        },
        "benefits": ["Subsidies on certification costs: 80% for Micro, 60% for Small, and 50% for Medium enterprises (additional 10% for women/SC/ST owned units)", "Financial assistance up to ₹5 Lakhs for handholding and consultancy to achieve higher ZED levels", "Preferential bank interest rate concessions (up to 0.5% lower) for ZED certified units from public sector banks"],
        "documents": ["Udyam Registration Certificate", "Factory layout and manufacturing process flow", "Aadhaar Card of authorized signatory", "Bank Account Details"],
        "application_steps": ["Register on zed.msme.gov.in with Udyam number", "Take free online ZED pledge and complete desktop self-assessment", "Desktop / site assessment by accredited assessment agencies (QCI) and certificate award"],
        "official_url": "https://zed.msme.gov.in/",
        "source_url": "https://msme.gov.in/",
        "source_name": "Ministry of MSME / QCI",
        "verification_status": "Verified",
        "active": True,
        "tags": ["business", "msme", "zed", "manufacturing", "certification", "subsidy", "quality", "green"]
    },
    {
        "slug": "sfurti-scheme-for-traditional-industries",
        "scheme_code": "SCH-CENTRAL-MSM-002",
        "name": "Scheme of Fund for Regeneration of Traditional Industries (SFURTI)",
        "name_hi": "पारंपरिक उद्योगों के उत्थान हेतु कोष योजना (स्फूर्ति / SFURTI)",
        "description": "Grants financial assistance up to ₹5 Crores to organize traditional artisans and rural craftspeople into modern industrial clusters with common facility centres, advanced tooling, and e-commerce linkages.",
        "description_hi": "पारंपरिक कारीगरों (खादी, बांस, मिट्टी, चर्म, कपड़ा) के क्लस्टर विकास हेतु ₹5 करोड़ तक का 100% सरकारी अनुदान, कॉमन फैसिलिटी सेंटर और आधुनिक मशीनरी।",
        "primary_category": "Business & Self Employment",
        "category": "Business & Self Employment",
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "department": "KVIC / Coir Board / MSME",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["business", "skills"],
        "target_beneficiaries": ["Artisans, rural craftspeople, NGOs, institutions, and Special Purpose Vehicles (SPVs) forming traditional artisan clusters (500+ artisans)"],
        "eligibility_rules": {
            "occupation": ["artisan", "self_employed", "entrepreneur"],
            "states": ["ALL"],
            "age": {"min": 18, "max": 75}
        },
        "benefits": ["Financial grant up to ₹2.5 Crores for Regular Clusters (up to 500 artisans) and up to ₹5 Crores for Major Clusters (more than 500 artisans)", "Covers 100% cost of hard interventions (land development, common work sheds, automated machinery) and soft interventions (training, market fairs)", "Transforms daily wage artisans into co-owners of modern industrial producer companies"],
        "documents": ["Detailed Project Report (DPR)", "SPV Registration documents (Section 8 Company / Producer Co)", "Artisan cluster roll with Aadhaar details", "Land availability documents for Common Facility Centre"],
        "application_steps": ["Submit project concept on sfurti.msme.gov.in through Nodal Agency (KVIC, Coir Board, IIE)", "Scheme Steering Committee (SSC) approval chaired by Secretary MSME", "Tranche-wise grant release directly into SPV escrow account"],
        "official_url": "https://sfurti.msme.gov.in/",
        "source_url": "https://msme.gov.in/",
        "source_name": "Ministry of MSME",
        "verification_status": "Verified",
        "active": True,
        "tags": ["business", "sfurti", "artisan", "cluster", "common-facility", "traditional-industry", "grant"]
    },
    {
        "slug": "national-sc-st-hub-nssh",
        "scheme_code": "SCH-CENTRAL-MSM-003",
        "name": "National SC-ST Hub (NSSH)",
        "name_hi": "राष्ट्रीय अनुसूचित जाति एवं अनुसूचित जनजाति हब (NSSH)",
        "description": "Special institutional initiative to promote enterprise culture and fulfill the mandate of 4% public procurement from SC/ST entrepreneurs by Central Ministries and CPSEs.",
        "description_hi": "अनुसूचित जाति एवं जनजाति के उद्यमियों के व्यवसाय विस्तार, सरकारी खरीद (4% कोटा), रियायती ऋण एवं निःशुल्क कौशल प्रशिक्षण हेतु समर्पित राष्ट्रीय हब।",
        "primary_category": "Business & Self Employment",
        "category": "Business & Self Employment",
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "department": "National Small Industries Corporation (NSIC)",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["business"],
        "target_beneficiaries": ["Micro, Small, and Medium Enterprises owned by Scheduled Caste and Scheduled Tribe entrepreneurs having Udyam registration"],
        "eligibility_rules": {
            "category": ["SC", "ST"],
            "occupation": ["entrepreneur"],
            "states": ["ALL"],
            "age": {"min": 18, "max": 70}
        },
        "benefits": ["Special Credit Linked Capital Subsidy Scheme (SCLCSS) providing 25% capital subsidy up to ₹25 Lakhs for purchasing modern machinery", "100% reimbursement of fee for GeM registration, BIS/ISO certifications, barcoding, and testing charges", "Reimbursement of participation fee in national and international trade fairs"],
        "documents": ["Udyam Registration Certificate (with SC/ST promoter classification)", "Caste Certificate of promoters (>51% shareholding)", "Machinery Purchase Invoices / DPR", "Bank Sanction Letter"],
        "application_steps": ["Register on scsthub.in portal or visit nearest NSIC office", "Submit claim under SCLCSS or reimbursement scheme", "Inspection by NSIC and direct subsidy credit to bank loan account"],
        "official_url": "https://www.scsthub.in/",
        "source_url": "https://www.nsic.co.in/",
        "source_name": "NSIC / Ministry of MSME",
        "verification_status": "Verified",
        "active": True,
        "tags": ["business", "sc", "st", "nssh", "msme", "subsidy", "procurement", "machinery"]
    },

    # -------------------------------------------------------------
    # SOCIAL SECURITY, CITIZEN RELIEF & HOUSING (Central)
    # -------------------------------------------------------------
    {
        "slug": "indira-gandhi-national-widow-pension-scheme",
        "scheme_code": "SCH-CENTRAL-PEN-005",
        "name": "Indira Gandhi National Widow Pension Scheme (IGNWPS)",
        "name_hi": "इंदिरा गांधी राष्ट्रीय विधवा पेंशन योजना (IGNWPS)",
        "description": "Monthly pension under National Social Assistance Programme (NSAP) providing regular financial sustenance to widows aged 40 to 59 years living below the poverty line.",
        "description_hi": "गरीबी रेखा से नीचे जीवनयापन करने वाली 40 से 59 वर्ष की निराश्रित विधवा माताओं-बहनों को सम्मानजनक जीवन हेतु प्रतिमाह नियमित पेंशन।",
        "primary_category": "Social Security & Pension",
        "category": "Social Security & Pension",
        "ministry": "Ministry of Rural Development",
        "department": "National Social Assistance Programme (NSAP)",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["pension", "women_child"],
        "target_beneficiaries": ["Widows aged 40-59 years belonging to households living below poverty line (BPL)"],
        "eligibility_rules": {
            "gender": ["female"],
            "income": {"max": 100000},
            "states": ["ALL"],
            "age": {"min": 40, "max": 59}
        },
        "benefits": ["Monthly pension credited directly into beneficiary's bank account (combined Central + State contribution typically ₹1,000 to ₹2,500/month depending on state)", "Seamless transition into IGNOAPS old age pension upon attaining 60 years of age"],
        "documents": ["Death Certificate of Husband", "BPL Ration Card / Income Certificate", "Aadhaar Card", "Age Verification Proof", "Bank Account Passbook"],
        "application_steps": ["Apply online on nsap.nic.in or at local Gram Panchayat / Municipal Welfare Office", "Inquiry by Block Development Officer (BDO) and sanction order issued", "Monthly DBT pension payment"],
        "official_url": "https://nsap.nic.in/",
        "source_url": "https://rural.nic.in/",
        "source_name": "Ministry of Rural Development",
        "verification_status": "Verified",
        "active": True,
        "tags": ["pension", "widow", "ignwps", "nsap", "bpl", "women-welfare", "dbt"]
    },
    {
        "slug": "indira-gandhi-national-disability-pension-scheme",
        "scheme_code": "SCH-CENTRAL-DIS-003",
        "name": "Indira Gandhi National Disability Pension Scheme (IGNDPS)",
        "name_hi": "इंदिरा गांधी राष्ट्रीय दिव्यांगता पेंशन योजना (IGNDPS)",
        "description": "Non-contributory disability pension providing monthly financial support to persons aged 18 to 79 years living below poverty line with severe or multiple disabilities (≥80% disability).",
        "description_hi": "80% या उससे अधिक गंभीर दिव्यांगता वाले 18 से 79 वर्ष के बीपीएल नागरिकों को गरिमापूर्ण जीवन हेतु प्रतिमाह सामाजिक सुरक्षा पेंशन।",
        "primary_category": "Differently Abled Support",
        "category": "Differently Abled Support",
        "ministry": "Ministry of Rural Development",
        "department": "National Social Assistance Programme (NSAP)",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["disability", "pension"],
        "target_beneficiaries": ["Persons aged 18-79 living below poverty line with severe or multiple disabilities (minimum 80% benchmark disability)"],
        "eligibility_rules": {
            "disability": True,
            "income": {"max": 100000},
            "states": ["ALL"],
            "age": {"min": 18, "max": 79}
        },
        "benefits": ["Monthly pension of ₹1,000 to ₹3,000 per month (combined Central and State assistance) credited directly into bank account via DBT", "Free assistive devices and priority in state social welfare welfare allocations"],
        "documents": ["Disability Certificate / UDID Card showing ≥80% disability", "BPL Certificate / Ration Card", "Aadhaar Card", "Bank Passbook"],
        "application_steps": ["Apply online via nsap.nic.in or at Block Social Welfare Office", "Medical officer and administrative verification", "Direct bank credit per month"],
        "official_url": "https://nsap.nic.in/",
        "source_url": "https://rural.nic.in/",
        "source_name": "Ministry of Rural Development",
        "verification_status": "Verified",
        "active": True,
        "tags": ["disability", "pension", "igndps", "nsap", "differently-abled", "bpl", "udid"]
    },
    {
        "slug": "national-family-benefit-scheme-nfbs",
        "scheme_code": "SCH-CENTRAL-SOC-001",
        "name": "National Family Benefit Scheme (NFBS)",
        "name_hi": "राष्ट्रीय पारिवारिक लाभ योजना (NFBS)",
        "description": "Provides immediate lump-sum financial grant of ₹20,000 to a bereaved BPL family upon the untimely death of the primary breadwinner aged between 18 and 59 years.",
        "description_hi": "बीपीएल परिवार के मुख्य कमाऊ मुखिया (18 से 59 वर्ष) की असामयिक मृत्यु पर शोकाकुल परिवार को तात्कालिक आर्थिक संबल हेतु ₹20,000 की एकमुश्त सहायता।",
        "primary_category": "Financial Assistance",
        "category": "Financial Assistance",
        "ministry": "Ministry of Rural Development",
        "department": "National Social Assistance Programme (NSAP)",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["financial", "social_welfare"],
        "target_beneficiaries": ["BPL families where the primary earning breadwinner (male or female) aged 18 to 59 years has passed away"],
        "eligibility_rules": {
            "income": {"max": 60000},
            "states": ["ALL"],
            "age": {"min": 18, "max": 100}
        },
        "benefits": ["One-time lump-sum grant of ₹20,000 paid directly into the bank account of the surviving spouse or eldest family member to prevent destitution", "No deduction or repayment"],
        "documents": ["Death Certificate of primary breadwinner (mentioning age between 18-59 years)", "BPL Ration Card / Income Certificate issued by Revenue Authority", "Aadhaar Card of applicant", "Bank Account Details"],
        "application_steps": ["Submit application within 1 year of death at Block Development Office or via state portal (e.g. nfbs.upsdc.gov.in)", "Tehsildar verifies family dependency", "Sanction by District Social Welfare Officer and payment release via DBT"],
        "official_url": "https://nsap.nic.in/",
        "source_url": "https://rural.nic.in/",
        "source_name": "Ministry of Rural Development",
        "verification_status": "Verified",
        "active": True,
        "tags": ["financial", "family-benefit", "nfbs", "death-grant", "bpl", "social-welfare", "dbt"]
    },
    {
        "slug": "pm-svamitva-yojana",
        "scheme_code": "SCH-CENTRAL-RUR-001",
        "name": "SVAMITVA Scheme (Survey of Villages and Mapping with Improvised Technology in Village Areas)",
        "name_hi": "स्वामित्व योजना (ग्रामीण आबादी क्षेत्र ड्रोन सर्वेक्षण एवं संपत्ति कार्ड)",
        "description": "Reformative scheme using high-resolution drone mapping to provide legal ownership 'Property Cards' (Gharauni / Sampatti Patra) to rural household owners for their inhabited land (Abadi).",
        "description_hi": "ग्रामीण आबादी क्षेत्रों में ड्रोन तकनीक से भूमि सर्वेक्षण कर ग्रामीणों को उनकी रिहायशी संपत्ति का मालिकाना कानूनी दस्तावेज (संपत्ति कार्ड / घरौनी) प्रदान करना।",
        "primary_category": "Housing & Shelter",
        "category": "Housing & Shelter",
        "ministry": "Ministry of Panchayati Raj",
        "department": "Survey of India / Ministry of Panchayati Raj",
        "level": "Central",
        "states": ["ALL"],
        "intents": ["housing", "financial"],
        "target_beneficiaries": ["Rural citizens owning houses in village inhabited (Abadi / Lal Dora) areas across all States and UTs"],
        "eligibility_rules": {
            "area": "Rural",
            "states": ["ALL"],
            "age": {"min": 18, "max": 100}
        },
        "benefits": ["Official legal Property Card (Gharauni) validating ownership of residential houses in rural abadi", "Enables rural citizens to leverage their property as collateral to take bank home loans and business loans", "Reduces village land disputes and enables accurate local tax collection by Gram Panchayats"],
        "documents": ["Aadhaar Card", "Mobile number", "Identification by Gram Panchayat during ground survey"],
        "application_steps": ["Drone flying conducted over village abadi by Survey of India teams", "Ground truth verification by Revenue/Panchayat officials with village elders", "Issuance and digital download of SVAMITVA Property Card"],
        "official_url": "https://svamitva.nic.in/",
        "source_url": "https://panchayat.gov.in/",
        "source_name": "Ministry of Panchayati Raj",
        "verification_status": "Verified",
        "active": True,
        "tags": ["housing", "svamitva", "property-card", "rural", "drone-survey", "gharauni", "ownership"]
    }
]
