"""Curated State Government Welfare Schemes - Northern States (UP, RJ, PB, HR, UK, HP, DL)."""

from typing import Any, Dict, List

STATE_SCHEMES_NORTH: List[Dict[str, Any]] = [
    # =============================================================
    # UTTAR PRADESH
    # =============================================================
    {
        "slug": "up-post-matric-scholarship-obc",
        "scheme_code": "SCH-UP-EDU-001",
        "name": "Uttar Pradesh Post-Matric Scholarship & Fee Reimbursement (OBC)",
        "name_hi": "उत्तर प्रदेश दशमोत्तर छात्रवृत्ति एवं शुल्क प्रतिपूर्ति (अन्य पिछड़ा वर्ग)",
        "description": "Uttar Pradesh state scholarship providing complete tuition fee reimbursement and monthly maintenance stipend for OBC students enrolled in Class 11, 12, undergraduate, postgraduate, and professional degree courses in UP.",
        "description_hi": "उत्तर प्रदेश के अन्य पिछड़ा वर्ग (OBC) के छात्र-छात्राओं हेतु 11वीं, 12वीं, स्नातक एवं परास्नातक स्तर पर शुल्क प्रतिपूर्ति एवं छात्रवृत्ति।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Backward Classes Welfare Department, Government of Uttar Pradesh",
        "department": "Backward Classes Welfare Department",
        "level": "State",
        "states": ["Uttar Pradesh"],
        "intents": ["education"],
        "target_beneficiaries": ["OBC students domiciled in Uttar Pradesh pursuing post-matric studies with family income below ₹2.5 Lakh"],
        "eligibility_rules": {
            "states": ["Uttar Pradesh"],
            "category": ["OBC"],
            "occupation": ["student"],
            "income": {"max": 250000},
            "age": {"min": 15, "max": 35}
        },
        "benefits": ["Full tuition fee reimbursement as approved by the State Fee Fixation Committee", "Maintenance allowance directly credited via DBT to Aadhaar-seeded bank account"],
        "documents": ["Uttar Pradesh Domicile Certificate", "OBC Caste Certificate verified on UP eDistrict", "Income Certificate (≤ ₹2.5 Lakh)", "Marksheets", "Fee Receipt", "Aadhaar Card"],
        "application_steps": ["Register on scholarship.up.gov.in portal", "Fill academic, personal, and fee details", "Submit printout to college for nodal officer verification"],
        "official_url": "https://scholarship.up.gov.in/",
        "source_url": "https://backwardwelfare.up.gov.in/",
        "source_name": "Government of Uttar Pradesh",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "scholarship", "uttar-pradesh", "obc", "post-matric", "student", "tuition"]
    },
    {
        "slug": "up-post-matric-scholarship-sc-st",
        "scheme_code": "SCH-UP-EDU-002",
        "name": "Uttar Pradesh Post-Matric Scholarship & Fee Reimbursement (SC/ST)",
        "name_hi": "उत्तर प्रदेश दशमोत्तर छात्रवृत्ति एवं शुल्क प्रतिपूर्ति (अनुसूचित जाति / जनजाति)",
        "description": "State welfare scholarship covering non-refundable fees and living allowances for SC and ST students studying in post-matric and higher educational institutions in Uttar Pradesh.",
        "description_hi": "उत्तर प्रदेश के अनुसूचित जाति एवं अनुसूचित जनजाति के छात्र-छात्राओं हेतु कक्षा 11वीं से उच्च शिक्षा तक निःशुल्क शिक्षा एवं छात्रवृत्ति।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Social Welfare Department, Government of Uttar Pradesh",
        "department": "Social Welfare Department",
        "level": "State",
        "states": ["Uttar Pradesh"],
        "intents": ["education"],
        "target_beneficiaries": ["SC and ST students domiciled in Uttar Pradesh with family income below ₹2.5 Lakh/year"],
        "eligibility_rules": {
            "states": ["Uttar Pradesh"],
            "category": ["SC", "ST"],
            "occupation": ["student"],
            "income": {"max": 250000},
            "age": {"min": 15, "max": 35}
        },
        "benefits": ["Complete fee waiver/reimbursement of institutional tuition charges", "Monthly maintenance allowance credited directly to student bank account"],
        "documents": ["UP Domicile Certificate", "SC/ST Caste Certificate", "Income Certificate", "High School & Intermediate Marksheets", "Aadhaar Card", "Bank Passbook"],
        "application_steps": ["Apply via scholarship.up.gov.in", "Online verification via DigiLocker / Aadhaar", "Institute submits verified master data to Social Welfare Department"],
        "official_url": "https://scholarship.up.gov.in/",
        "source_url": "https://socialwelfare.up.gov.in/",
        "source_name": "Social Welfare Department UP",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "scholarship", "uttar-pradesh", "sc", "st", "student", "fee-reimbursement"]
    },
    {
        "slug": "up-post-matric-scholarship-general",
        "scheme_code": "SCH-UP-EDU-003",
        "name": "Uttar Pradesh Post-Matric Scholarship & Fee Reimbursement (General Category Poor)",
        "name_hi": "उत्तर प्रदेश दशमोत्तर छात्रवृत्ति एवं शुल्क प्रतिपूर्ति (सामान्य वर्ग निर्धन)",
        "description": "State financial assistance for meritorious and economically disadvantaged General category students domiciled in UP with annual family income up to ₹2,00,000.",
        "description_hi": "उत्तर प्रदेश के सामान्य वर्ग के निर्धन छात्र-छात्राओं (वार्षिक पारिवारिक आय ₹2 लाख तक) हेतु शुल्क प्रतिपूर्ति एवं छात्रवृत्ति सहायता।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Social Welfare Department, Government of Uttar Pradesh",
        "department": "Social Welfare Department",
        "level": "State",
        "states": ["Uttar Pradesh"],
        "intents": ["education"],
        "target_beneficiaries": ["Economically poor General category students studying in Class 11, 12, degree, or professional programs in UP"],
        "eligibility_rules": {
            "states": ["Uttar Pradesh"],
            "category": ["General", "EWS"],
            "occupation": ["student"],
            "income": {"max": 200000},
            "age": {"min": 15, "max": 35}
        },
        "benefits": ["Reimbursement of tuition fees as per government slabs", "Maintenance stipend credited directly to bank account"],
        "documents": ["Domicile Certificate of UP", "Income Certificate (≤ ₹2 Lakh/year)", "Previous Class Passing Marksheet", "Admission Fee Receipt", "Aadhaar Card"],
        "application_steps": ["Submit application on scholarship.up.gov.in under General Category link", "Institutional verification and district sanction"],
        "official_url": "https://scholarship.up.gov.in/",
        "source_url": "https://socialwelfare.up.gov.in/",
        "source_name": "Social Welfare Department UP",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "scholarship", "uttar-pradesh", "general", "ews", "student", "dbt"]
    },
    {
        "slug": "up-mukhyamantri-kanya-sumangala-yojana",
        "scheme_code": "SCH-UP-WOM-001",
        "name": "Mukhyamantri Kanya Sumangala Yojana (Uttar Pradesh)",
        "name_hi": "मुख्यमंत्री कन्या सुमंगला योजना (उत्तर प्रदेश)",
        "description": "Conditional cash transfer scheme providing ₹25,000 in six milestone stages from birth to graduation to promote girl child education, health, and gender equality in UP.",
        "description_hi": "उत्तर प्रदेश में बालिकाओं के जन्म से लेकर स्नातक तक की शिक्षा हेतु 6 चरणों में कुल ₹25,000 की वित्तीय सहायता।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Women and Child Development Department, Uttar Pradesh",
        "department": "Women and Child Development Department",
        "level": "State",
        "states": ["Uttar Pradesh"],
        "intents": ["women_child", "education"],
        "target_beneficiaries": ["Girl children born and domiciled in UP in families with annual income up to ₹3 Lakh (maximum 2 daughters per family)"],
        "eligibility_rules": {
            "gender": ["female"],
            "states": ["Uttar Pradesh"],
            "income": {"max": 300000},
            "age": {"min": 0, "max": 25}
        },
        "benefits": ["Total financial assistance of ₹25,000 disbursed across 6 stages: Birth (₹5,000), Immunization (₹2,000), Class 1 (₹3,000), Class 6 (₹3,000), Class 9 (₹5,000), Degree/Diploma admission (₹7,000)"],
        "documents": ["Birth Certificate of Girl Child", "UP Domicile Certificate", "Family Income Certificate (≤ ₹3 Lakh)", "School/College Admission Receipt", "Bank Passbook of mother/daughter"],
        "application_steps": ["Apply online through mksy.up.gov.in portal", "Upload stage-specific documentation", "Verification by Block Development Officer / SDM and DBT release"],
        "official_url": "https://mksy.up.gov.in/",
        "source_url": "https://womenchild.up.gov.in/",
        "source_name": "Government of Uttar Pradesh",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "girl-child", "kanya-sumangala", "uttar-pradesh", "education", "dbt"]
    },
    {
        "slug": "up-old-age-pension-scheme",
        "scheme_code": "SCH-UP-PEN-001",
        "name": "Uttar Pradesh Vridhavastha Pension Yojana (Old Age Pension)",
        "name_hi": "उत्तर प्रदेश वृद्धावस्था पेंशन योजना",
        "description": "State pension providing monthly financial assistance of ₹1,000 directly to destitute elderly citizens aged 60 years and above domiciled in Uttar Pradesh.",
        "description_hi": "उत्तर प्रदेश के 60 वर्ष या उससे अधिक आयु के वृद्धजनों को प्रतिमाह ₹1,000 (तिमाही ₹3,000) की नियमित पेंशन सहायता सीधे बैंक खाते में।",
        "primary_category": "Social Security & Pension",
        "category": "Social Security & Pension",
        "ministry": "Social Welfare Department, Government of Uttar Pradesh",
        "department": "Social Welfare Department",
        "level": "State",
        "states": ["Uttar Pradesh"],
        "intents": ["pension"],
        "target_beneficiaries": ["Elderly citizens of UP aged 60 years or older living below poverty line (rural income ≤ ₹46,080/yr; urban ≤ ₹56,460/yr)"],
        "eligibility_rules": {
            "states": ["Uttar Pradesh"],
            "age": {"min": 60, "max": 120},
            "income": {"max": 60000}
        },
        "benefits": ["Monthly pension of ₹1,000 (disbursed as ₹3,000 per quarter) directly into bank account via PFMS DBT", "Health assistance and social security"],
        "documents": ["Aadhaar Card", "UP Domicile / Residence Proof", "Income Certificate issued by Tehsildar", "Age Certificate / Voter ID", "Bank Passbook"],
        "application_steps": ["Apply on sspy-up.gov.in portal", "Select 'Old Age Pension' and submit details", "Block / Tehsil inquiry and District Social Welfare Officer sanction"],
        "official_url": "https://sspy-up.gov.in/",
        "source_url": "https://socialwelfare.up.gov.in/",
        "source_name": "Social Welfare Department UP",
        "verification_status": "Verified",
        "active": True,
        "tags": ["pension", "senior-citizens", "uttar-pradesh", "old-age", "sspy", "dbt"]
    },
    {
        "slug": "up-divyangjan-pension-scheme",
        "scheme_code": "SCH-UP-DIS-001",
        "name": "Uttar Pradesh Divyangjan Pension Yojana",
        "name_hi": "उत्तर प्रदेश दिव्यांगजन पेंशन योजना",
        "description": "Monthly disability pension of ₹1,000 provided by Uttar Pradesh Government to persons with 40% or more benchmark disability living in economically weaker households.",
        "description_hi": "उत्तर प्रदेश के 40% या अधिक दिव्यांगता वाले नागरिकों को गरिमापूर्ण जीवन हेतु ₹1,000 प्रतिमाह की पेंशन सहायता।",
        "primary_category": "Differently Abled Support",
        "category": "Differently Abled Support",
        "ministry": "Empowerment of Persons with Disabilities Department, Uttar Pradesh",
        "department": "Divyangjan Sashaktikaran Vibhag",
        "level": "State",
        "states": ["Uttar Pradesh"],
        "intents": ["disability", "pension"],
        "target_beneficiaries": ["Persons with ≥40% disability domiciled in UP with annual household income up to ₹60,000"],
        "eligibility_rules": {
            "states": ["Uttar Pradesh"],
            "disability": True,
            "income": {"max": 60000},
            "age": {"min": 18, "max": 100}
        },
        "benefits": ["Monthly pension of ₹1,000 credited quarterly directly via DBT into beneficiary's bank account"],
        "documents": ["Disability Certificate issued by CMO (≥40% disability)", "UP Residence Proof", "Income Certificate", "Aadhaar Card", "Bank Account Passbook"],
        "application_steps": ["Submit online application on sspy-up.gov.in under Divyang Pension link", "Verification by Gram Panchayat / Lekhpal and District Divyangjan Officer sanction"],
        "official_url": "https://sspy-up.gov.in/",
        "source_url": "http://uphwo.up.nic.in/",
        "source_name": "Divyangjan Sashaktikaran Vibhag UP",
        "verification_status": "Verified",
        "active": True,
        "tags": ["disability", "pension", "uttar-pradesh", "differently-abled", "sspy", "dbt"]
    },
    {
        "slug": "up-mukhyamantri-abhyudaya-yojana",
        "scheme_code": "SCH-UP-EDU-004",
        "name": "Mukhyamantri Abhyudaya Yojana (Free Competitive Exam Coaching)",
        "name_hi": "मुख्यमंत्री अभ्युदय योजना (निःशुल्क प्रतियोगी परीक्षा कोचिंग)",
        "description": "Provides free comprehensive high-quality coaching, study materials, and tablet support for underprivileged youth preparing for UPSC, UPPSC, JEE, NEET, NDA, CDS, and banking exams.",
        "description_hi": "उत्तर प्रदेश के मेधावी एवं निर्धन युवाओं को सिविल सेवा (UPSC/UPPSC), जेईई, नीट, एनडीए, सीडीएस आदि हेतु निःशुल्क ऑफलाइन व ऑनलाइन कोचिंग।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Social Welfare Department, Government of Uttar Pradesh",
        "department": "Social Welfare Department",
        "level": "State",
        "states": ["Uttar Pradesh"],
        "intents": ["education", "jobs"],
        "target_beneficiaries": ["Students of Uttar Pradesh preparing for competitive exams who cannot afford private coaching fees"],
        "eligibility_rules": {
            "states": ["Uttar Pradesh"],
            "occupation": ["student", "unemployed"],
            "income": {"max": 600000},
            "age": {"min": 17, "max": 35}
        },
        "benefits": ["Free physical and virtual classroom coaching by IAS, IPS, and subject matter experts at divisional headquarters", "Free e-learning content and mentorship", "Free tablet distribution for selected top performers"],
        "documents": ["Aadhaar Card", "UP Domicile Certificate", "Educational Qualification Marksheets", "Passport Photograph"],
        "application_steps": ["Register on abhyuday.up.gov.in", "Select desired examination course and nearest divisional center", "Appear in state eligibility screening test to secure seat"],
        "official_url": "http://abhyuday.up.gov.in/",
        "source_url": "https://socialwelfare.up.gov.in/",
        "source_name": "Government of Uttar Pradesh",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "coaching", "upsc", "neet", "jee", "uttar-pradesh", "abhyudaya", "competitive-exams"]
    },
    {
        "slug": "up-odop-margin-money-scheme",
        "scheme_code": "SCH-UP-BIZ-001",
        "name": "One District One Product (ODOP) Margin Money Subsidy Scheme",
        "name_hi": "एक जनपद एक उत्पाद (ODOP) मार्जिन मनी सब्सिडी योजना",
        "description": "Financial assistance scheme by MSME UP providing margin money subsidies of up to 25% (up to ₹20 Lakhs) on bank loans to establish or expand district-specific traditional product units.",
        "description_hi": "उत्तर प्रदेश के पारंपरिक जिला उत्पादों (जैसे भदोही कालीन, मुरादाबाद पीतल, अलीगढ़ ताले) के निर्माण एवं व्यवसाय विस्तार हेतु 25% तक मार्जिन मनी अनुदान।",
        "primary_category": "Business & Self Employment",
        "category": "Business & Self Employment",
        "ministry": "MSME and Export Promotion Department, Uttar Pradesh",
        "department": "Directorate of Industries",
        "level": "State",
        "states": ["Uttar Pradesh"],
        "intents": ["business"],
        "target_beneficiaries": ["Artisans, micro-entrepreneurs, and manufacturing units producing products identified under UP's ODOP list"],
        "eligibility_rules": {
            "states": ["Uttar Pradesh"],
            "occupation": ["entrepreneur", "artisan", "self_employed"],
            "age": {"min": 18, "max": 65}
        },
        "benefits": ["Margin money subsidy of 25% for projects up to ₹25 Lakh (max ₹6.25 Lakh); 20% for projects ₹25-50 Lakh; 10% for projects > ₹50 Lakh (max ₹20 Lakh)", "Common facility center access and skill training"],
        "documents": ["Aadhaar and PAN Card", "UP Domicile Proof", "Detailed Project Report (DPR)", "Bank Loan Application Copy", "Proof of ODOP product trade"],
        "application_steps": ["Apply online on diupmsme.upsdc.gov.in portal", "Select ODOP Margin Money Scheme", "District Level Committee (DLC) evaluation and bank sanction"],
        "official_url": "http://diupmsme.upsdc.gov.in/",
        "source_url": "http://odopup.in/",
        "source_name": "MSME Department Uttar Pradesh",
        "verification_status": "Verified",
        "active": True,
        "tags": ["business", "odop", "uttar-pradesh", "artisan", "msme", "subsidy", "margin-money"]
    },

    # =============================================================
    # RAJASTHAN
    # =============================================================
    {
        "slug": "rajasthan-mukhyamantri-ayushman-arogya-yojana",
        "scheme_code": "SCH-RJ-HLT-001",
        "name": "Rajasthan Mukhyamantri Ayushman Arogya (MAA) Yojana (Formerly Chiranjeevi)",
        "name_hi": "राजस्थान मुख्यमंत्री आयुष्मान आरोग्य (माँ) योजना (चिरंजीवी)",
        "description": "Universal health insurance scheme of Rajasthan offering cashless hospitalization cover of up to ₹25 Lakhs per family per year across empaneled public and private hospitals.",
        "description_hi": "राजस्थान के परिवारों को गंभीर बीमारियों के उपचार हेतु प्रति परिवार प्रति वर्ष ₹25 लाख तक का कैशलेस अस्पताल स्वास्थ्य बीमा।",
        "primary_category": "Healthcare",
        "category": "Healthcare",
        "ministry": "Medical, Health and Family Welfare Department, Rajasthan",
        "department": "State Health Assurance Agency",
        "level": "State",
        "states": ["Rajasthan"],
        "intents": ["healthcare"],
        "target_beneficiaries": ["All families domiciled in Rajasthan possessing Jan Aadhaar card (free for NFSA, SECC, small/marginal farmers; nominal premium for others)"],
        "eligibility_rules": {
            "states": ["Rajasthan"],
            "age": {"min": 0, "max": 100}
        },
        "benefits": ["Cashless medical cover of up to ₹25 Lakhs per family per year", "Includes day care, critical organ transplants, cancer treatment, and accidental insurance of ₹10 Lakhs"],
        "documents": ["Jan Aadhaar Card / Jan Aadhaar Acknowledgment Receipt", "Aadhaar Card"],
        "application_steps": ["Register through Rajasthan SSO portal (sso.rajasthan.gov.in) or nearest e-Mitra kiosk", "Free auto-inclusion for NFSA, BPL, and marginal farmers; others pay ₹850/year premium", "Avail treatment using Jan Aadhaar at empaneled hospitals"],
        "official_url": "https://health.rajasthan.gov.in/",
        "source_url": "https://sso.rajasthan.gov.in/",
        "source_name": "Government of Rajasthan",
        "verification_status": "Verified",
        "active": True,
        "tags": ["healthcare", "rajasthan", "chiranjeevi", "ayushman-arogya", "jan-aadhaar", "cashless", "medical"]
    },
    {
        "slug": "rajasthan-mukhyamantri-yuva-sambal-yojana",
        "scheme_code": "SCH-RJ-JOB-001",
        "name": "Rajasthan Mukhyamantri Yuva Sambal Yojana (Unemployment Allowance)",
        "name_hi": "राजस्थान मुख्यमंत्री युवा संबल योजना (बेरोजगारी भत्ता)",
        "description": "Provides monthly unemployment allowance of ₹4,000 for male graduates and ₹4,500 for female/transgender/specially-abled graduates in Rajasthan along with skill internship.",
        "description_hi": "राजस्थान के शिक्षित बेरोजगार स्नातक युवाओं को ₹4,000 (पुरुष) तथा ₹4,500 (महिला/दिव्यांग) मासिक बेरोजगारी भत्ता एवं कौशल इंटर्नशिप।",
        "primary_category": "Employment & Skills",
        "category": "Employment & Skills",
        "ministry": "Department of Skill, Employment and Entrepreneurship, Rajasthan",
        "department": "Employment Department",
        "level": "State",
        "states": ["Rajasthan"],
        "intents": ["jobs", "financial"],
        "target_beneficiaries": ["Unemployed graduates domiciled in Rajasthan aged up to 30 years (35 years for female/SC/ST/Divyang) with family income up to ₹2 Lakh"],
        "eligibility_rules": {
            "states": ["Rajasthan"],
            "occupation": ["unemployed"],
            "income": {"max": 200000},
            "age": {"min": 21, "max": 35}
        },
        "benefits": ["Monthly financial allowance of ₹4,000 for males; ₹4,500 for women, Transgender, and Divyangjan for up to 2 years", "Daily 4 hours internship in government offices to gain administrative experience"],
        "documents": ["Jan Aadhaar Card", "Graduation Degree / Marksheet", "Income Certificate (≤ ₹2 Lakh/year)", "Rajasthan Domicile Certificate", "Bank Passbook"],
        "application_steps": ["Log in to Rajasthan SSO portal and navigate to Employment Exchange", "Apply under Mukhyamantri Yuva Sambal Yojana", "Join assigned department internship"],
        "official_url": "https://employment.livelihoods.rajasthan.gov.in/",
        "source_url": "https://sso.rajasthan.gov.in/",
        "source_name": "Government of Rajasthan",
        "verification_status": "Verified",
        "active": True,
        "tags": ["jobs", "unemployment-allowance", "rajasthan", "graduates", "yuva-sambal", "financial-support"]
    },
    {
        "slug": "rajasthan-post-matric-scholarship",
        "scheme_code": "SCH-RJ-EDU-001",
        "name": "Rajasthan Post-Matric Scholarship Scheme (SC/ST/OBC/SBC/EBC)",
        "name_hi": "राजस्थान उत्तर मैट्रिक छात्रवृत्ति योजना",
        "description": "Scholarship and complete fee reimbursement for SC, ST, OBC, SBC, and EBC students studying in Class 11, 12, college degrees, and professional courses in Rajasthan.",
        "description_hi": "राजस्थान के अनुसूचित जाति, जनजाति, अन्य पिछड़ा वर्ग एवं विशेष पिछड़ा वर्ग के विद्यार्थियों हेतु सम्पूर्ण शिक्षण शुल्क प्रतिपूर्ति एवं छात्रवृत्ति।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Social Justice and Empowerment Department, Rajasthan",
        "department": "Social Justice and Empowerment Department",
        "level": "State",
        "states": ["Rajasthan"],
        "intents": ["education"],
        "target_beneficiaries": ["SC/ST students (income up to ₹2.5 Lakh) and OBC/EBC students (income up to ₹1.5 Lakh) domiciled in Rajasthan"],
        "eligibility_rules": {
            "states": ["Rajasthan"],
            "category": ["SC", "ST", "OBC", "EWS"],
            "occupation": ["student"],
            "income": {"max": 250000},
            "age": {"min": 15, "max": 35}
        },
        "benefits": ["100% non-refundable course fee reimbursement directly deposited in student's bank account", "Monthly maintenance allowance throughout academic year"],
        "documents": ["Jan Aadhaar Card", "Caste Certificate", "Income Certificate", "Course Fee Receipt", "Previous Year Marksheet"],
        "application_steps": ["Apply online via SSO Rajasthan (sje.rajasthan.gov.in/scholarship)", "Institute verification through online portal", "District SJE officer sanction and DBT payment"],
        "official_url": "https://sjmsnew.rajasthan.gov.in/",
        "source_url": "https://sje.rajasthan.gov.in/",
        "source_name": "Government of Rajasthan",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "scholarship", "rajasthan", "post-matric", "jan-aadhaar", "student"]
    },

    # =============================================================
    # PUNJAB & HARYANA
    # =============================================================
    {
        "slug": "punjab-ashirwad-scheme",
        "scheme_code": "SCH-PB-WOM-001",
        "name": "Punjab Ashirwad Scheme (Shagun Scheme for Girls Marriage)",
        "name_hi": "पंजाब आशीर्वाद योजना (शगुन योजना)",
        "description": "Financial assistance of ₹51,000 provided by Punjab Government to poor families (SC/BC/EWS) on the marriage of daughters to prevent indebtedness.",
        "description_hi": "पंजाब में अनुसूचित जाति, पिछड़ा वर्ग एवं आर्थिक रूप से कमजोर परिवारों की बेटियों के विवाह पर ₹51,000 का सरकारी शगुन/आशीर्वाद अनुदान।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Department of Social Justice, Empowerment and Minorities, Punjab",
        "department": "Social Justice Department",
        "level": "State",
        "states": ["Punjab"],
        "intents": ["women_child", "financial"],
        "target_beneficiaries": ["SC, BC, and economically backward families domiciled in Punjab with annual income below ₹32,790"],
        "eligibility_rules": {
            "states": ["Punjab"],
            "gender": ["female"],
            "income": {"max": 32790},
            "age": {"min": 18, "max": 40}
        },
        "benefits": ["One-time financial grant of ₹51,000 credited directly into the bank account of the bride/mother"],
        "documents": ["Punjab Residence Proof", "Caste Certificate", "Income Certificate", "Age Proof of Bride (≥18 years)", "Marriage Certificate / Card", "Bank Account Details"],
        "application_steps": ["Submit application on ashirwad.punjab.gov.in or through District Social Justice Officer", "Verification by Tehsil Welfare Officer and DBT sanction"],
        "official_url": "https://punjab.gov.in/",
        "source_url": "https://welfarepunjab.gov.in/",
        "source_name": "Government of Punjab",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "marriage", "punjab", "ashirwad", "shagun", "financial-grant"]
    },
    {
        "slug": "haryana-chirayu-yojana",
        "scheme_code": "SCH-HR-HLT-001",
        "name": "Chirayu Haryana Yojana (Extended Ayushman Bharat)",
        "name_hi": "चिरायु हरियाणा योजना (विस्तारित आयुष्मान भारत)",
        "description": "State expanded health assurance program covering families verified under Parivar Pehchan Patra (PPP) with annual income up to ₹3,00,000 with ₹5 Lakh free hospitalization cover.",
        "description_hi": "हरियाणा में परिवार पहचान पत्र (PPP) धारक ₹3 लाख तक की वार्षिक आय वाले परिवारों को प्रतिवर्ष ₹5 लाख तक का निःशुल्क कैशलेस अस्पताल उपचार।",
        "primary_category": "Healthcare",
        "category": "Healthcare",
        "ministry": "Health Department, Haryana",
        "department": "Haryana Ayushman Bharat Health Protection Authority",
        "level": "State",
        "states": ["Haryana"],
        "intents": ["healthcare"],
        "target_beneficiaries": ["Families verified in Haryana Parivar Pehchan Patra (PPP) with annual income up to ₹3.00 Lakh (free up to ₹1.80 Lakh; ₹1,500 contribution for ₹1.80-3.00 Lakh)"],
        "eligibility_rules": {
            "states": ["Haryana"],
            "income": {"max": 300000},
            "age": {"min": 0, "max": 100}
        },
        "benefits": ["Cashless medical treatment up to ₹5,00,000 per family per year in empaneled private and civil hospitals", "Card issuance linked with Parivar Pehchan Patra (PPP) Family ID"],
        "documents": ["Parivar Pehchan Patra (PPP) Family ID", "Aadhaar Card of family members"],
        "application_steps": ["Check eligibility on chirayuayushmanharyana.in using Family ID", "Pay nominal token contribution if income between ₹1.80L - ₹3.00L", "Download Chirayu Golden Card"],
        "official_url": "https://chirayuayushmanharyana.in/",
        "source_url": "https://haryanahealth.gov.in/",
        "source_name": "Government of Haryana",
        "verification_status": "Verified",
        "active": True,
        "tags": ["healthcare", "haryana", "chirayu", "parivar-pehchan-patra", "ppp", "cashless", "ayushman"]
    },
    {
        "slug": "haryana-old-age-samman-allowance",
        "scheme_code": "SCH-HR-PEN-001",
        "name": "Haryana Old Age Samman Allowance (Vridhavastha Samman)",
        "name_hi": "हरियाणा वृद्धावस्था सम्मान भत्ता",
        "description": "Highest state old age pension in India providing ₹3,000 per month automatically sanctioned to senior citizens aged 60+ based on Parivar Pehchan Patra data.",
        "description_hi": "हरियाणा के 60 वर्ष या उससे अधिक आयु के वरिष्ठ नागरिकों को बिना किसी सरकारी दफ्तर के चक्कर लगाए ₹3,000 प्रतिमाह का स्वतः सम्मान भत्ता।",
        "primary_category": "Social Security & Pension",
        "category": "Social Security & Pension",
        "ministry": "Social Justice, Empowerment, Welfare of SCs & BCs Department, Haryana",
        "department": "Social Justice Department",
        "level": "State",
        "states": ["Haryana"],
        "intents": ["pension"],
        "target_beneficiaries": ["Senior citizens aged 60+ domiciled in Haryana with combined husband-wife income not exceeding ₹3,00,000 per year"],
        "eligibility_rules": {
            "states": ["Haryana"],
            "age": {"min": 60, "max": 120},
            "income": {"max": 300000}
        },
        "benefits": ["Monthly pension allowance of ₹3,000 directly credited into bank account", "Proactive auto-sanction through Parivar Pehchan Patra (PPP) upon attaining 60 years"],
        "documents": ["Parivar Pehchan Patra (Family ID)", "Aadhaar Card", "Bank Account linked with Family ID"],
        "application_steps": ["Citizen receives SMS/call upon turning 60 based on PPP data", "Citizen gives consent to field verification officer", "Pension starts automatically without submitting manual forms"],
        "official_url": "https://pension.socialjusticehry.gov.in/",
        "source_url": "https://meraparivar.haryana.gov.in/",
        "source_name": "Government of Haryana",
        "verification_status": "Verified",
        "active": True,
        "tags": ["pension", "senior-citizens", "haryana", "samman-allowance", "ppp", "dbt", "elderly"]
    },

    # =============================================================
    # DELHI
    # =============================================================
    {
        "slug": "delhi-higher-education-and-skill-development-guarantee",
        "scheme_code": "SCH-DL-EDU-001",
        "name": "Delhi Higher Education and Skill Development Guarantee Scheme",
        "name_hi": "दिल्ली उच्च शिक्षा एवं कौशल विकास ऋण गारंटी योजना",
        "description": "Government of NCT of Delhi provides credit guarantee for educational loans up to ₹10 Lakhs without any third-party guarantee or collateral for students pursuing higher education in Delhi.",
        "description_hi": "दिल्ली के छात्रों को स्नातक, स्नातकोत्तर एवं डिप्लोमा पाठ्यक्रमों हेतु बिना किसी अचल संपत्ति बंधक अथवा गारंटर के ₹10 लाख तक का शिक्षा ऋण।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Directorate of Higher Education, Government of NCT of Delhi",
        "department": "Higher Education Department",
        "level": "State",
        "states": ["Delhi"],
        "intents": ["education", "financial"],
        "target_beneficiaries": ["Students who have passed Class 10 and 12 from Delhi seeking loans for higher studies in recognized colleges/universities in Delhi"],
        "eligibility_rules": {
            "states": ["Delhi"],
            "occupation": ["student"],
            "age": {"min": 17, "max": 35}
        },
        "benefits": ["Collateral-free educational loan up to ₹10 Lakhs", "Delhi Government provides 100% guarantee to lending banks through Higher Education and Skill Development Guarantee Fund", "Moratorium period of Course duration + 1 year"],
        "documents": ["Class 10 and 12 marksheets and passing certificates from schools in Delhi", "Admission Proof in recognized college in Delhi", "Aadhaar Card", "Fee schedule from institution"],
        "application_steps": ["Apply online through Delhi Government e-District portal or higheredn.delhi.gov.in", "Select lending bank branch", "Bank processes application under state credit guarantee cover"],
        "official_url": "https://higheredn.delhi.gov.in/",
        "source_url": "https://edistrict.delhigovt.nic.in/",
        "source_name": "Government of NCT of Delhi",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "loan", "delhi", "higher-education", "guarantee", "student", "collateral-free"]
    },
    {
        "slug": "delhi-ladli-scheme",
        "scheme_code": "SCH-DL-WOM-001",
        "name": "Delhi Ladli Scheme",
        "name_hi": "दिल्ली लाडली योजना",
        "description": "Financial assistance program promoting girl child education and preventing female foeticide by depositing institutional financial milestones totaling up to ₹36,000.",
        "description_hi": "दिल्ली में बालिकाओं के जन्म एवं स्कूली शिक्षा (कक्षा 1, 6, 9, 10वीं, 12वीं) के विभिन्न स्तरों पर कुल ₹35,000 से ₹36,000 का वित्तीय संचय।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Department of Women and Child Development, Government of NCT of Delhi",
        "department": "WCD Delhi",
        "level": "State",
        "states": ["Delhi"],
        "intents": ["women_child", "education"],
        "target_beneficiaries": ["Girl children born in Delhi or studying in recognized schools in Delhi with family income not exceeding ₹1,00,000/year"],
        "eligibility_rules": {
            "states": ["Delhi"],
            "gender": ["female"],
            "income": {"max": 100000},
            "age": {"min": 0, "max": 21}
        },
        "benefits": ["Milestone deposits: ₹11,000 for institutional birth in Delhi (₹10,000 if home birth); ₹5,000 each upon admission to Class 1, 6, 9, 10, and 12", "Entire accumulated amount with compound interest paid to girl upon passing Class 10/12 and attaining 18 years"],
        "documents": ["Delhi Domicile / Residence Proof for past 3 years", "Birth Certificate of Girl Child", "Family Income Certificate (≤ ₹1 Lakh/yr)", "School Admission Proof", "Aadhaar Card"],
        "application_steps": ["Apply through school where girl is admitted or via edistrict.delhigovt.nic.in", "State Life Insurance Corporation (SBIL / LIC) manages the trust deposit", "Maturity claim submitted upon turning 18"],
        "official_url": "https://wcd.delhi.gov.in/",
        "source_url": "https://edistrict.delhigovt.nic.in/",
        "source_name": "Government of NCT of Delhi",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "girl-child", "delhi", "ladli", "education", "savings"]
    },

    # =============================================================
    # UTTARAKHAND & HIMACHAL PRADESH
    # =============================================================
    {
        "slug": "uttarakhand-gaura-devi-kanya-dhan",
        "scheme_code": "SCH-UK-WOM-001",
        "name": "Nanda Gaura Yojana (Gaura Devi Kanya Dhan Uttarakhand)",
        "name_hi": "नंदा गौरा योजना (उत्तराखंड)",
        "description": "Financial assistance program providing ₹11,000 upon the birth of a girl child and ₹51,000 upon passing Class 12 to encourage girls to pursue higher university education.",
        "description_hi": "उत्तराखंड में बालिका जन्म पर ₹11,000 तथा 12वीं कक्षा उत्तीर्ण करने पर उच्च शिक्षा हेतु ₹51,000 की प्रत्यक्ष वित्तीय सहायता।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Women Empowerment and Child Development Department, Uttarakhand",
        "department": "WECD Uttarakhand",
        "level": "State",
        "states": ["Uttarakhand"],
        "intents": ["women_child", "education"],
        "target_beneficiaries": ["Girl children domiciled in Uttarakhand from families with annual income up to ₹72,000"],
        "eligibility_rules": {
            "states": ["Uttarakhand"],
            "gender": ["female"],
            "income": {"max": 72000},
            "age": {"min": 0, "max": 25}
        },
        "benefits": ["₹11,000 cash grant upon institutional birth of girl child", "₹51,000 one-time grant upon successfully passing Class 12 from any recognized board in Uttarakhand to enroll in higher education"],
        "documents": ["Uttarakhand Domicile / Sthaniya Niwas Praman Patra", "Class 12 Marksheet", "Income Certificate (≤ ₹72,000/yr)", "Birth Certificate", "Aadhaar Card & Bank Account"],
        "application_steps": ["Apply online on nandagaura.uk.gov.in portal", "Verification by Anganwadi worker and Child Development Project Officer (CDPO)", "DBT release directly into girl's account"],
        "official_url": "https://nandagaura.uk.gov.in/",
        "source_url": "https://wecd.uk.gov.in/",
        "source_name": "Government of Uttarakhand",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "girl-child", "uttarakhand", "nanda-gaura", "higher-education", "dbt"]
    },
    {
        "slug": "himachal-mukhya-mantri-swavlamban-yojana",
        "scheme_code": "SCH-HP-BIZ-001",
        "name": "Himachal Pradesh Mukhya Mantri Swavlamban Yojana (MMSY)",
        "name_hi": "हिमाचल प्रदेश मुख्यमंत्री स्वावलंबन योजना (MMSY)",
        "description": "Promotes local entrepreneurship in Himachal Pradesh by providing 25% to 35% capital subsidy and 5% interest subvention for 3 years on bank loans up to ₹1 Crore.",
        "description_hi": "हिमाचल प्रदेश के युवाओं एवं महिलाओं को विनिर्माण, पर्यटन, सेवा एवं कृषि-उद्योग स्थापित करने हेतु ₹1 करोड़ तक के ऋण पर 25% से 35% तक का पूंजीगत अनुदान।",
        "primary_category": "Business & Self Employment",
        "category": "Business & Self Employment",
        "ministry": "Industries Department, Himachal Pradesh",
        "department": "Directorate of Industries",
        "level": "State",
        "states": ["Himachal Pradesh"],
        "intents": ["business", "jobs"],
        "target_beneficiaries": ["Himachali youth aged 18-45 years (up to 50 years for women and widows) setting up new enterprises"],
        "eligibility_rules": {
            "states": ["Himachal Pradesh"],
            "occupation": ["entrepreneur", "unemployed", "self_employed"],
            "age": {"min": 18, "max": 50}
        },
        "benefits": ["Capital investment subsidy: 25% for males, 30% for women, and 35% for SC/ST/Divyang/Widows on project machinery up to ₹1 Crore", "5% interest subsidy for 3 years on term loans", "Land allocation at 50% concessional rates in industrial areas"],
        "documents": ["Bonafide Himachali Certificate", "Detailed Project Report (DPR)", "Aadhaar Card & PAN Card", "Caste / Category certificate", "Bank Sanction Letter"],
        "application_steps": ["Submit project on emerginghimachal.hp.gov.in portal", "District Level Committee (DLC) chaired by Deputy Commissioner approves subsidy", "Bank disburses loan and subsidy released directly to bank"],
        "official_url": "https://emerginghimachal.hp.gov.in/",
        "source_url": "https://himachal.nic.in/",
        "source_name": "Government of Himachal Pradesh",
        "verification_status": "Verified",
        "active": True,
        "tags": ["business", "entrepreneurship", "himachal-pradesh", "subsidy", "mmsy", "startup", "industry"]
    }
]
