"""Curated State Government Welfare Schemes - Southern States (KA, TN, TS, AP, KL)."""

from typing import Any, Dict, List

STATE_SCHEMES_SOUTH: List[Dict[str, Any]] = [
    # =============================================================
    # KARNATAKA
    # =============================================================
    {
        "slug": "karnataka-gruha-lakshmi-scheme",
        "scheme_code": "SCH-KA-WOM-001",
        "name": "Gruha Lakshmi Scheme (Karnataka)",
        "name_hi": "गृह लक्ष्मी योजना (कर्नाटक)",
        "description": "Direct financial empowerment scheme providing monthly direct benefit transfer of ₹2,000 to woman heads of households registered under BPL, Antyodaya, or APL cards in Karnataka.",
        "description_hi": "कर्नाटक के बीपीएल, अंत्योदय एवं एपीएल परिवारों की महिला मुखिया को आर्थिक आत्मनिर्भरता हेतु प्रतिमाह ₹2,000 (वार्षिक ₹24,000) की प्रत्यक्ष नकद सहायता।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Women and Child Development Department, Karnataka",
        "department": "WCD Karnataka",
        "level": "State",
        "states": ["Karnataka"],
        "intents": ["women_child", "financial"],
        "target_beneficiaries": ["Woman identified as head of the family in Antyodaya, BPL, or APL ration cards whose husband is not paying income tax or GST"],
        "eligibility_rules": {
            "states": ["Karnataka"],
            "gender": ["female"],
            "age": {"min": 18, "max": 80}
        },
        "benefits": ["Direct transfer of ₹2,000 per month (₹24,000/year) into woman's Aadhaar-linked bank account", "Dignified social security and domestic financial control"],
        "documents": ["Ration Card (APL/BPL/Antyodaya) showing woman as family head", "Aadhaar Card of woman and husband", "Bank Passbook seeded with Aadhaar and NPCI mapping"],
        "application_steps": ["Submit application at Karnataka One, Grama One, or Bangalore One centres or via Seva Sindhu portal (sevasindhu.karnataka.gov.in)", "Automatic verification and sanction", "Direct monthly credit via DBT"],
        "official_url": "https://sevasindhugs.karnataka.gov.in/",
        "source_url": "https://karnataka.gov.in/",
        "source_name": "Government of Karnataka",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "gruha-lakshmi", "karnataka", "dbt", "women-empowerment", "income-support"]
    },
    {
        "slug": "karnataka-yuva-nidhi-scheme",
        "scheme_code": "SCH-KA-JOB-001",
        "name": "Yuva Nidhi Scheme (Karnataka Unemployment Allowance)",
        "name_hi": "युवा निधि योजना (कर्नाटक बेरोजगारी भत्ता)",
        "description": "Youth financial support scheme providing monthly unemployment allowance of ₹3,000 for degree holders and ₹1,500 for diploma holders who graduated and remained unemployed.",
        "description_hi": "कर्नाटक के बेरोजगार स्नातकों को ₹3,000 प्रतिमाह तथा डिप्लोमा धारकों को ₹1,500 प्रतिमाह की वित्तीय सहायता 2 वर्ष की अवधि तक।",
        "primary_category": "Employment & Skills",
        "category": "Employment & Skills",
        "ministry": "Skill Development, Entrepreneurship and Livelihood Department, Karnataka",
        "department": "KSDC",
        "level": "State",
        "states": ["Karnataka"],
        "intents": ["jobs", "financial"],
        "target_beneficiaries": ["Graduates and diploma holders domiciled in Karnataka who completed their course and remained unemployed after 180 days of graduation"],
        "eligibility_rules": {
            "states": ["Karnataka"],
            "occupation": ["unemployed"],
            "age": {"min": 20, "max": 35}
        },
        "benefits": ["Monthly financial stipend of ₹3,000 for degree holders and ₹1,500 for diploma holders for up to 2 years or until employment is secured", "Free registration and skill training under Karnataka Skill Connect portal"],
        "documents": ["Karnataka Domicile Certificate", "Degree / Diploma Passing Certificate and Marksheets", "Aadhaar Card", "Bank Account linked with Aadhaar", "Self-declaration of unemployment"],
        "application_steps": ["Apply online on Seva Sindhu portal (sevasindhugs.karnataka.gov.in)", "Automatic verification of university degree through NAD / State Student Achievement Tracking System (SATS)", "Monthly DBT disbursement upon periodic self-declaration"],
        "official_url": "https://sevasindhugs.karnataka.gov.in/",
        "source_url": "https://skill.karnataka.gov.in/",
        "source_name": "Government of Karnataka",
        "verification_status": "Verified",
        "active": True,
        "tags": ["jobs", "unemployment-allowance", "karnataka", "yuva-nidhi", "graduates", "diploma", "stipend"]
    },
    {
        "slug": "karnataka-vidyasiri-scholarship",
        "scheme_code": "SCH-KA-EDU-001",
        "name": "Vidyasiri Scholarship (Karnataka ePASS Food and Accommodation Scheme)",
        "name_hi": "विद्यासिरी छात्रवृत्ति (कर्नाटक ई-पास)",
        "description": "Post-matric scholarship and monthly food & accommodation stipend of ₹1,500 for backward classes (OBC, SC, ST) students who did not get admission into government hostels.",
        "description_hi": "कर्नाटक के पिछड़ा वर्ग, एससी एवं एसटी छात्रों को सरकारी छात्रावास न मिलने पर भोजन एवं आवास हेतु ₹1,500 प्रतिमाह (वार्षिक ₹15,000) तथा पूर्ण शुल्क रियायत।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Backward Classes Welfare Department, Karnataka",
        "department": "BCWD Karnataka",
        "level": "State",
        "states": ["Karnataka"],
        "intents": ["education"],
        "target_beneficiaries": ["OBC, SC, ST students studying in post-matric courses who are residents of Karnataka living away from home without hostel allotment"],
        "eligibility_rules": {
            "states": ["Karnataka"],
            "category": ["OBC", "SC", "ST"],
            "occupation": ["student"],
            "income": {"max": 250000},
            "age": {"min": 16, "max": 35}
        },
        "benefits": ["Food and accommodation allowance of ₹1,500 per month for 10 months (₹15,000/year)", "Tuition fee waiver and exam fee reimbursement as approved by Department"],
        "documents": ["Karnataka Domicile Certificate", "Caste and Income Certificate (RD number verified via Nadakacheri)", "Admission Fee Receipt", "SSLC and PUC marksheets", "Aadhaar Card & Bank Passbook"],
        "application_steps": ["Register on State Scholarship Portal (ssp.postmatric.karnataka.gov.in)", "College e-attestation of documents", "District Backward Classes Welfare Officer approves and releases payment"],
        "official_url": "https://ssp.postmatric.karnataka.gov.in/",
        "source_url": "https://bcwd.karnataka.gov.in/",
        "source_name": "Government of Karnataka",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "scholarship", "karnataka", "vidyasiri", "epass", "hostel", "obc", "student"]
    },

    # =============================================================
    # TAMIL NADU
    # =============================================================
    {
        "slug": "tamil-nadu-kalaignar-magalir-urimai-thittam",
        "scheme_code": "SCH-TN-WOM-001",
        "name": "Kalaignar Magalir Urimai Thittam (KMUT - Tamil Nadu)",
        "name_hi": "कलैग्नार मगलिर उरीमई थित्तम (तमिलनाडु महिला अधिकार अनुदान)",
        "description": "Basic universal income rights scheme providing ₹1,000 per month directly into bank accounts of over 1.15 crore women heads of households in Tamil Nadu.",
        "description_hi": "तमिलनाडु की 1.15 करोड़ से अधिक महिला गृहणियों को उनके घरेलू श्रम के सम्मान एवं आर्थिक स्वावलंबन हेतु प्रतिमाह ₹1,000 की नियमित नकद सहायता।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Special Programme Implementation Department, Tamil Nadu",
        "department": "Revenue and Disaster Management Department",
        "level": "State",
        "states": ["Tamil Nadu"],
        "intents": ["women_child", "financial"],
        "target_beneficiaries": ["Women aged 21 and above who are heads of families possessing smart family cards with annual family income up to ₹2.5 Lakh"],
        "eligibility_rules": {
            "states": ["Tamil Nadu"],
            "gender": ["female"],
            "income": {"max": 250000},
            "age": {"min": 21, "max": 75}
        },
        "benefits": ["Monthly financial rights grant of ₹1,000 credited on the 15th of every month directly via DBT", "Zero deduction or minimum balance penalty from banks"],
        "documents": ["Smart Family Card (Ration Card)", "Aadhaar Card", "Electricity Consumer Number", "Bank Account Details with Aadhaar seeding"],
        "application_steps": ["Submit application at designated camp in Fair Price Shop / Ration Shop area", "Field verification by volunteer and revenue staff", "Direct monthly transfer to bank account"],
        "official_url": "https://kmut.tn.gov.in/",
        "source_url": "https://tn.gov.in/",
        "source_name": "Government of Tamil Nadu",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "kmut", "tamil-nadu", "dbt", "women-empowerment", "rights-grant"]
    },
    {
        "slug": "tamil-nadu-pudhumai-penn-scheme",
        "scheme_code": "SCH-TN-EDU-001",
        "name": "Moovalur Ramamirtham Ammaiyar Higher Education Assurance Scheme (Pudhumai Penn)",
        "name_hi": "पुधुमई पेन योजना (तमिलनाडु बालिका उच्च शिक्षा प्रोत्साहन)",
        "description": "Incentivizes female higher education by providing ₹1,000 per month directly into bank accounts of girl students who studied Class 6 to 12 in government schools pursuing degree/diploma courses.",
        "description_hi": "सरकारी स्कूलों से कक्षा 6 से 12वीं तक पढ़ने वाली छात्राओं को कॉलेज की स्नातक, इंजीनियरिंग, मेडिकल या डिप्लोमा शिक्षा पूरी होने तक ₹1,000 प्रतिमाह का वजीफा।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Social Welfare and Women Empowerment Department, Tamil Nadu",
        "department": "Directorate of Social Welfare",
        "level": "State",
        "states": ["Tamil Nadu"],
        "intents": ["education", "women_child"],
        "target_beneficiaries": ["Girl students domiciled in Tamil Nadu who studied from Class 6 to 12 in Government schools and enrolled in undergraduate degree, diploma, or ITI programs"],
        "eligibility_rules": {
            "states": ["Tamil Nadu"],
            "gender": ["female"],
            "occupation": ["student"],
            "age": {"min": 17, "max": 25}
        },
        "benefits": ["Monthly financial assistance of ₹1,000 credited throughout the duration of undergraduate, engineering, medical, law, or diploma degree", "Higher education enrollment parity for rural and poor girl students"],
        "documents": ["EMIS (Educational Management Information System) ID verifying Class 6-12 in Tamil Nadu government school", "College Admission and Bonafide Certificate", "Aadhaar Card", "Bank Account Details in student's name"],
        "application_steps": ["Register through college nodal officer on pudhumaipenn.tn.gov.in", "Automatic school history verification via School Education EMIS database", "Direct monthly DBT disbursement to student's bank account"],
        "official_url": "https://www.pudhumaipenn.tn.gov.in/",
        "source_url": "https://socialwelfare.tn.gov.in/",
        "source_name": "Government of Tamil Nadu",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "scholarship", "girls", "tamil-nadu", "pudhumai-penn", "higher-education", "dbt"]
    },
    {
        "slug": "tamil-nadu-cmchis-health-insurance",
        "scheme_code": "SCH-TN-HLT-001",
        "name": "Chief Minister's Comprehensive Health Insurance Scheme (CMCHIS Tamil Nadu)",
        "name_hi": "मुख्यमंत्री व्यापक स्वास्थ्य बीमा योजना (तमिलनाडु CMCHIS)",
        "description": "Cashless hospitalization scheme providing coverage of up to ₹5,00,000 per family per year for 1,513 medical and surgical procedures across 1,600+ network hospitals in Tamil Nadu.",
        "description_hi": "तमिलनाडु के परिवारों को गंभीर बीमारियों एवं सर्जरी हेतु प्रति वर्ष प्रति परिवार ₹5 लाख तक का कैशलेस अस्पताल उपचार।",
        "primary_category": "Healthcare",
        "category": "Healthcare",
        "ministry": "Health and Family Welfare Department, Tamil Nadu",
        "department": "Tamil Nadu Health Systems Project (TNHSP)",
        "level": "State",
        "states": ["Tamil Nadu"],
        "intents": ["healthcare"],
        "target_beneficiaries": ["Families domiciled in Tamil Nadu holding Smart Ration Cards with annual income less than ₹1,20,000"],
        "eligibility_rules": {
            "states": ["Tamil Nadu"],
            "income": {"max": 120000},
            "age": {"min": 0, "max": 100}
        },
        "benefits": ["Cashless hospital coverage up to ₹5,00,000 per family per year", "Covers specialized surgeries, diagnostic tests, bone marrow transplant, liver and renal transplants", "Integrated with Ayushman Bharat PM-JAY in Tamil Nadu"],
        "documents": ["Smart Family Ration Card", "Income Certificate issued by Revenue Authority (≤ ₹1.2 Lakh/year)", "Aadhaar Card"],
        "application_steps": ["Enroll at District Collectorate CMCHIS kiosk with Smart Card and Income certificate", "Biometric capture and smart insurance card issuance", "Cashless treatment at empaneled hospitals"],
        "official_url": "https://www.cmchistn.com/",
        "source_url": "https://tnhealth.tn.gov.in/",
        "source_name": "Government of Tamil Nadu",
        "verification_status": "Verified",
        "active": True,
        "tags": ["healthcare", "cmchis", "tamil-nadu", "cashless", "hospital", "surgery", "health-insurance"]
    },

    # =============================================================
    # TELANGANA & ANDHRA PRADESH
    # =============================================================
    {
        "slug": "telangana-rythu-bandhu-bharosa",
        "scheme_code": "SCH-TS-AGRI-001",
        "name": "Rythu Bharosa / Rythu Bandhu Scheme (Telangana)",
        "name_hi": "रायथू भरोसा / रायथू बंधु योजना (तेलंगाना)",
        "description": "Agricultural investment support scheme providing direct financial transfer of up to ₹15,000 per acre per year (₹7,500 per acre each season) to farmers for seed, fertilizer, and farm inputs.",
        "description_hi": "तेलंगाना के किसानों को खरीफ एवं रबी दोनों मौसमों में खाद, बीज एवं कीटनाशक क्रय हेतु ₹15,000 प्रति एकड़ प्रति वर्ष की सीधी निवेश सहायता।",
        "primary_category": "Agriculture & Rural Development",
        "category": "Agriculture & Rural Development",
        "ministry": "Agriculture and Cooperation Department, Telangana",
        "department": "Directorate of Agriculture",
        "level": "State",
        "states": ["Telangana"],
        "intents": ["agriculture", "financial"],
        "target_beneficiaries": ["All landowning farmers possessing digital Pattadar Passbooks and active Dharani land records in Telangana"],
        "eligibility_rules": {
            "states": ["Telangana"],
            "occupation": ["farmer"],
            "age": {"min": 18, "max": 90}
        },
        "benefits": ["Financial grant of ₹7,500 per acre per season (total ₹15,000 per acre per year)", "No middlemen, direct electronic credit into farmer's savings bank account", "Freedom to purchase quality inputs from any vendor"],
        "documents": ["Pattadar Passbook (Title Deed)", "Aadhaar Card", "Bank Account Details (Aadhaar linked)"],
        "application_steps": ["Land ownership verified automatically through Dharani portal records", "Agriculture Extension Officer (AEO) confirms crop status", "Direct credit via e-Kuber portal to bank account"],
        "official_url": "https://rythubandhu.telangana.gov.in/",
        "source_url": "https://agri.telangana.gov.in/",
        "source_name": "Government of Telangana",
        "verification_status": "Verified",
        "active": True,
        "tags": ["agriculture", "farmer", "telangana", "rythu-bandhu", "rythu-bharosa", "crop-investment", "dbt"]
    },
    {
        "slug": "telangana-kalyana-lakshmi-shaadi-mubarak",
        "scheme_code": "SCH-TS-WOM-001",
        "name": "Kalyana Lakshmi & Shaadi Mubarak Scheme (Telangana)",
        "name_hi": "कल्याण लक्ष्मी एवं शादी मुबारक योजना (तेलंगाना)",
        "description": "One-time financial assistance of ₹1,00,116 to brides from SC, ST, BC, EBC, and Minority poor families in Telangana to prevent child marriage and alleviate wedding financial distress.",
        "description_hi": "तेलंगाना के एससी, एसटी, बीसी एवं अल्पसंख्यक गरीब परिवारों की बेटियों के विवाह पर ₹1,00,116 की एकमुश्त सरकारी वित्तीय सहायता।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Scheduled Castes Development & Backward Classes Welfare Departments, Telangana",
        "department": "Social Welfare Telangana",
        "level": "State",
        "states": ["Telangana"],
        "intents": ["women_child", "financial"],
        "target_beneficiaries": ["Brides aged 18 or above domiciled in Telangana from SC/ST/BC/EBC (income ≤ ₹2 Lakh in urban; ₹1.5 Lakh in rural) and Minorities"],
        "eligibility_rules": {
            "states": ["Telangana"],
            "gender": ["female"],
            "income": {"max": 200000},
            "age": {"min": 18, "max": 40}
        },
        "benefits": ["One-time financial grant of ₹1,00,116 credited directly into the bank account of the bride's mother", "Abolishes dependence on usurious local moneylenders"],
        "documents": ["Bride's Age Proof (SSC Certificate / Birth Certificate showing age ≥18)", "Aadhaar Cards of bride, bridegroom, and parents", "Marriage Card / Nikahnama", "Income and Caste Certificate verified through MeeSeva", "Bank Passbook of bride's mother"],
        "application_steps": ["Apply online on telanganaepass.cgg.gov.in portal", "Field inspection by Mandal Revenue Officer (MRO)", "Direct bank sanction through Treasury"],
        "official_url": "https://telanganaepass.cgg.gov.in/",
        "source_url": "https://telangana.gov.in/",
        "source_name": "Government of Telangana",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "marriage", "telangana", "kalyana-lakshmi", "shaadi-mubarak", "financial-grant"]
    },
    {
        "slug": "andhra-pradesh-jagananna-vidya-deevena",
        "scheme_code": "SCH-AP-EDU-001",
        "name": "Jagananna Vidya Deevena (Andhra Pradesh Full Fee Reimbursement)",
        "name_hi": "जगनान्ना विद्या दीवेना (आंध्र प्रदेश पूर्ण शुल्क प्रतिपूर्ति)",
        "description": "Flagship higher education welfare program providing 100% full fee reimbursement directly into mothers' bank accounts for students pursuing ITI, Polytechnic, Degree, Engineering, and Medicine.",
        "description_hi": "आंध्र प्रदेश के गरीब विद्यार्थियों हेतु आईटीआई, पॉलिटेक्निक, इंजीनियरिंग, मेडिकल एवं डिग्री पाठ्यक्रमों की 100% सम्पूर्ण कॉलेज ट्यूशन फीस की प्रतिपूर्ति।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Higher Education Department, Andhra Pradesh",
        "department": "Social Welfare Department",
        "level": "State",
        "states": ["Andhra Pradesh"],
        "intents": ["education"],
        "target_beneficiaries": ["Students domiciled in AP enrolled in recognized post-matric degree/diploma programs whose family annual income is under ₹2.5 Lakh"],
        "eligibility_rules": {
            "states": ["Andhra Pradesh"],
            "occupation": ["student"],
            "income": {"max": 250000},
            "age": {"min": 16, "max": 30}
        },
        "benefits": ["100% reimbursement of college tuition fees credited in quarterly installments into mother's bank account", "Companion Vasathi Deevena covers boarding and hostel expenses up to ₹20,000/year"],
        "documents": ["White Ration Card / Rice Card", "Income and Integrated Caste Certificate", "College Admission Allotment Letter", "Aadhaar Card of student and mother", "Mother's Bank Account Passbook"],
        "application_steps": ["Apply through Grama / Ward Sachivalayam volunteer on jnanabhumi.ap.gov.in", "College principal verifies enrollment and fee demand", "Direct electronic transfer into mother's account"],
        "official_url": "https://jnanabhumi.ap.gov.in/",
        "source_url": "https://ap.gov.in/",
        "source_name": "Government of Andhra Pradesh",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "fee-reimbursement", "andhra-pradesh", "jagananna-vidya-deevena", "college", "student"]
    },
    {
        "slug": "andhra-pradesh-aarogyasri",
        "scheme_code": "SCH-AP-HLT-001",
        "name": "Dr. YSR Aarogyasri Health Scheme (Andhra Pradesh)",
        "name_hi": "डॉ. वाईएसआर आरोग्यश्री स्वास्थ्य योजना (आंध्र प्रदेश)",
        "description": "Comprehensive catastrophic health insurance offering cashless medical coverage of up to ₹25,00,000 per family per year for 3,257 recognized ailments in Andhra Pradesh and super-specialty hospitals.",
        "description_hi": "आंध्र प्रदेश के गरीब परिवारों को कैंसर, हृदय रोग एवं 3,257 गंभीर बीमारियों के उपचार हेतु प्रति परिवार प्रति वर्ष ₹25 लाख तक का कैशलेस अस्पताल स्वास्थ्य बीमा।",
        "primary_category": "Healthcare",
        "category": "Healthcare",
        "ministry": "Health, Medical and Family Welfare Department, Andhra Pradesh",
        "department": "Dr. YSR Aarogyasri Health Care Trust",
        "level": "State",
        "states": ["Andhra Pradesh"],
        "intents": ["healthcare"],
        "target_beneficiaries": ["Families domiciled in Andhra Pradesh holding Rice Cards or having annual income up to ₹5.00 Lakh"],
        "eligibility_rules": {
            "states": ["Andhra Pradesh"],
            "income": {"max": 500000},
            "age": {"min": 0, "max": 100}
        },
        "benefits": ["Complete cashless medical care up to ₹25 Lakhs per family per year across 2,400+ empaneled hospitals including Hyderabad, Bangalore, and Chennai", "Post-operative financial subsistence allowance under Aarogya Asara (up to ₹5,000/month during convalescence)"],
        "documents": ["YSR Aarogyasri Health Card / Rice Card", "Aadhaar Card"],
        "application_steps": ["Aarogya Mithra at any network hospital verifies patient eligibility using QR code / Aadhaar", "Pre-authorization granted electronically within 24 hours", "Completely cashless discharge and medication"],
        "official_url": "https://ysraarogyasri.ap.gov.in/",
        "source_url": "https://ap.gov.in/",
        "source_name": "Government of Andhra Pradesh",
        "verification_status": "Verified",
        "active": True,
        "tags": ["healthcare", "aarogyasri", "andhra-pradesh", "cashless", "surgery", "hospital", "asara"]
    },

    # =============================================================
    # KERALA
    # =============================================================
    {
        "slug": "kerala-karunya-benevolent-fund",
        "scheme_code": "SCH-KL-HLT-001",
        "name": "Karunya Benevolent Fund (KBF / KASP Kerala)",
        "name_hi": "कारुण्या बेनेवोलेंट फंड (केरल स्वास्थ्य सहायता)",
        "description": "Financial assistance program funded by Kerala state lottery proceeds providing medical assistance up to ₹2,00,000 (up to ₹3 Lakh for cancer and transplants) for low-income patients suffering from acute ailments.",
        "description_hi": "केरल के गरीब मरीजों को कैंसर, किडनी डायलिसिस, हीमोफीलिया एवं हृदय शल्य चिकित्सा हेतु ₹2 लाख से ₹3 लाख तक का सरकारी वित्तीय अनुदान।",
        "primary_category": "Healthcare",
        "category": "Healthcare",
        "ministry": "Health and Family Welfare Department, Kerala",
        "department": "State Health Agency (SHA) Kerala",
        "level": "State",
        "states": ["Kerala"],
        "intents": ["healthcare", "financial"],
        "target_beneficiaries": ["Patients domiciled in Kerala with annual family income up to ₹3,00,000 suffering from critical diseases"],
        "eligibility_rules": {
            "states": ["Kerala"],
            "income": {"max": 300000},
            "age": {"min": 0, "max": 100}
        },
        "benefits": ["One-time financial assistance of up to ₹2,00,000 for treatments and surgeries; up to ₹3,00,000 for kidney/liver transplants", "Free regular hemodialysis through Karunya dialyzer support network"],
        "documents": ["Medical Certificate from attending specialist in empanelled hospital with estimated treatment cost", "Income Certificate issued by Village Officer (≤ ₹3 Lakh/yr)", "Ration Card (BPL or APL)", "Aadhaar Card"],
        "application_steps": ["Submit application at District Medical Office (DMO) or empanelled hospital Karunya liaison desk", "District Committee evaluates and issues sanction letter", "Payment disbursed directly to treating hospital"],
        "official_url": "http://karunya.kerala.gov.in/",
        "source_url": "https://sha.kerala.gov.in/",
        "source_name": "Government of Kerala",
        "verification_status": "Verified",
        "active": True,
        "tags": ["healthcare", "karunya", "kerala", "cancer", "dialysis", "medical-grant", "critical-care"]
    }
]
