"""Curated State Government Welfare Schemes - Eastern States (BR, WB, OD, JH, AS)."""

from typing import Any, Dict, List

STATE_SCHEMES_EAST: List[Dict[str, Any]] = [
    # =============================================================
    # BIHAR
    # =============================================================
    {
        "slug": "bihar-mukhyamantri-kanya-utthan-yojana",
        "scheme_code": "SCH-BR-WOM-001",
        "name": "Mukhyamantri Kanya Utthan Yojana (Bihar)",
        "name_hi": "मुख्यमंत्री कन्या उत्थान योजना (बिहार)",
        "description": "Comprehensive girl child welfare program providing financial assistance totaling up to ₹54,100 from birth to graduation to prevent infant mortality and promote female higher education.",
        "description_hi": "बिहार में बालिकाओं के जन्म से लेकर स्नातक उत्तीर्ण होने तक विभिन्न चरणों में कुल ₹54,100 (जन्म पर ₹5,000, 12वीं पर ₹25,000, स्नातक पर ₹50,000) की प्रोत्साहन राशि।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Education and Social Welfare Department, Government of Bihar",
        "department": "Directorate of Higher Education",
        "level": "State",
        "states": ["Bihar"],
        "intents": ["women_child", "education"],
        "target_beneficiaries": ["Girl students domiciled in Bihar passing intermediate or graduation from recognized institutions in Bihar"],
        "eligibility_rules": {
            "states": ["Bihar"],
            "gender": ["female"],
            "age": {"min": 0, "max": 28}
        },
        "benefits": ["₹25,000 one-time incentive upon passing Intermediate (Class 12) unmarried", "₹50,000 one-time incentive upon completing Bachelor's Degree (Graduation) in any stream from recognized university in Bihar", "Direct electronic transfer into girl's personal bank account"],
        "documents": ["Bihar Domicile Certificate", "Graduation Degree / Class 12 Passing Marksheet", "Aadhaar Card", "Bank Passbook with student's name and IFSC (Bank located in Bihar)"],
        "application_steps": ["Register on medhasoft.bih.nic.in portal", "Enter university registration roll number and Aadhaar details", "College verifies student graduation list and DBT payment credited"],
        "official_url": "http://medhasoft.bih.nic.in/",
        "source_url": "https://state.bihar.gov.in/educationbihar/",
        "source_name": "Government of Bihar",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "girl-child", "bihar", "kanya-utthan", "graduation", "scholarship", "higher-education"]
    },
    {
        "slug": "bihar-student-credit-card-scheme",
        "scheme_code": "SCH-BR-EDU-001",
        "name": "Bihar Student Credit Card (BSCC) Scheme",
        "name_hi": "बिहार स्टूडेंट क्रेडिट कार्ड योजना (BSCC)",
        "description": "Provides collateral-free educational loans up to ₹4,00,000 guaranteed by Bihar Government to 12th pass students for pursuing higher education in technical, medical, and general degree courses.",
        "description_hi": "12वीं पास छात्रों को उच्च शिक्षा हेतु राज्य सरकार की गारंटी पर बिना किसी गिरवी या बंधक के ₹4 लाख तक का शिक्षा ऋण मात्र 1% (महिला/दिव्यांग) एवं 4% (पुरुष) ब्याज पर।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Education Department, Bihar",
        "department": "Bihar State Education Finance Corporation (BSEFC)",
        "level": "State",
        "states": ["Bihar"],
        "intents": ["education", "financial"],
        "target_beneficiaries": ["Students domiciled in Bihar who have passed Class 12 (or 10th for polytechnic) admitted to recognized higher education institutions in India"],
        "eligibility_rules": {
            "states": ["Bihar"],
            "occupation": ["student"],
            "age": {"min": 17, "max": 25}
        },
        "benefits": ["Education loan up to ₹4,00,000 covering college fees, hostel, books, laptop, and living expenses", "Concessional simple interest: 1% for females, transgender, and Divyangjan; 4% for male students", "Moratorium period of Course duration + 1 year (no interest during course)"],
        "documents": ["Class 10 and 12 marksheets", "College Admission Proof and Fee Structure", "Bihar Residence Certificate", "Aadhaar Card of student and co-borrower", "Two photographs"],
        "application_steps": ["Register on 7nishchay-yuvaupmission.bihar.gov.in portal", "Visit District Registration and Counseling Centre (DRCC) for document physical verification", "BSEFC issues approval and disburses fee directly to college"],
        "official_url": "https://www.7nishchay-yuvaupmission.bihar.gov.in/",
        "source_url": "https://state.bihar.gov.in/educationbihar/",
        "source_name": "Government of Bihar",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "loan", "bihar", "student-credit-card", "higher-education", "saat-nischay"]
    },
    {
        "slug": "bihar-mukhyamantri-udyami-yojana",
        "scheme_code": "SCH-BR-BIZ-001",
        "name": "Bihar Mukhyamantri Udyami Yojana (SC/ST/EBC/Women/Yuva)",
        "name_hi": "बिहार मुख्यमंत्री उद्यमी योजना",
        "description": "Flagship industrial promotion program providing ₹10,00,000 financial support (50% grant + 50% interest-free loan) to set up new manufacturing and service micro-enterprises in Bihar.",
        "description_hi": "नया उद्योग स्थापित करने हेतु ₹10 लाख की सहायता: ₹5 लाख का पूर्ण सरकारी अनुदान (सब्सिडी) तथा ₹5 लाख का ब्याज-मुक्त ऋण (महिलाओं/युवाओं हेतु 1% नाममात्र ब्याज)।",
        "primary_category": "Business & Self Employment",
        "category": "Business & Self Employment",
        "ministry": "Industries Department, Government of Bihar",
        "department": "Directorate of Industries",
        "level": "State",
        "states": ["Bihar"],
        "intents": ["business", "jobs"],
        "target_beneficiaries": ["Youth, women, SC, ST, and EBC citizens of Bihar aged 18-50 years with minimum intermediate/ITI/polytechnic diploma qualification"],
        "eligibility_rules": {
            "states": ["Bihar"],
            "occupation": ["entrepreneur", "unemployed", "self_employed"],
            "age": {"min": 18, "max": 50}
        },
        "benefits": ["Total financial assistance of ₹10 Lakhs: ₹5 Lakhs direct government grant (subsidy) + ₹5 Lakhs soft loan repayable in 84 monthly installments", "0% interest for SC, ST, EBC, and Women; only 1% simple interest for general/OBC youth", "₹25,000 one-time grant for 2 weeks training"],
        "documents": ["Bihar Domicile Certificate", "Class 12 / ITI / Diploma / Degree Passing Certificate", "Caste Certificate", "Aadhaar Card and PAN Card", "Cancelled Cheque / Bank Account Details"],
        "application_steps": ["Apply online on udyami.bihar.gov.in when annual registration window opens", "Computerized lottery selection monitored by Industries Department", "Two-week enterprise training and tranche-wise fund release"],
        "official_url": "https://udyami.bihar.gov.in/",
        "source_url": "https://state.bihar.gov.in/industries/",
        "source_name": "Industries Department Bihar",
        "verification_status": "Verified",
        "active": True,
        "tags": ["business", "entrepreneurship", "bihar", "udyami", "manufacturing", "subsidy", "msme"]
    },

    # =============================================================
    # WEST BENGAL
    # =============================================================
    {
        "slug": "west-bengal-kanyashree-prakalpa",
        "scheme_code": "SCH-WB-WOM-001",
        "name": "Kanyashree Prakalpa (West Bengal)",
        "name_hi": "कन्याश्री प्रकल्प (पश्चिम बंगाल)",
        "description": "UN Public Service Award-winning conditional cash transfer scheme providing annual scholarships (K1) and a one-time grant of ₹25,000 (K2) to keep girls in school and prevent child marriage.",
        "description_hi": "बालिकाओं को बाल विवाह से बचाने एवं उच्च शिक्षा तक पहुंचाने हेतु वार्षिक छात्रवृत्ति (K1) तथा 18 वर्ष आयु पर ₹25,000 का एकमुश्त सरकारी अनुदान (K2)।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Department of Women & Child Development and Social Welfare, West Bengal",
        "department": "WCD & SW West Bengal",
        "level": "State",
        "states": ["West Bengal"],
        "intents": ["women_child", "education"],
        "target_beneficiaries": ["Unmarried girls aged 13-18 enrolled in Class 8-12 (K1) and aged 18-19 pursuing higher education/training (K2) in West Bengal"],
        "eligibility_rules": {
            "states": ["West Bengal"],
            "gender": ["female"],
            "age": {"min": 13, "max": 19}
        },
        "benefits": ["K1: Annual scholarship of ₹1,000 paid every year from age 13 to 18 while in school", "K2: One-time capital grant of ₹25,000 paid upon turning 18 if unmarried and enrolled in an educational or vocational institution", "K3: Special fellowship for post-graduate higher education"],
        "documents": ["Birth Certificate", "Unmarried Declaration signed by parent and head of institution", "School/College Enrollment Certificate", "Bank Account in girl's sole name with IFSC", "Aadhaar Card"],
        "application_steps": ["Fill application form at school / college", "School head verifies and uploads data on wb.gov.in/kanyashree portal", "Direct bank credit to girl's account"],
        "official_url": "https://www.wbkanyashree.gov.in/",
        "source_url": "https://wb.gov.in/",
        "source_name": "Government of West Bengal",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "girl-child", "west-bengal", "kanyashree", "education", "unmarried", "dbt"]
    },
    {
        "slug": "west-bengal-lakshmir-bhandar",
        "scheme_code": "SCH-WB-WOM-002",
        "name": "Lakshmir Bhandar Scheme (West Bengal)",
        "name_hi": "लक्ष्मी भंडार योजना (पश्चिम बंगाल)",
        "description": "Direct financial assistance scheme providing monthly basic income of ₹1,000 to General category women and ₹1,200 to SC/ST women aged 25-60 years residing in West Bengal.",
        "description_hi": "पश्चिम बंगाल की 25 से 60 वर्ष की महिलाओं को प्रतिमाह ₹1,000 (सामान्य वर्ग) तथा ₹1,200 (एससी/एसटी वर्ग) की नियमित बुनियादी आय सहायता।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Department of Women & Child Development and Social Welfare, West Bengal",
        "department": "WCD & SW West Bengal",
        "level": "State",
        "states": ["West Bengal"],
        "intents": ["women_child", "financial"],
        "target_beneficiaries": ["Women residents of West Bengal aged 25-60 years not in permanent government employment"],
        "eligibility_rules": {
            "states": ["West Bengal"],
            "gender": ["female"],
            "age": {"min": 25, "max": 60}
        },
        "benefits": ["Monthly direct financial grant: ₹1,000 per month for General category women; ₹1,200 per month for SC/ST women", "Credited directly via DBT into beneficiary's personal Aadhaar-linked bank account on the first week of every month"],
        "documents": ["Swasthya Sathi Card number", "Aadhaar Card", "SC/ST Certificate (if claiming higher ₹1,200 rate)", "Bank Passbook showing name and IFSC"],
        "application_steps": ["Submit application form at Duare Sarkar (Government at Doorstep) camps held across the state", "Verification by Block Development Officer / Sub-Divisional Officer", "Monthly automatic credit"],
        "official_url": "https://socialwelfare.wb.gov.in/",
        "source_url": "https://wb.gov.in/",
        "source_name": "Government of West Bengal",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "lakshmir-bhandar", "west-bengal", "dbt", "women-empowerment", "income-support"]
    },
    {
        "slug": "west-bengal-swasthya-sathi",
        "scheme_code": "SCH-WB-HLT-001",
        "name": "Swasthya Sathi Scheme (West Bengal)",
        "name_hi": "स्वास्थ्य साथी योजना (पश्चिम बंगाल)",
        "description": "Flagship universal health protection scheme providing ₹5,00,000 cashless secondary and tertiary hospitalization cover per family per year, issued in the name of the eldest woman of the family.",
        "description_hi": "परिवार की वरिष्ठ महिला के नाम पर जारी स्मार्ट कार्ड के माध्यम से प्रति परिवार प्रति वर्ष ₹5 लाख का पूर्णतः कैशलेस अस्पताल स्वास्थ्य उपचार।",
        "primary_category": "Healthcare",
        "category": "Healthcare",
        "ministry": "Health and Family Welfare Department, West Bengal",
        "department": "Swasthya Sathi Samiti",
        "level": "State",
        "states": ["West Bengal"],
        "intents": ["healthcare"],
        "target_beneficiaries": ["All resident families of West Bengal not covered under any other government statutory health scheme"],
        "eligibility_rules": {
            "states": ["West Bengal"],
            "age": {"min": 0, "max": 100}
        },
        "benefits": ["Basic health cover up to ₹5,00,000 per annum per family on a floater basis", "Paperless and cashless treatment in 2,400+ government and private network hospitals across Bengal and top hospitals in India", "All pre-existing diseases covered from day one"],
        "documents": ["Aadhaar Card of all family members", "Ration Card / Digital Khadya Sathi Card", "Photograph of eldest female family head"],
        "application_steps": ["Enroll at Duare Sarkar camp or local municipal/block office", "Biometric capture of family members", "Issuance of Swasthya Sathi Smart Card on the spot"],
        "official_url": "https://swasthyasathi.gov.in/",
        "source_url": "https://wbhealth.gov.in/",
        "source_name": "Government of West Bengal",
        "verification_status": "Verified",
        "active": True,
        "tags": ["healthcare", "swasthya-sathi", "west-bengal", "cashless", "hospital", "smart-card"]
    },

    # =============================================================
    # ODISHA
    # =============================================================
    {
        "slug": "odisha-kalia-scheme",
        "scheme_code": "SCH-OD-AGRI-001",
        "name": "KALIA Scheme (Krushak Assistance for Livelihood and Income Augmentation)",
        "name_hi": "कालिया योजना (ओडिशा कृषक आजीविका एवं आय संवर्धन)",
        "description": "Progressive agrarian welfare scheme providing financial assistance of ₹10,000 per year for cultivation to small/marginal farmers and ₹12,500 livelihood grants to landless agricultural households.",
        "description_hi": "ओडिशा के छोटे व सीमांत किसानों को खेती हेतु ₹10,000 प्रतिवर्ष तथा भूमिहीन खेतिहर परिवारों को बकरी, बत्तख व डेयरी पालन हेतु ₹12,500 की आजीविका सहायता।",
        "primary_category": "Agriculture & Rural Development",
        "category": "Agriculture & Rural Development",
        "ministry": "Department of Agriculture and Farmers' Empowerment, Odisha",
        "department": "Directorate of Agriculture and Food Production",
        "level": "State",
        "states": ["Odisha"],
        "intents": ["agriculture", "financial"],
        "target_beneficiaries": ["Small and marginal farmers, landless agricultural households, and vulnerable agricultural laborers domiciled in Odisha"],
        "eligibility_rules": {
            "states": ["Odisha"],
            "occupation": ["farmer", "laborer"],
            "age": {"min": 18, "max": 80}
        },
        "benefits": ["Financial assistance of ₹4,000 (Rabi) + ₹4,000 (Kharif) per year for input procurement (fertilizers, seeds)", "One-time financial assistance of ₹12,500 to landless agricultural households for allied activities (goat rearing, duckery, fisheries)", "Life insurance cover of ₹2 Lakh and accidental cover of ₹2 Lakh"],
        "documents": ["Aadhaar Card", "Ration Card (NFSA / SFSS)", "Land Record (RoR) for farmers", "Bank Passbook with active DBT"],
        "application_steps": ["Apply online on kalia.odisha.gov.in portal", "Validation by Village Agriculture Worker (VAW) and Gram Panchayat scrutiny", "Direct benefit transfer via PFMS directly to bank account"],
        "official_url": "https://kalia.odisha.gov.in/",
        "source_url": "https://agri.odisha.gov.in/",
        "source_name": "Government of Odisha",
        "verification_status": "Verified",
        "active": True,
        "tags": ["agriculture", "odisha", "kalia", "farmer", "landless-laborer", "input-support", "dbt"]
    },
    {
        "slug": "odisha-biju-swasthya-kalyan-yojana-bsky",
        "scheme_code": "SCH-OD-HLT-001",
        "name": "Biju Swasthya Kalyan Yojana (BSKY / Gopabandhu Jan Arogya)",
        "name_hi": "बीजू स्वास्थ्य कल्याण योजना (ओडिशा)",
        "description": "Comprehensive health insurance program of Odisha providing cashless medical treatment of ₹5,00,000 per family and ₹10,00,000 for women members per year in premier hospitals.",
        "description_hi": "ओडिशा के 1 करोड़ परिवारों को प्रति परिवार ₹5 लाख तथा परिवार की महिला सदस्यों हेतु ₹10 लाख प्रति वर्ष का कैशलेस अस्पताल स्वास्थ्य बीमा।",
        "primary_category": "Healthcare",
        "category": "Healthcare",
        "ministry": "Health and Family Welfare Department, Odisha",
        "department": "State Health Assurance Society",
        "level": "State",
        "states": ["Odisha"],
        "intents": ["healthcare"],
        "target_beneficiaries": ["NFSA and SFSS ration card holder families domiciled in Odisha"],
        "eligibility_rules": {
            "states": ["Odisha"],
            "age": {"min": 0, "max": 100}
        },
        "benefits": ["Cashless healthcare up to ₹5,00,000 per family per annum", "Enhanced cover up to ₹10,00,000 per annum for all female family members", "Cashless services across 800+ top private hospitals in Odisha and major metros (AIIMS, Apollo, Tata Memorial)"],
        "documents": ["BSKY Health Card / NFSA Ration Card", "Aadhaar Card of patient"],
        "application_steps": ["Show BSKY card / NFSA ration card at hospital helpdesk", "Swasthya Mitra facilitates pre-authorization", "Completely cashless hospital stay and treatment"],
        "official_url": "https://bsky.odisha.gov.in/",
        "source_url": "https://health.odisha.gov.in/",
        "source_name": "Government of Odisha",
        "verification_status": "Verified",
        "active": True,
        "tags": ["healthcare", "odisha", "bsky", "cashless", "women-health", "hospital", "health-insurance"]
    },

    # =============================================================
    # JHARKHAND & ASSAM
    # =============================================================
    {
        "slug": "jharkhand-mukhyamantri-maiyan-samman-yojana",
        "scheme_code": "SCH-JH-WOM-001",
        "name": "Jharkhand Mukhyamantri Maiyan Samman Yojana (JMMSY)",
        "name_hi": "झारखंड मुख्यमंत्री मंइयां सम्मान योजना (JMMSY)",
        "description": "Direct financial aid program providing monthly direct benefit transfer of ₹1,000 to underprivileged women aged 18 to 50 years domiciled in Jharkhand.",
        "description_hi": "झारखंड की 18 से 50 वर्ष की बहनों एवं माताओं को आर्थिक स्वावलंबन एवं सशक्तिकरण हेतु प्रतिमाह ₹1,000 (वार्षिक ₹12,000) की प्रत्यक्ष वित्तीय सहायता।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Women, Child Development and Social Security Department, Jharkhand",
        "department": "WCD & SS Jharkhand",
        "level": "State",
        "states": ["Jharkhand"],
        "intents": ["women_child", "financial"],
        "target_beneficiaries": ["Women aged 18-50 domiciled in Jharkhand belonging to Antyodaya/Priority ration card families whose household does not pay income tax"],
        "eligibility_rules": {
            "states": ["Jharkhand"],
            "gender": ["female"],
            "income": {"max": 250000},
            "age": {"min": 18, "max": 50}
        },
        "benefits": ["Direct monthly financial assistance of ₹1,000 credited on the 15th of every month into beneficiary's Aadhaar-linked bank account", "Economic independence for rural and tribal women"],
        "documents": ["Aadhaar Card", "Ration Card (Yellow/Pink/Green)", "Jharkhand Residential Proof", "Bank Account linked with Aadhaar with single holder operation"],
        "application_steps": ["Submit application at special camps organized across Panchayats or on mmmsy.jharkhand.gov.in", "Biometric verification by Pragya Kendra (CSC)", "Sanction by Block Development Officer and monthly DBT release"],
        "official_url": "https://mmmsy.jharkhand.gov.in/",
        "source_url": "https://jharkhand.gov.in/",
        "source_name": "Government of Jharkhand",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "maiyan-samman", "jharkhand", "dbt", "women-empowerment", "tribal-welfare"]
    },
    {
        "slug": "jharkhand-abua-awas-yojana",
        "scheme_code": "SCH-JH-HOU-001",
        "name": "Abua Awas Yojana (Jharkhand)",
        "name_hi": "अबुआ आवास योजना (झारखंड)",
        "description": "State rural housing scheme providing ₹2,00,000 financial assistance for constructing a 3-room pucca house with a kitchen for homeless and kutcha-house dwelling rural families.",
        "description_hi": "झारखंड के बेघर एवं कच्चे मकानों में रहने वाले परिवारों को 3 कमरों का पक्का मकान (रसोईघर सहित) निर्माण हेतु ₹2,00,000 की सरकारी वित्तीय सहायता।",
        "primary_category": "Housing & Shelter",
        "category": "Housing & Shelter",
        "ministry": "Rural Development Department, Jharkhand",
        "department": "Department of Rural Development",
        "level": "State",
        "states": ["Jharkhand"],
        "intents": ["housing"],
        "target_beneficiaries": ["Homeless and kutcha-house dwelling rural families domiciled in Jharkhand not covered under PMAY-G"],
        "eligibility_rules": {
            "states": ["Jharkhand"],
            "area": "Rural",
            "income": {"max": 200000},
            "age": {"min": 18, "max": 85}
        },
        "benefits": ["Financial grant of ₹2,00,000 paid across 4 construction stages: Foundation (₹30,000), Lintel (₹50,000), Roof (₹1,00,000), Completion (₹20,000)", "Additional 95 days of unskilled wage labor support under MGNREGA (~₹26,000)"],
        "documents": ["Aadhaar Card", "Ration Card", "Gram Panchayat / BPL verification", "Bank Passbook", "Geo-tagged photo of existing kutcha house"],
        "application_steps": ["Submit application at Aapki Yojana Aapki Sarkar Aapke Dwar camp", "Gram Sabha scrutinizes and approves beneficiary priority list", "Direct electronic transfer into bank account linked with construction stages"],
        "official_url": "https://aay.jharkhand.gov.in/",
        "source_url": "https://rural.jharkhand.gov.in/",
        "source_name": "Government of Jharkhand",
        "verification_status": "Verified",
        "active": True,
        "tags": ["housing", "pucca-house", "jharkhand", "abua-awas", "rural", "shelter", "grant"]
    },
    {
        "slug": "assam-orunodoi-scheme",
        "scheme_code": "SCH-AS-WOM-001",
        "name": "Orunodoi 2.0 Scheme (Assam)",
        "name_hi": "ओरुनोदोई 2.0 योजना (असम)",
        "description": "Direct financial benefit transfer scheme transferring ₹1,250 on the 10th of every month into bank accounts of female heads of economically disadvantaged families across Assam.",
        "description_hi": "असम के गरीब परिवारों की महिला मुखिया को पोषण, दवा एवं दैनिक आवश्यकताओं हेतु प्रतिमाह ₹1,250 (वार्षिक ₹15,000) की प्रत्यक्ष नकद सहायता।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Finance Department, Government of Assam",
        "department": "Finance Department",
        "level": "State",
        "states": ["Assam"],
        "intents": ["women_child", "financial"],
        "target_beneficiaries": ["Permanent resident families of Assam with annual income below ₹2,00,000 with preference for families with widows, divyang, or unmarried daughters"],
        "eligibility_rules": {
            "states": ["Assam"],
            "gender": ["female"],
            "income": {"max": 200000},
            "age": {"min": 18, "max": 75}
        },
        "benefits": ["Monthly assistance of ₹1,250 (covering ₹400 for medicines, ₹200 for 4 kg pulses, ₹250 for sugar/fruits, ₹150 for essential items, ₹250 for electricity)", "Direct transfer into nominated woman's bank account via DBT"],
        "documents": ["Assam Resident Proof", "Ration Card (NFSA / Non-NFSA)", "Income Certificate (≤ ₹2 Lakh/year)", "Aadhaar Card", "Bank Account in woman's name"],
        "application_steps": ["Gaon Panchayat / VCDC / Urban Local Body prepares beneficiary shortlist", "Verification by District Level Monitoring Committee", "Direct electronic monthly disbursement"],
        "official_url": "https://orunodoi.assam.gov.in/",
        "source_url": "https://finance.assam.gov.in/",
        "source_name": "Government of Assam",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "orunodoi", "assam", "dbt", "women-empowerment", "income-support", "nutrition"]
    }
]
