"""Curated State Government Welfare Schemes - Central & Western States (MH, GJ, MP, CG)."""

from typing import Any, Dict, List

STATE_SCHEMES_CENTRAL_WEST: List[Dict[str, Any]] = [
    # =============================================================
    # MAHARASHTRA
    # =============================================================
    {
        "slug": "maharashtra-majhi-ladki-bahin-yojana",
        "scheme_code": "SCH-MH-WOM-001",
        "name": "Mukhyamantri Majhi Ladki Bahin Yojana (Maharashtra)",
        "name_hi": "मुख्यमंत्री माझी लाड़की बहीण योजना (महाराष्ट्र)",
        "description": "Direct financial empowerment scheme providing monthly direct benefit transfer of ₹1,500 to underprivileged women aged 21-65 years residing in Maharashtra.",
        "description_hi": "महाराष्ट्र की 21 से 65 वर्ष आयु वर्ग की पात्र महिलाओं को आर्थिक स्वावलंबन एवं पोषण हेतु प्रतिमाह ₹1,500 की नकद वित्तीय सहायता।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Women and Child Development Department, Maharashtra",
        "department": "WCD Maharashtra",
        "level": "State",
        "states": ["Maharashtra"],
        "intents": ["women_child", "financial"],
        "target_beneficiaries": ["Married, widowed, divorced, deserted, and destitute women aged 21-65 residing in Maharashtra with annual family income up to ₹2.5 Lakh"],
        "eligibility_rules": {
            "states": ["Maharashtra"],
            "gender": ["female"],
            "income": {"max": 250000},
            "age": {"min": 21, "max": 65}
        },
        "benefits": ["Direct Benefit Transfer of ₹1,500 per month (₹18,000 per year) directly credited into woman's Aadhaar-linked bank account", "Economic independence and nutritional security"],
        "documents": ["Aadhaar Card", "Maharashtra Domicile Certificate / Ration Card issued at least 15 years ago", "Yellow / Orange Ration Card or Income Certificate (≤ ₹2.5 Lakh)", "Bank Passbook seeded with Aadhaar", "Hamipatra (Self-declaration)"],
        "application_steps": ["Apply online through Nari Shakti Doot Mobile App or ladakibahin.maharashtra.gov.in portal", "Upload documents and Aadhaar e-KYC", "Gram Panchayat / Ward screening and direct monthly bank credit"],
        "official_url": "https://ladakibahin.maharashtra.gov.in/",
        "source_url": "https://womenchild.maharashtra.gov.in/",
        "source_name": "Government of Maharashtra",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "ladki-bahin", "maharashtra", "dbt", "women-empowerment", "financial-support"]
    },
    {
        "slug": "mahatma-jyotirao-phule-jan-arogya-yojana",
        "scheme_code": "SCH-MH-HLT-001",
        "name": "Mahatma Jyotirao Phule Jan Arogya Yojana (MJPJAY Maharashtra)",
        "name_hi": "महात्मा ज्योतिराव फुले जन आरोग्य योजना (महाराष्ट्र)",
        "description": "Universal health insurance scheme of Maharashtra providing cashless medical and surgical treatment of up to ₹5,00,000 per family per year across 1,000+ empaneled hospitals.",
        "description_hi": "महाराष्ट्र के नागरिकों को 1,356 प्रकार की गंभीर बीमारियों एवं शल्य चिकित्सा हेतु प्रति परिवार प्रति वर्ष ₹5 लाख तक का कैशलेस स्वास्थ्य उपचार।",
        "primary_category": "Healthcare",
        "category": "Healthcare",
        "ministry": "Public Health Department, Maharashtra",
        "department": "State Health Assurance Society (SHAS)",
        "level": "State",
        "states": ["Maharashtra"],
        "intents": ["healthcare"],
        "target_beneficiaries": ["All ration card holder families in Maharashtra holding Yellow, Orange, or White ration cards (Universal health coverage)"],
        "eligibility_rules": {
            "states": ["Maharashtra"],
            "age": {"min": 0, "max": 100}
        },
        "benefits": ["Cashless hospital care of up to ₹5,00,000 per family per year", "Covers 1,356 medical and surgical procedures across 34 specialized categories including renal transplant, cardiac surgeries, and oncology", "Free diagnostic and medicine support during hospital stay"],
        "documents": ["Ration Card (Yellow/Orange/White) or Domicile Certificate", "Aadhaar Card / Voter ID", "Doctor's diagnostic report"],
        "application_steps": ["Visit any empaneled government or private network hospital", "Meet Arogyamitra at MJPJAY helpdesk with Ration Card and Aadhaar", "Hospital sends e-pre-authorization and provides cashless treatment"],
        "official_url": "https://www.jeevandayee.gov.in/",
        "source_url": "https://arogya.maharashtra.gov.in/",
        "source_name": "Government of Maharashtra",
        "verification_status": "Verified",
        "active": True,
        "tags": ["healthcare", "maharashtra", "mjpjay", "cashless", "hospital", "health-insurance", "surgery"]
    },
    {
        "slug": "mahadbt-rajarshi-chhatrapati-shahu-maharaj-scholarship",
        "scheme_code": "SCH-MH-EDU-001",
        "name": "Rajarshi Chhatrapati Shahu Maharaj Shikshan Shulkh Shishyavrutti Yojna (EBC)",
        "name_hi": "राजर्षि छत्रपति शाहू महाराज शिक्षण शुल्क शिष्यवृत्ति योजना (ईबीसी)",
        "description": "Higher education fee reimbursement scheme on MahaDBT portal providing 50% tuition and exam fee waiver to students from Economically Backward Classes (EBC) in professional courses.",
        "description_hi": "महाराष्ट्र के आर्थिक रूप से कमजोर वर्ग (EBC/SEBC) के विद्यार्थियों को मेडिकल, इंजीनियरिंग एवं व्यावसायिक उच्च शिक्षा में 50% शिक्षण शुल्क प्रतिपूर्ति।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Higher and Technical Education Department, Maharashtra",
        "department": "Directorate of Technical Education (DTE) / MahaDBT",
        "level": "State",
        "states": ["Maharashtra"],
        "intents": ["education"],
        "target_beneficiaries": ["Students domiciled in Maharashtra admitted through CAP rounds to professional/technical diploma, degree, and postgraduate courses with family income up to ₹8 Lakh"],
        "eligibility_rules": {
            "states": ["Maharashtra"],
            "occupation": ["student"],
            "income": {"max": 800000},
            "age": {"min": 17, "max": 35}
        },
        "benefits": ["50% reimbursement of tuition fees and exam fees approved by Fee Regulating Authority (FRA)", "Direct electronic transfer into student / institute account via MahaDBT"],
        "documents": ["Maharashtra Domicile Certificate", "Income Certificate issued by Tehsildar (≤ ₹8 Lakh/year)", "CAP Admission Allotment Letter", "Class 10, 12 marksheets", "Fee Receipt", "Aadhaar linked Bank Account"],
        "application_steps": ["Log in to mahadbt.maharashtra.gov.in portal", "Apply under Directorate of Higher Education / Directorate of Technical Education", "College nodal officer e-verifies credentials"],
        "official_url": "https://mahadbt.maharashtra.gov.in/",
        "source_url": "https://dte.maharashtra.gov.in/",
        "source_name": "Government of Maharashtra",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "scholarship", "maharashtra", "mahadbt", "ebc", "engineering", "medical", "tuition"]
    },
    {
        "slug": "maharashtra-cmegp",
        "scheme_code": "SCH-MH-BIZ-001",
        "name": "Chief Minister Employment Generation Programme (CMEGP Maharashtra)",
        "name_hi": "मुख्यमंत्री रोजगार सृजन कार्यक्रम (CMEGP महाराष्ट्र)",
        "description": "Credit-linked capital subsidy scheme assisting youth to establish manufacturing and service micro-enterprises with loans up to ₹50 Lakhs and government subsidies up to 35%.",
        "description_hi": "महाराष्ट्र के शिक्षित बेरोजगार युवाओं को विनिर्माण एवं सेवा क्षेत्र में उद्योग स्थापित करने हेतु ₹50 लाख तक का ऋण एवं 15% से 35% तक सरकारी अनुदान।",
        "primary_category": "Business & Self Employment",
        "category": "Business & Self Employment",
        "ministry": "Industries Department, Maharashtra",
        "department": "Directorate of Industries",
        "level": "State",
        "states": ["Maharashtra"],
        "intents": ["business", "jobs"],
        "target_beneficiaries": ["Youth aged 18-45 years (up to 50 years for women, SC, ST, and Ex-Servicemen) domiciled in Maharashtra"],
        "eligibility_rules": {
            "states": ["Maharashtra"],
            "occupation": ["entrepreneur", "unemployed", "self_employed"],
            "age": {"min": 18, "max": 50}
        },
        "benefits": ["Financial assistance for projects up to ₹50 Lakhs in manufacturing and ₹20 Lakhs in service sector", "Capital subsidy (Margin Money) of 15% to 25% for general category and 25% to 35% for special categories (Women/SC/ST/Divyang/Rural)"],
        "documents": ["Maharashtra Domicile Certificate", "Detailed Project Report (DPR)", "Educational Marksheet (Class 10 pass for projects > ₹10 Lakh in manufacturing)", "Aadhaar Card & PAN Card", "Caste Certificate (if applicable)"],
        "application_steps": ["Submit online application on cmegp.gov.in portal", "District Level Task Force Committee (DLTFC) reviews and forwards to designated bank", "Bank disburses loan and subsidy released directly into escrow account"],
        "official_url": "https://cmegp.gov.in/",
        "source_url": "https://industry.maharashtra.gov.in/",
        "source_name": "Government of Maharashtra",
        "verification_status": "Verified",
        "active": True,
        "tags": ["business", "cmegp", "maharashtra", "subsidy", "msme", "entrepreneurship", "self-employment"]
    },

    # =============================================================
    # GUJARAT
    # =============================================================
    {
        "slug": "gujarat-mukhyamantri-yuva-swavalamban-yojana-mysy",
        "scheme_code": "SCH-GJ-EDU-001",
        "name": "Mukhyamantri Yuva Swavalamban Yojana (MYSY Gujarat)",
        "name_hi": "मुख्यमंत्री युवा स्वावलंबन योजना (MYSY गुजरात)",
        "description": "Comprehensive higher education scholarship of Gujarat providing 50% tuition fee reimbursement up to ₹2 Lakh/year, hostel allowances, and book grants to meritorious students.",
        "description_hi": "गुजरात के 10वीं/12वीं में 80 पर्सेंटाइल से अधिक अंक पाने वाले विद्यार्थियों को मेडिकल, इंजीनियरिंग एवं डिग्री कोर्सेज में 50% तक ट्यूशन फीस एवं हॉस्टल सहायता।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Education Department, Government of Gujarat",
        "department": "Knowledge Consortium of Gujarat (KCG)",
        "level": "State",
        "states": ["Gujarat"],
        "intents": ["education"],
        "target_beneficiaries": ["Students securing ≥80 percentile in Class 10/12 board exams admitted to degree/diploma courses in Gujarat with family income up to ₹6 Lakh"],
        "eligibility_rules": {
            "states": ["Gujarat"],
            "occupation": ["student"],
            "income": {"max": 600000},
            "age": {"min": 15, "max": 30}
        },
        "benefits": ["50% tuition fee assistance: up to ₹2,00,000/year for medical/dental; up to ₹50,000/year for engineering/professional; up to ₹25,000/year for diploma", "Hostel accommodation allowance of ₹1,200 per month (₹12,000/year)", "One-time book and equipment grant up to ₹10,000"],
        "documents": ["Gujarat Domicile Proof", "Class 10/12 Marksheet showing ≥80 percentile", "Income Certificate issued by Mamlatdar / TDO (≤ ₹6 Lakh)", "Admission Letter and Fee Receipt", "Bank Passbook"],
        "application_steps": ["Apply online at mysy.guj.nic.in", "Document verification at designated Help Centre (government colleges)", "Direct transfer of scholarship into student's Aadhaar-linked bank account"],
        "official_url": "https://mysy.guj.nic.in/",
        "source_url": "https://gujaratindia.gov.in/",
        "source_name": "Government of Gujarat",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "scholarship", "gujarat", "mysy", "engineering", "medical", "tuition-fee"]
    },
    {
        "slug": "gujarat-vhali-dikri-yojana",
        "scheme_code": "SCH-GJ-WOM-001",
        "name": "Vhali Dikri Yojana (Gujarat Dear Daughter Scheme)",
        "name_hi": "व्हाली दीकरी योजना (गुजरात)",
        "description": "Financial incentive program by Gujarat Government granting total financial assistance of ₹1,10,000 across three stages for the education and marriage of the first two girl children in poor families.",
        "description_hi": "गुजरात में बालिकाओं के सशक्तिकरण एवं शिक्षा हेतु तीन चरणों में कुल ₹1,10,000 (कक्षा 1, कक्षा 9 एवं 18 वर्ष आयु) की वित्तीय सहायता।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Women and Child Development Department, Gujarat",
        "department": "WCD Gujarat",
        "level": "State",
        "states": ["Gujarat"],
        "intents": ["women_child", "education"],
        "target_beneficiaries": ["First and second girl children born in Gujarat families with annual income up to ₹2,00,000"],
        "eligibility_rules": {
            "states": ["Gujarat"],
            "gender": ["female"],
            "income": {"max": 200000},
            "age": {"min": 0, "max": 20}
        },
        "benefits": ["First installment of ₹4,000 on admission to Class 1", "Second installment of ₹6,000 on admission to Class 9", "Third lump-sum installment of ₹1,00,000 upon attaining 18 years of age (without being married before 18) for higher education or marriage"],
        "documents": ["Birth Certificate of Girl Child", "Gujarat Domicile Proof", "Income Certificate (≤ ₹2 Lakh/year)", "Aadhaar Card of parents and daughter", "Bank Passbook"],
        "application_steps": ["Submit application at Anganwadi Centre, Taluka Development Office, or through Digital Gujarat portal (digitalgujarat.gov.in)", "Scrutiny by Child Development Project Officer (CDPO) and sanction"],
        "official_url": "https://wcd.gujarat.gov.in/",
        "source_url": "https://digitalgujarat.gov.in/",
        "source_name": "Government of Gujarat",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "girl-child", "gujarat", "vhali-dikri", "education", "financial-grant"]
    },

    # =============================================================
    # MADHYA PRADESH
    # =============================================================
    {
        "slug": "mp-ladli-behna-yojana",
        "scheme_code": "SCH-MP-WOM-001",
        "name": "Mukhyamantri Ladli Behna Yojana (Madhya Pradesh)",
        "name_hi": "मुख्यमंत्री लाड़ली बहना योजना (मध्य प्रदेश)",
        "description": "Flagship direct income support scheme providing ₹1,250 per month directly into bank accounts of over 1.29 crore women in Madhya Pradesh to foster health, nutrition, and self-reliance.",
        "description_hi": "मध्य प्रदेश की 21 से 60 वर्ष की विवाहित, विधवा एवं तलाकशुदा महिलाओं को प्रतिमाह ₹1,250 की प्रत्यक्ष नकद आर्थिक सहायता।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Women and Child Development Department, Madhya Pradesh",
        "department": "WCD Madhya Pradesh",
        "level": "State",
        "states": ["Madhya Pradesh"],
        "intents": ["women_child", "financial"],
        "target_beneficiaries": ["Resident women of MP aged 21-60 years whose combined family annual income is under ₹2.5 Lakh and not paying income tax"],
        "eligibility_rules": {
            "states": ["Madhya Pradesh"],
            "gender": ["female"],
            "income": {"max": 250000},
            "age": {"min": 21, "max": 60}
        },
        "benefits": ["Monthly financial transfer of ₹1,250 (credited on 10th of every month) directly via DBT into Aadhaar-linked bank account", "Subsidized domestic LPG refills at ₹450 under Ladli Behna Gas Subsidy scheme"],
        "documents": ["Samagra Family ID and Member ID", "Aadhaar Card", "Bank Account linked with Aadhaar with active DBT", "Self-declaration of income under ₹2.5 Lakh"],
        "application_steps": ["Camps organized at Gram Panchayat and Ward level", "Biometric e-KYC on cmladlibehna.mp.gov.in", "Instant generation of Ladli Behna registration receipt and monthly credit"],
        "official_url": "https://cmladlibehna.mp.gov.in/",
        "source_url": "https://mpwcdmis.gov.in/",
        "source_name": "Government of Madhya Pradesh",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "ladli-behna", "madhya-pradesh", "dbt", "women-empowerment", "income-support"]
    },
    {
        "slug": "mp-mukhyamantri-medhavi-vidyarthi-yojana-mmvy",
        "scheme_code": "SCH-MP-EDU-001",
        "name": "Mukhyamantri Medhavi Vidyarthi Yojana (MMVY Madhya Pradesh)",
        "name_hi": "मुख्यमंत्री मेधावी विद्यार्थी योजना (MMVY मध्य प्रदेश)",
        "description": "State education initiative where the Madhya Pradesh Government pays 100% of the tuition fees for students securing ≥70% in MP Board (≥85% in CBSE/ICSE) admitted to engineering, medical, law, and degree colleges.",
        "description_hi": "12वीं में मेधावी अंक लाने वाले विद्यार्थियों के मेडिकल (MBBS), इंजीनियरिंग (IIT/NIT/JEE), क्लैट (NLU) एवं डिग्री पाठ्यक्रमों की सम्पूर्ण ट्यूशन फीस म.प्र. सरकार द्वारा वहन।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Technical Education, Skill Development and Employment Department, Madhya Pradesh",
        "department": "Directorate of Technical Education",
        "level": "State",
        "states": ["Madhya Pradesh"],
        "intents": ["education"],
        "target_beneficiaries": ["Students domiciled in MP scoring ≥70% in MP Board or ≥85% in CBSE/ICSE in Class 12 with family income up to ₹6 Lakh"],
        "eligibility_rules": {
            "states": ["Madhya Pradesh"],
            "occupation": ["student"],
            "income": {"max": 600000},
            "age": {"min": 16, "max": 30}
        },
        "benefits": ["100% tuition fee paid directly to institution by State Government for MBBS in government/private medical colleges in MP", "Full academic fees paid for IIT, NIT, IIIT, BITS Pilani, NLU, and government engineering colleges", "Full fee reimbursement for regular degree courses in government colleges"],
        "documents": ["MP Domicile Certificate", "Class 12 Marksheet", "Income Certificate (≤ ₹6 Lakh)", "National Entrance Exam Allotment Letter (NEET/JEE/CLAT)", "Aadhaar Card & Samagra ID"],
        "application_steps": ["Apply online on Scholarshipportal.mp.nic.in under MMVY section", "Institute verifies fee demand and admission records", "Sanction and direct fee remittance to institution"],
        "official_url": "http://scholarshipportal.mp.nic.in/MedhaviChhatra/",
        "source_url": "https://mp.gov.in/",
        "source_name": "Government of Madhya Pradesh",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "scholarship", "madhya-pradesh", "mmvy", "medical", "engineering", "tuition-fee"]
    },
    {
        "slug": "mp-sambal-yojana-2-0",
        "scheme_code": "SCH-MP-SOC-001",
        "name": "Mukhya Mantri Jan Kalyan (Sambal 2.0) Yojana",
        "name_hi": "मुख्यमंत्री जनकल्याण (संबल 2.0) योजना (मध्य प्रदेश)",
        "description": "Comprehensive social safety net for unorganized workers in MP providing maternity assistance of ₹16,000, death ex-gratia up to ₹4 Lakhs, funeral assistance, and free higher education for children.",
        "description_hi": "असंगठित श्रमिकों को प्रसूति सहायता (₹16,000), दुर्घटना मृत्यु पर ₹4 लाख अनुग्रह राशि, अंत्येष्टि सहायता एवं बच्चों की निःशुल्क उच्च शिक्षा।",
        "primary_category": "Social Security & Pension",
        "category": "Social Security & Pension",
        "ministry": "Labour Department, Madhya Pradesh",
        "department": "MP Unorganized Workers Social Security Board",
        "level": "State",
        "states": ["Madhya Pradesh"],
        "intents": ["social_welfare", "financial", "women_child"],
        "target_beneficiaries": ["Registered unorganized workers aged 18-60 domiciled in MP not paying income tax or holding government jobs"],
        "eligibility_rules": {
            "states": ["Madhya Pradesh"],
            "occupation": ["laborer", "informal_worker", "unemployed", "self_employed"],
            "age": {"min": 18, "max": 60}
        },
        "benefits": ["Maternity assistance of ₹16,000 for women workers", "Accidental death assistance of ₹4,00,000 to family; ₹2,00,000 for normal death", "₹5,000 immediate funeral aid", "Complete free higher education in technical/medical institutes for children of Sambal card holders"],
        "documents": ["Samagra Family and Member ID", "Aadhaar Card", "Bank Account linked with Aadhaar", "Self-declaration of unorganized worker"],
        "application_steps": ["Apply online at sambal.mp.gov.in portal", "Inquiry by Gram Panchayat Secretary / Ward in-charge", "Instant issuance of Sambal 2.0 Smart Card"],
        "official_url": "https://sambal.mp.gov.in/",
        "source_url": "https://labour.mp.gov.in/",
        "source_name": "Government of Madhya Pradesh",
        "verification_status": "Verified",
        "active": True,
        "tags": ["social-security", "sambal", "madhya-pradesh", "unorganized-workers", "maternity", "insurance"]
    },

    # =============================================================
    # CHHATTISGARH
    # =============================================================
    {
        "slug": "chhattisgarh-mahtari-vandan-yojana",
        "scheme_code": "SCH-CG-WOM-001",
        "name": "Mahtari Vandan Yojana (Chhattisgarh)",
        "name_hi": "महतारी वंदन योजना (छत्तीसगढ़)",
        "description": "Direct benefit transfer program providing monthly financial assistance of ₹1,000 (₹12,000 per year) directly to married, widowed, and abandoned women in Chhattisgarh.",
        "description_hi": "छत्तीसगढ़ की 21 वर्ष से अधिक आयु की विवाहित, विधवा एवं परित्यक्ता महिलाओं को प्रतिमाह ₹1,000 (वार्षिक ₹12,000) की नकद आर्थिक सहायता।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Women and Child Development Department, Chhattisgarh",
        "department": "WCD Chhattisgarh",
        "level": "State",
        "states": ["Chhattisgarh"],
        "intents": ["women_child", "financial"],
        "target_beneficiaries": ["Married women aged 21 and above domiciled in Chhattisgarh whose family income is not subject to income tax"],
        "eligibility_rules": {
            "states": ["Chhattisgarh"],
            "gender": ["female"],
            "income": {"max": 250000},
            "age": {"min": 21, "max": 75}
        },
        "benefits": ["Monthly assistance of ₹1,000 directly credited via DBT on the first week of every month into beneficiary's bank account"],
        "documents": ["Aadhaar Card of applicant and husband", "Marriage Certificate / Ration Card showing marital status", "Chhattisgarh Domicile Certificate", "Bank Passbook with active DBT"],
        "application_steps": ["Apply through mahtarivandan.cgstate.gov.in portal or submit form at Anganwadi Centre / Gram Panchayat", "Aadhaar biometric authentication", "Monthly DBT release"],
        "official_url": "https://mahtarivandan.cgstate.gov.in/",
        "source_url": "https://cgstate.gov.in/",
        "source_name": "Government of Chhattisgarh",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "mahtari-vandan", "chhattisgarh", "dbt", "women-empowerment", "income-support"]
    },
    {
        "slug": "chhattisgarh-krishi-unnati-yojana",
        "scheme_code": "SCH-CG-AGRI-001",
        "name": "Chhattisgarh Krishi Unnati Yojana (Paddy Farmers Assistance)",
        "name_hi": "छत्तीसगढ़ कृषक उन्नति योजना (धान उपार्जन सहायता)",
        "description": "Flagship agricultural support scheme providing input assistance ensuring farmers receive ₹3,100 per quintal for paddy procurement up to 21 quintals per acre.",
        "description_hi": "छत्तीसगढ़ के धान उत्पादक किसानों को ₹3,100 प्रति क्विंटल का सुनिश्चित मूल्य एवं प्रति एकड़ 21 क्विंटल धान विक्रय पर अंतर राशि का सीधा भुगतान।",
        "primary_category": "Agriculture & Rural Development",
        "category": "Agriculture & Rural Development",
        "ministry": "Department of Agriculture and Farmers Welfare, Chhattisgarh",
        "department": "Directorate of Agriculture",
        "level": "State",
        "states": ["Chhattisgarh"],
        "intents": ["agriculture", "financial"],
        "target_beneficiaries": ["Paddy producing farmers registered on the Rajiv Gandhi Kisan Nyay / Unified Farmer Portal in Chhattisgarh"],
        "eligibility_rules": {
            "states": ["Chhattisgarh"],
            "occupation": ["farmer"],
            "age": {"min": 18, "max": 85}
        },
        "benefits": ["Differential input subsidy ensuring farmers receive ₹3,100 per quintal (above Central MSP)", "Procurement ceiling of 21 quintals per acre", "One-time direct bank transfer of differential amount"],
        "documents": ["Bhuiyan Land Record (B-1 / P-II)", "Kisan Kitan Card / Registration number", "Aadhaar Card", "Bank Account Details"],
        "application_steps": ["Register land and crop details on kisan.cg.nic.in portal", "Sell paddy at Primary Agricultural Cooperative Society (PACS) mandi", "Direct transfer of difference subsidy amount into bank account"],
        "official_url": "https://agriportal.cg.nic.in/",
        "source_url": "https://cgstate.gov.in/",
        "source_name": "Government of Chhattisgarh",
        "verification_status": "Verified",
        "active": True,
        "tags": ["agriculture", "chhattisgarh", "paddy", "farmer", "krishi-unnati", "msp", "input-subsidy"]
    }
]
