"""Comprehensive State Government Scheme Directory for all 20 priority Indian States."""

from typing import Any, Dict, List

# Structured State Scheme definitions across all 20 states
# Ensuring every state has robust representation across Education, Agriculture, Women, Pension, Health, and Employment.

STATE_SCHEMES_COMPREHENSIVE: List[Dict[str, Any]] = [
    # -------------------------------------------------------------
    # HARYANA (Comprehensive State Schemes)
    # -------------------------------------------------------------
    {
        "slug": "haryana-saksham-yuva-scheme",
        "scheme_code": "SCH-HR-JOB-002",
        "name": "Saksham Yuva Scheme (Haryana Skill & Unemployment Allowance)",
        "name_hi": "सक्षम युवा योजना (हरियाणा कौशल एवं मानदेय भत्ता)",
        "description": "Provides monthly unemployment allowance and honorary assignment wages up to ₹9,000 per month for 100 hours of monthly work to 12th pass, graduate, and post-graduate youth in Haryana.",
        "description_hi": "हरियाणा के 12वीं, स्नातक एवं स्नातकोत्तर बेरोजगार युवाओं को ₹1,500 से ₹3,000 मासिक भत्ता तथा 100 घंटे मानद कार्य हेतु ₹6,000 अतिरिक्त मानदेय (कुल ₹9,000/माह)।",
        "primary_category": "Employment & Skills",
        "category": "Employment & Skills",
        "ministry": "Employment Department, Haryana",
        "department": "Directorate of Employment",
        "level": "State",
        "states": ["Haryana"],
        "intents": ["jobs", "skills", "financial"],
        "target_beneficiaries": ["Unemployed youth aged 18-35 domiciled in Haryana with family income under ₹3 Lakh registered in Parivar Pehchan Patra"],
        "eligibility_rules": {
            "states": ["Haryana"],
            "occupation": ["unemployed"],
            "income": {"max": 300000},
            "age": {"min": 18, "max": 35}
        },
        "benefits": ["Monthly allowance: ₹900 (10th), ₹1,500 (12th), ₹2,000 (Graduate), ₹3,000 (Postgraduate)", "Additional ₹6,000 per month for doing 100 hours of honorary government work (total up to ₹9,000/month)", "Free skill upskilling through Haryana Skill Development Mission (HSDM)"],
        "documents": ["Parivar Pehchan Patra (Family ID)", "Class 12 / Degree Marksheets", "Haryana Domicile Certificate", "Aadhaar Card", "Bank Account linked with Family ID"],
        "application_steps": ["Register on hrex.gov.in portal", "Apply for Saksham Yuva scheme", "Allocation of 100 hours work in government offices and monthly DBT"],
        "official_url": "https://hrex.gov.in/",
        "source_url": "https://meraparivar.haryana.gov.in/",
        "source_name": "Government of Haryana",
        "verification_status": "Verified",
        "active": True,
        "tags": ["jobs", "skills", "haryana", "saksham-yuva", "unemployment-allowance", "ppp"]
    },
    {
        "slug": "haryana-bhavantar-bharpai-yojana",
        "scheme_code": "SCH-HR-AGRI-001",
        "name": "Bhavantar Bharpayee Yojana (Haryana Price Deficit Compensation)",
        "name_hi": "भावांतर भरपाई योजना (हरियाणा कृषि मूल्य अंतर भरपाई)",
        "description": "Compensates farmers for the price deficit when market prices of notified horticultural crops (potatoes, onions, tomatoes, cauliflower, carrots, peas) fall below the state protected benchmark price.",
        "description_hi": "सब्जी एवं बागवानी फसलों के बाजार भाव गिरने पर राज्य सरकार द्वारा तय संरक्षित मूल्य के अंतर की राशि की सीधी भरपाई किसानों के बैंक खाते में।",
        "primary_category": "Agriculture & Rural Development",
        "category": "Agriculture & Rural Development",
        "ministry": "Agriculture and Farmers Welfare Department, Haryana",
        "department": "Haryana State Agricultural Marketing Board (HSAMB)",
        "level": "State",
        "states": ["Haryana"],
        "intents": ["agriculture", "financial"],
        "target_beneficiaries": ["Farmers growing notified horticulture and vegetable crops in Haryana registered on Meri Fasal Mera Byora portal"],
        "eligibility_rules": {
            "states": ["Haryana"],
            "occupation": ["farmer"],
            "age": {"min": 18, "max": 85}
        },
        "benefits": ["Direct price deficit compensation ranging from ₹500 to ₹1,000 per quintal directly transferred via DBT", "Fixed risk protection insulating vegetable farmers from market crashes"],
        "documents": ["Meri Fasal Mera Byora Registration ID", "Parivar Pehchan Patra (PPP)", "Land Revenue Record / Khasra Girdawari", "Mandi J-Form / Sale Receipt"],
        "application_steps": ["Register crop on fasal.haryana.gov.in portal during sowing season", "Sell produce in approved APMC mandis", "Differential amount calculated and credited directly to bank account"],
        "official_url": "https://fasal.haryana.gov.in/",
        "source_url": "https://agriharyana.gov.in/",
        "source_name": "Government of Haryana",
        "verification_status": "Verified",
        "active": True,
        "tags": ["agriculture", "farmer", "haryana", "bhavantar", "vegetables", "horticulture", "price-support"]
    },
    {
        "slug": "haryana-post-matric-scholarship-sc-bc",
        "scheme_code": "SCH-HR-EDU-001",
        "name": "Haryana Post-Matric Scholarship Scheme (SC / BC)",
        "name_hi": "हरियाणा पोस्ट-मैट्रिक छात्रवृत्ति (एससी / बीसी)",
        "description": "Full tuition fee reimbursement and monthly maintenance allowances for SC and Backward Classes students pursuing post-matric courses in Haryana colleges.",
        "description_hi": "हरियाणा के अनुसूचित जाति एवं पिछड़ा वर्ग के विद्यार्थियों हेतु 11वीं कक्षा से स्नातकोत्तर एवं तकनीकी शिक्षा में सम्पूर्ण शिक्षण शुल्क प्रतिपूर्ति एवं छात्रवृत्ति।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Higher Education Department, Haryana",
        "department": "Department of Higher Education",
        "level": "State",
        "states": ["Haryana"],
        "intents": ["education"],
        "target_beneficiaries": ["SC and BC students domiciled in Haryana with family income below ₹2.5 Lakh registered in Parivar Pehchan Patra"],
        "eligibility_rules": {
            "states": ["Haryana"],
            "category": ["SC", "OBC"],
            "occupation": ["student"],
            "income": {"max": 250000},
            "age": {"min": 15, "max": 35}
        },
        "benefits": ["100% reimbursement of non-refundable college and exam fees", "Monthly maintenance allowance of up to ₹1,200 per month credited directly via DBT"],
        "documents": ["Parivar Pehchan Patra (Family ID)", "Caste Certificate", "Income Certificate (≤ ₹2.5 Lakh/yr)", "College Fee Receipt", "Marksheets"],
        "application_steps": ["Apply online on Har-Chhatravratti portal (harchhatravratti.highereduhry.ac.in)", "College e-verifies data and state department disburses funds"],
        "official_url": "https://harchhatravratti.highereduhry.ac.in/",
        "source_url": "https://highereduhry.ac.in/",
        "source_name": "Government of Haryana",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "scholarship", "haryana", "post-matric", "sc", "bc", "higher-education"]
    },

    # -------------------------------------------------------------
    # PUNJAB (Comprehensive State Schemes)
    # -------------------------------------------------------------
    {
        "slug": "punjab-old-age-pension",
        "scheme_code": "SCH-PB-PEN-001",
        "name": "Punjab Old Age Pension Scheme",
        "name_hi": "पंजाब वृद्धावस्था पेंशन योजना",
        "description": "Social security pension of ₹1,500 per month provided directly into bank accounts of senior citizens aged 65+ (men) and 58+ (women) in Punjab.",
        "description_hi": "पंजाब के वरिष्ठ नागरिकों (पुरुष 65+ वर्ष, महिला 58+ वर्ष) को प्रतिमाह ₹1,500 की नियमित सामाजिक सुरक्षा पेंशन।",
        "primary_category": "Social Security & Pension",
        "category": "Social Security & Pension",
        "ministry": "Department of Social Security and Women & Child Development, Punjab",
        "department": "Directorate of Social Security",
        "level": "State",
        "states": ["Punjab"],
        "intents": ["pension"],
        "target_beneficiaries": ["Senior citizens residing in Punjab with annual family income not exceeding ₹60,000"],
        "eligibility_rules": {
            "states": ["Punjab"],
            "income": {"max": 60000},
            "age": {"min": 58, "max": 120}
        },
        "benefits": ["Monthly pension of ₹1,500 credited directly into the beneficiary's bank account via DBT", "Free medical check-ups in government dispensaries"],
        "documents": ["Punjab Domicile Proof", "Age Proof (Voter ID / Aadhaar / Matriculation certificate)", "Income Certificate (≤ ₹60,000/yr)", "Bank Passbook"],
        "application_steps": ["Submit application at Sewa Kendra or online via punjab.gov.in portal", "Child Development Project Officer (CDPO) / SDM verification", "Sanction order issued and monthly DBT started"],
        "official_url": "https://punjab.gov.in/",
        "source_url": "https://sswcd.punjab.gov.in/",
        "source_name": "Government of Punjab",
        "verification_status": "Verified",
        "active": True,
        "tags": ["pension", "senior-citizens", "punjab", "old-age", "social-security", "dbt"]
    },
    {
        "slug": "punjab-post-matric-scholarship-dr-ambedkar",
        "scheme_code": "SCH-PB-EDU-001",
        "name": "Dr. B.R. Ambedkar SC Post-Matric Scholarship (Punjab)",
        "name_hi": "डॉ. बी.आर. अम्बेडकर एससी पोस्ट-मैट्रिक छात्रवृत्ति (पंजाब)",
        "description": "State scholarship providing 100% free education, complete fee waiver, and maintenance stipends for SC students studying in post-matric courses in Punjab.",
        "description_hi": "पंजाब के अनुसूचित जाति के छात्र-छात्राओं हेतु 11वीं, 12वीं, आईटीआई, डिग्री एवं मेडिकल/इंजीनियरिंग में पूर्णतः निःशुल्क शिक्षा एवं मासिक छात्रवृत्ति।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Department of Social Justice, Empowerment and Minorities, Punjab",
        "department": "Directorate of Welfare of SCs & BCs",
        "level": "State",
        "states": ["Punjab"],
        "intents": ["education"],
        "target_beneficiaries": ["SC students domiciled in Punjab studying in recognized institutions with family income up to ₹2.5 Lakh"],
        "eligibility_rules": {
            "states": ["Punjab"],
            "category": ["SC"],
            "occupation": ["student"],
            "income": {"max": 250000},
            "age": {"min": 15, "max": 35}
        },
        "benefits": ["Complete waiver/reimbursement of institutional tuition and non-refundable fees", "Free Freeship Card issued to enable college admission without paying upfront fees", "Maintenance allowance credited via DBT"],
        "documents": ["Punjab Residence Certificate", "SC Caste Certificate", "Income Certificate (≤ ₹2.5 Lakh/yr)", "Marksheets", "Aadhaar Card", "Bank Account Details"],
        "application_steps": ["Apply for Freeship Card on scholarships.punjab.gov.in (Dr. Ambedkar Scholarship Portal)", "Take admission using Freeship Card without paying fees", "Institute confirms admission online"],
        "official_url": "https://scholarships.punjab.gov.in/",
        "source_url": "https://punjab.gov.in/",
        "source_name": "Government of Punjab",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "scholarship", "punjab", "sc", "post-matric", "freeship-card", "tuition-fee"]
    },
    {
        "slug": "punjab-mukh-mantri-cancer-rahat-kosh",
        "scheme_code": "SCH-PB-HLT-001",
        "name": "Mukh Mantri Punjab Cancer Rahat Kosh Society (MMCPRK)",
        "name_hi": "मुख्यमंत्री पंजाब कैंसर राहत कोष",
        "description": "Provides financial grant up to ₹1,50,000 for cashless cancer treatment (chemotherapy, radiotherapy, cancer surgery) to cancer patients in Punjab across empaneled hospitals.",
        "description_hi": "पंजाब के कैंसर मरीजों को पीजीआई, एम्स एवं सूचीबद्ध सरकारी व निजी कैंसर अस्पतालों में उपचार हेतु ₹1,50,000 तक की निःशुल्क वित्तीय सहायता।",
        "primary_category": "Healthcare",
        "category": "Healthcare",
        "ministry": "Department of Health and Family Welfare, Punjab",
        "department": "Directorate of Health Services",
        "level": "State",
        "states": ["Punjab"],
        "intents": ["healthcare", "financial"],
        "target_beneficiaries": ["Any cancer patient who is a permanent resident of Punjab (except government employees with medical reimbursement)"],
        "eligibility_rules": {
            "states": ["Punjab"],
            "age": {"min": 0, "max": 100}
        },
        "benefits": ["Financial grant of up to ₹1,50,000 per patient disbursed directly to treating hospital (PGIMER, Homi Bhabha Cancer Hospital, AIIMS, GMC)", "Free medicines and diagnostics during hospitalization"],
        "documents": ["Punjab Domicile Proof / Voter ID", "Biopsy / Histopathology diagnostic report confirming cancer", "Treatment estimate from treating cancer hospital", "Aadhaar Card"],
        "application_steps": ["Get application filled and signed by treating oncologist in empaneled hospital", "Submit to Civil Surgeon office of home district", "District committee sanctions assistance and funds released to hospital"],
        "official_url": "https://punjab.gov.in/",
        "source_url": "https://health.punjab.gov.in/",
        "source_name": "Government of Punjab",
        "verification_status": "Verified",
        "active": True,
        "tags": ["healthcare", "cancer", "punjab", "medical-grant", "oncology", "hospital", "relief"]
    },

    # -------------------------------------------------------------
    # UTTARAKHAND (Comprehensive State Schemes)
    # -------------------------------------------------------------
    {
        "slug": "uttarakhand-veer-chandra-singh-garhwali-tourism",
        "scheme_code": "SCH-UK-BIZ-001",
        "name": "Veer Chandra Singh Garhwali Tourism Self-Employment Scheme",
        "name_hi": "वीर चंद्र सिंह गढ़वाली पर्यटन स्वरोजगार योजना (उत्तराखंड)",
        "description": "Provides 33% to 50% capital subsidy (up to ₹15 Lakh for non-transport, up to ₹25 Lakh for homestays/eco-resorts) on bank loans to start tourism, hotel, and commercial vehicle businesses in Uttarakhand.",
        "description_hi": "उत्तराखंड के युवाओं को होमस्टे, होटल, योग केंद्र, ट्रैकिंग व पर्यटन वाहन क्रय हेतु 33% से 50% तक सरकारी सब्सिडी (अधिकतम ₹25 लाख)।",
        "primary_category": "Business & Self Employment",
        "category": "Business & Self Employment",
        "ministry": "Tourism Department, Uttarakhand",
        "department": "Uttarakhand Tourism Development Board (UTDB)",
        "level": "State",
        "states": ["Uttarakhand"],
        "intents": ["business", "jobs"],
        "target_beneficiaries": ["Permanent residents of Uttarakhand aged 18+ establishing tourism-related enterprises in the state"],
        "eligibility_rules": {
            "states": ["Uttarakhand"],
            "occupation": ["entrepreneur", "self_employed", "unemployed"],
            "age": {"min": 18, "max": 65}
        },
        "benefits": ["Capital investment subsidy: 33% (up to ₹15 Lakhs in plain areas) and 50% (up to ₹25 Lakhs in hilly areas) for homestays, hotels, fast-food outlets, and adventure sports gear", "Commercial vehicle subsidy of 25% (up to ₹7.5 Lakhs) for tourist taxis and buses"],
        "documents": ["Uttarakhand Domicile / Sthaniya Niwas Praman Patra", "Detailed Project Report (DPR)", "Land Revenue Documents (Khatauni) for construction projects", "Driving License (if vehicle loan)", "Aadhaar & PAN"],
        "application_steps": ["Apply online on vcsg.uk.gov.in portal", "Interview and screening by District Tourism Development Committee chaired by District Magistrate", "Sanction letter issued and subsidy released to bank"],
        "official_url": "https://vcsg.uk.gov.in/",
        "source_url": "https://uttarakhandtourism.gov.in/",
        "source_name": "Uttarakhand Tourism Development Board",
        "verification_status": "Verified",
        "active": True,
        "tags": ["business", "tourism", "homestay", "uttarakhand", "subsidy", "vcsg", "self-employment"]
    },
    {
        "slug": "uttarakhand-old-age-pension",
        "scheme_code": "SCH-UK-PEN-001",
        "name": "Uttarakhand Vridhavastha Pension Yojana (Old Age Pension)",
        "name_hi": "उत्तराखंड वृद्धावस्था पेंशन योजना",
        "description": "Monthly pension of ₹1,500 provided by Uttarakhand Government to senior citizens aged 60+ living in BPL or low-income families in hill and plain districts.",
        "description_hi": "उत्तराखंड के 60 वर्ष या उससे अधिक आयु के वृद्धजनों को प्रतिमाह ₹1,500 की नियमित सामाजिक सुरक्षा पेंशन।",
        "primary_category": "Social Security & Pension",
        "category": "Social Security & Pension",
        "ministry": "Social Welfare Department, Uttarakhand",
        "department": "Directorate of Social Welfare",
        "level": "State",
        "states": ["Uttarakhand"],
        "intents": ["pension"],
        "target_beneficiaries": ["Senior citizens aged 60+ domiciled in Uttarakhand whose family monthly income does not exceed ₹4,000 (BPL limit)"],
        "eligibility_rules": {
            "states": ["Uttarakhand"],
            "income": {"max": 48000},
            "age": {"min": 60, "max": 120}
        },
        "benefits": ["Monthly pension allowance of ₹1,500 directly transferred into beneficiary's bank account via PFMS DBT"],
        "documents": ["Uttarakhand Domicile Certificate", "BPL Certificate / Income Certificate (≤ ₹48,000/yr)", "Age Certificate (Voter ID / Aadhaar)", "Bank Account Details"],
        "application_steps": ["Apply online on ssp.uk.gov.in portal or through Gram Panchayat / Municipal office", "Verification by Village Development Officer (VDO)", "District Social Welfare Officer sanctions pension"],
        "official_url": "https://ssp.uk.gov.in/",
        "source_url": "https://socialwelfare.uk.gov.in/",
        "source_name": "Government of Uttarakhand",
        "verification_status": "Verified",
        "active": True,
        "tags": ["pension", "senior-citizens", "uttarakhand", "old-age", "social-security", "dbt"]
    },

    # -------------------------------------------------------------
    # HIMACHAL PRADESH (Comprehensive State Schemes)
    # -------------------------------------------------------------
    {
        "slug": "hp-indira-gandhi-pyari-behna-sukh-samman-nidhi",
        "scheme_code": "SCH-HP-WOM-001",
        "name": "Indira Gandhi Pyari Behna Sukh Samman Nidhi (Himachal Pradesh)",
        "name_hi": "इंदिरा गांधी प्यारी बहना सुख सम्मान निधि (हिमाचल प्रदेश)",
        "description": "Monthly direct benefit transfer of ₹1,500 (₹18,000 annually) provided to all eligible adult women aged 18 to 59 years in Himachal Pradesh to ensure financial security.",
        "description_hi": "हिमाचल प्रदेश की 18 से 59 वर्ष की पात्र महिलाओं को प्रतिमाह ₹1,500 (वार्षिक ₹18,000) की प्रत्यक्ष नकद सम्मान राशि।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Social Justice and Empowerment Department, Himachal Pradesh",
        "department": "Directorate of Women and Child Development",
        "level": "State",
        "states": ["Himachal Pradesh"],
        "intents": ["women_child", "financial"],
        "target_beneficiaries": ["Women aged 18-59 domiciled in Himachal Pradesh whose family members are not in regular government service or paying income tax"],
        "eligibility_rules": {
            "states": ["Himachal Pradesh"],
            "gender": ["female"],
            "income": {"max": 250000},
            "age": {"min": 18, "max": 59}
        },
        "benefits": ["Monthly financial allowance of ₹1,500 credited directly into the woman's bank account via DBT", "Universal cover for non-government households"],
        "documents": ["Bonafide Himachali Certificate", "Ration Card", "Aadhaar Card", "Bank Account Passbook (Aadhaar linked)", "Self-declaration of non-government employment"],
        "application_steps": ["Submit application at local Tehsil Welfare Office or Gram Panchayat", "Scrutiny by Tehsil Welfare Officer (TWO)", "Direct monthly bank credit"],
        "official_url": "https://himachal.nic.in/",
        "source_url": "https://esomsa.hp.gov.in/",
        "source_name": "Government of Himachal Pradesh",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "himachal-pradesh", "pyari-behna", "sukh-samman", "dbt", "income-support"]
    },
    {
        "slug": "hp-sahara-yojana",
        "scheme_code": "SCH-HP-HLT-001",
        "name": "HP Sahara Yojana (Financial Assistance for Critical Illness Patients)",
        "name_hi": "हिमाचल प्रदेश सहारा योजना (गंभीर बीमारी मरीज आर्थिक सहायता)",
        "description": "Monthly financial assistance of ₹3,000 provided to economically weaker patients suffering from chronic debilitating diseases (Parkinson's, malignant cancer, kidney failure, muscular dystrophy, paralysis).",
        "description_hi": "कैंसर, किडनी फेलियर, पक्षाघात (पैरालिसिस), पार्किंसंस जैसी गंभीर बीमारियों से पीड़ित निर्धन मरीजों को दवाओं एवं तीमारदार हेतु ₹3,000 प्रतिमाह की सहायता।",
        "primary_category": "Healthcare",
        "category": "Healthcare",
        "ministry": "Health and Family Welfare Department, Himachal Pradesh",
        "department": "Directorate of Health Services",
        "level": "State",
        "states": ["Himachal Pradesh"],
        "intents": ["healthcare", "financial"],
        "target_beneficiaries": ["Patients domiciled in HP suffering from specified chronic illnesses with annual family income up to ₹4 Lakh"],
        "eligibility_rules": {
            "states": ["Himachal Pradesh"],
            "income": {"max": 400000},
            "age": {"min": 0, "max": 100}
        },
        "benefits": ["Monthly financial sustenance allowance of ₹3,000 credited directly into patient's or caregiver's bank account via DBT", "Free medicines from hospital"],
        "documents": ["Medical Certificate from specialist of medical college / zonal hospital", "Bonafide Himachali Certificate", "Income Certificate (≤ ₹4 Lakh/yr)", "Aadhaar Card & Bank Passbook"],
        "application_steps": ["Submit application through local ASHA worker or at nearest Block Medical Officer (BMO) office", "Chief Medical Officer (CMO) approves and initiates monthly DBT"],
        "official_url": "https://hpsbys.in/",
        "source_url": "https://hphealth.nic.in/",
        "source_name": "Government of Himachal Pradesh",
        "verification_status": "Verified",
        "active": True,
        "tags": ["healthcare", "himachal-pradesh", "sahara", "critical-illness", "cancer", "dialysis", "monthly-stipend"]
    },

    # -------------------------------------------------------------
    # KARNATAKA (Comprehensive State Schemes)
    # -------------------------------------------------------------
    {
        "slug": "karnataka-shakti-scheme-free-bus-travel",
        "scheme_code": "SCH-KA-WOM-002",
        "name": "Shakti Scheme (Free Bus Travel for Women in Karnataka)",
        "name_hi": "शक्ति योजना (कर्नाटक महिलाओं हेतु निःशुल्क बस यात्रा)",
        "description": "Provides completely free bus travel for all domicile women, girls, and transgender persons across all state government road transport corporations (KSRTC, BMTC, NWKRTC, KKRTC) in Karnataka.",
        "description_hi": "कर्नाटक की सभी महिलाओं, छात्राओं एवं ट्रांसजेंडर नागरिकों को राज्य की सभी सरकारी बसों (KSRTC, BMTC) में निःशुल्क यात्रा की सुविधा।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Transport Department, Government of Karnataka",
        "department": "KSRTC / BMTC",
        "level": "State",
        "states": ["Karnataka"],
        "intents": ["women_child", "social_welfare"],
        "target_beneficiaries": ["All female and transgender citizens domiciled in Karnataka irrespective of income"],
        "eligibility_rules": {
            "states": ["Karnataka"],
            "gender": ["female", "other"],
            "age": {"min": 5, "max": 100}
        },
        "benefits": ["100% free travel in ordinary, express, and city buses within Karnataka (up to 20 km inside border states)", "Significant monthly savings on commute expenses for working women and students"],
        "documents": ["Any Government issued photo ID proving Karnataka residence (Aadhaar Card / Voter ID / Driving License)"],
        "application_steps": ["Show valid Karnataka residence ID to bus conductor and receive zero-fare ticket immediately"],
        "official_url": "https://sevasindhu.karnataka.gov.in/",
        "source_url": "https://ksrtc.in/",
        "source_name": "Government of Karnataka",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "karnataka", "shakti", "free-bus", "women-travel", "transport", "public-mobility"]
    },
    {
        "slug": "karnataka-gruha-jyothi-scheme",
        "scheme_code": "SCH-KA-ENG-001",
        "name": "Gruha Jyothi Scheme (Up to 200 Units Free Electricity Karnataka)",
        "name_hi": "गृह ज्योति योजना (कर्नाटक 200 यूनिट तक निःशुल्क बिजली)",
        "description": "Provides up to 200 units of free electricity every month to all residential domestic households in Karnataka based on their average annual consumption plus 10%.",
        "description_hi": "कर्नाटक के सभी घरेलू उपभोक्ताओं को उनके औसत मासिक उपभोग के आधार पर प्रतिमाह 200 यूनिट तक निःशुल्क घरेलू बिजली।",
        "primary_category": "Housing & Shelter",
        "category": "Housing & Shelter",
        "ministry": "Energy Department, Karnataka",
        "department": "Karnataka Electricity Supply Companies (BESCOM, HESCOM, GESCOM, MESCOM, CHESCOM)",
        "level": "State",
        "states": ["Karnataka"],
        "intents": ["housing", "financial"],
        "target_beneficiaries": ["All residential domestic household consumers having individual electricity meter connections in Karnataka"],
        "eligibility_rules": {
            "states": ["Karnataka"],
            "age": {"min": 18, "max": 100}
        },
        "benefits": ["Zero electricity bill for households consuming within their entitled limit (up to 200 units/month)", "Significant monthly household savings of ₹1,000 to ₹1,600"],
        "documents": ["Electricity Account ID / Consumer Connection Number", "Aadhaar Card", "Rental / Lease agreement (if tenant)"],
        "application_steps": ["Apply online on Seva Sindhu portal (sevasindhugs.karnataka.gov.in)", "Link Aadhaar with electricity consumer account", "Zero electricity bills generated automatically from subsequent billing cycle"],
        "official_url": "https://sevasindhugs.karnataka.gov.in/",
        "source_url": "https://energy.karnataka.gov.in/",
        "source_name": "Government of Karnataka",
        "verification_status": "Verified",
        "active": True,
        "tags": ["housing", "free-electricity", "karnataka", "gruha-jyothi", "bescom", "power-subsidy"]
    },

    # -------------------------------------------------------------
    # TAMIL NADU (Comprehensive State Schemes)
    # -------------------------------------------------------------
    {
        "slug": "tamil-nadu-naan-mudhalvan-scheme",
        "scheme_code": "SCH-TN-JOB-001",
        "name": "Naan Mudhalvan Scheme (Tamil Nadu Upskilling & Career Guidance)",
        "name_hi": "नान मुधलवन योजना (तमिलनाडु युवा कौशल एवं करियर संवर्धन)",
        "description": "Massive youth empowerment platform delivering dynamic industry-aligned skill training in coding, data analytics, artificial intelligence, electric vehicles, and foreign languages to 10 lakh college students annually.",
        "description_hi": "तमिलनाडु के 10 लाख कॉलेज छात्रों को एआई, डेटा साइंस, क्लाउड कंप्यूटिंग एवं रोबोटिक्स में निःशुल्क आधुनिक तकनीकी प्रशिक्षण तथा रोजगार के अवसर।",
        "primary_category": "Employment & Skills",
        "category": "Employment & Skills",
        "ministry": "Special Programme Implementation & Higher Education Department, Tamil Nadu",
        "department": "Tamil Nadu Skill Development Corporation (TNSDC)",
        "level": "State",
        "states": ["Tamil Nadu"],
        "intents": ["skills", "jobs"],
        "target_beneficiaries": ["Students enrolled in government and aided Arts, Science, Engineering, and Polytechnic colleges in Tamil Nadu"],
        "eligibility_rules": {
            "states": ["Tamil Nadu"],
            "occupation": ["student"],
            "age": {"min": 17, "max": 25}
        },
        "benefits": ["Free integrated curriculum training courses created by tech giants (Microsoft, IBM, Cambridge, Infosys)", "Free access to industry certification vouchers", "Mega job placement drives and internships across 500+ multinational companies"],
        "documents": ["College Student Roll Number / ID Card", "Aadhaar Card"],
        "application_steps": ["Log in through college portal at naanmudhalvan.tn.gov.in", "Choose elective skill training tracks", "Attend curriculum integrated sessions and placement interviews"],
        "official_url": "https://www.naanmudhalvan.tn.gov.in/",
        "source_url": "https://tn.gov.in/",
        "source_name": "Government of Tamil Nadu",
        "verification_status": "Verified",
        "active": True,
        "tags": ["skills", "tamil-nadu", "naan-mudhalvan", "coding", "ai", "engineering", "jobs", "youth"]
    },
    {
        "slug": "tamil-nadu-moovalur-ramamirtham-ammaiyar-marriage-aid",
        "scheme_code": "SCH-TN-WOM-003",
        "name": "Chief Minister's Girl Child Protection Scheme (Tamil Nadu)",
        "name_hi": "मुख्यमंत्री बालिका संरक्षण योजना (तमिलनाडु)",
        "description": "Fixed deposit scheme of ₹50,000 for single girl child (₹25,000 each for two girl children) with monthly interest payout and high maturity grant at age 18 to promote family planning and girl child education.",
        "description_hi": "केवल एक बेटी होने पर ₹50,000 तथा दो बेटियां होने पर ₹25,000 प्रति बेटी का सरकारी फिक्स्ड डिपॉजिट जो 18 वर्ष आयु पर ब्याज सहित उच्च शिक्षा हेतु प्राप्त होता है।",
        "primary_category": "Women & Child Development",
        "category": "Women & Child Development",
        "ministry": "Social Welfare and Women Empowerment Department, Tamil Nadu",
        "department": "Directorate of Social Welfare",
        "level": "State",
        "states": ["Tamil Nadu"],
        "intents": ["women_child", "financial"],
        "target_beneficiaries": ["Families in Tamil Nadu with only one or two girl children and no male child, where either parent has undergone sterilization before age 35 with family income up to ₹72,000"],
        "eligibility_rules": {
            "states": ["Tamil Nadu"],
            "gender": ["female"],
            "income": {"max": 72000},
            "age": {"min": 0, "max": 18}
        },
        "benefits": ["State Government deposits ₹50,000 in Tamil Nadu Power Finance Corporation for single girl (or ₹25,000 each for two girls)", "Annual incentive payment of ₹1,800 to girl from age 6 to 18 for educational expenses", "Full accumulated maturity proceeds paid to girl at age 18 for college studies"],
        "documents": ["Birth Certificate of Girl Children", "Sterilization Certificate of parent", "Income Certificate (≤ ₹72,000/yr)", "Tamil Nadu Domicile Proof", "Aadhaar Card"],
        "application_steps": ["Submit application to District Social Welfare Officer (DSWO) before child turns 3 years of age", "Verification of certificates and deposit receipt issued"],
        "official_url": "https://socialwelfare.tn.gov.in/",
        "source_url": "https://tn.gov.in/",
        "source_name": "Government of Tamil Nadu",
        "verification_status": "Verified",
        "active": True,
        "tags": ["women_child", "girl-child", "tamil-nadu", "fixed-deposit", "education", "protection"]
    },

    # -------------------------------------------------------------
    # TELANGANA (Comprehensive State Schemes)
    # -------------------------------------------------------------
    {
        "slug": "telangana-dalit-bandhu-scheme",
        "scheme_code": "SCH-TS-SOC-001",
        "name": "Dalit Bandhu Scheme (Telangana Direct Capital Grant)",
        "name_hi": "दलित बंधु योजना (तेलंगाना ₹10 लाख प्रत्यक्ष पूंजी अनुदान)",
        "description": "Revolutionary direct capital transfer scheme providing a one-time grant of ₹10,00,000 with 100% subsidy (no bank loan or repayment required) to Dalit (SC) families to start profitable enterprises.",
        "description_hi": "तेलंगाना के दलित (एससी) परिवारों को अपना व्यवसाय, विनिर्माण, डेयरी, वाहन अथवा सेवा उद्यम शुरू करने हेतु ₹10 लाख का 100% गैर-वापसी योग्य सरकारी पूंजी अनुदान।",
        "primary_category": "Business & Self Employment",
        "category": "Business & Self Employment",
        "ministry": "Scheduled Castes Development Department, Telangana",
        "department": "Telangana Scheduled Castes Co-operative Development Corporation (TSCCDC)",
        "level": "State",
        "states": ["Telangana"],
        "intents": ["business", "social_welfare"],
        "target_beneficiaries": ["Scheduled Caste (SC) families domiciled in Telangana seeking financial self-reliance through independent business ventures"],
        "eligibility_rules": {
            "category": ["SC"],
            "states": ["Telangana"],
            "occupation": ["entrepreneur", "self_employed", "unemployed", "farmer"],
            "age": {"min": 18, "max": 65}
        },
        "benefits": ["Direct one-time grant of ₹10,00,000 per family deposited into a dedicated Dalit Bandhu bank account", "100% grant: No bank loan, no collateral, no margin money, and zero repayment burden", "Beneficiary chooses enterprise: Transport (taxis, JCBs, tractors), manufacturing, dairy units, retail supermarkets, or medical clinics"],
        "documents": ["SC Caste Certificate verified via MeeSeva", "Food Security Card / Ration Card", "Aadhaar Card", "Special Dalit Bandhu Bank Account details"],
        "application_steps": ["Selection through District Collector and Gram Sabha / Ward committee", "Beneficiary attends enterprise counseling and selects business activity", "Immediate release of ₹10 Lakhs directly for asset procurement"],
        "official_url": "https://dalitbandhu.telangana.gov.in/",
        "source_url": "https://telangana.gov.in/",
        "source_name": "Government of Telangana",
        "verification_status": "Verified",
        "active": True,
        "tags": ["business", "dalit-bandhu", "telangana", "sc", "capital-grant", "entrepreneurship", "social-justice"]
    },
    {
        "slug": "telangana-rythu-bima-farmer-life-insurance",
        "scheme_code": "SCH-TS-AGRI-002",
        "name": "Rythu Bima Scheme (Telangana Farmers Group Life Insurance)",
        "name_hi": "रायथू बीमा योजना (तेलंगाना किसान समूह जीवन बीमा)",
        "description": "Completely free group life insurance scheme providing ₹5,00,000 financial compensation to the bereaved family within 10 days upon the death of a registered farmer aged 18-59 years.",
        "description_hi": "18 से 59 वर्ष के किसान की किसी भी कारण से मृत्यु होने पर परिवार/नामिती को ₹5,00,000 की त्वरित बीमा राशि (100% प्रीमियम तेलंगाना सरकार द्वारा देय)।",
        "primary_category": "Agriculture & Rural Development",
        "category": "Agriculture & Rural Development",
        "ministry": "Agriculture Department, Telangana",
        "department": "Directorate of Agriculture / LIC of India",
        "level": "State",
        "states": ["Telangana"],
        "intents": ["agriculture", "financial"],
        "target_beneficiaries": ["All pattadar farmers aged 18-59 holding title deeds and registered under Rythu Bandhu in Telangana"],
        "eligibility_rules": {
            "states": ["Telangana"],
            "occupation": ["farmer"],
            "age": {"min": 18, "max": 59}
        },
        "benefits": ["₹5,00,000 life insurance claim paid to nominee directly into bank account via DBT within 10 days of death", "100% premium paid entirely by Telangana Government to Life Insurance Corporation (LIC)", "Covers death due to any cause (natural, accidental, illness)"],
        "documents": ["Pattadar Passbook / Title Deed", "Aadhaar Card of farmer and nominee", "Death Certificate of farmer"],
        "application_steps": ["Automatic enrollment upon land registration in Dharani portal", "In case of farmer's demise, Agriculture Extension Officer (AEO) collects claim documents from home", "Claim processed and ₹5 Lakh credited into nominee's account within 10 working days"],
        "official_url": "https://rythubima.telangana.gov.in/",
        "source_url": "https://agri.telangana.gov.in/",
        "source_name": "Government of Telangana",
        "verification_status": "Verified",
        "active": True,
        "tags": ["agriculture", "insurance", "farmer", "rythu-bima", "telangana", "life-insurance", "death-benefit"]
    },

    # -------------------------------------------------------------
    # ANDHRA PRADESH (Comprehensive State Schemes)
    # -------------------------------------------------------------
    {
        "slug": "andhra-pradesh-ysr-rythu-bharosa",
        "scheme_code": "SCH-AP-AGRI-001",
        "name": "YSR Rythu Bharosa - PM KISAN (Andhra Pradesh)",
        "name_hi": "वाईएसआर रायथू भरोसा (आंध्र प्रदेश किसान निवेश सहायता)",
        "description": "Financial assistance of ₹13,500 per year per farmer family (including ₹6,000 Central PM-KISAN and ₹7,500 State share) including tenant farmers (CCRC holders) and ROFR tribal farmers.",
        "description_hi": "आंध्र प्रदेश के सभी भू-स्वामी एवं काश्तकार (कौलू) किसानों को खेती की लागत हेतु प्रति वर्ष ₹13,500 की नकद वित्तीय सहायता (तीन किस्तों में)।",
        "primary_category": "Agriculture & Rural Development",
        "category": "Agriculture & Rural Development",
        "ministry": "Agriculture & Marketing Department, Andhra Pradesh",
        "department": "Directorate of Agriculture",
        "level": "State",
        "states": ["Andhra Pradesh"],
        "intents": ["agriculture", "financial"],
        "target_beneficiaries": ["Farmer families including landholders, tenant farmers belonging to SC, ST, BC, Minorities holding Crop Cultivator Rights Cards (CCRC), and ROFR landholders in AP"],
        "eligibility_rules": {
            "states": ["Andhra Pradesh"],
            "occupation": ["farmer"],
            "age": {"min": 18, "max": 85}
        },
        "benefits": ["Annual financial transfer of ₹13,500: ₹7,500 in May (Kharif sowing); ₹4,000 in October (Rabi sowing); ₹2,000 in January (harvest season)", "Full coverage extended to tenant farmers without land ownership"],
        "documents": ["Webland Land Title Records / CCRC Tenant Farmer Agreement", "Aadhaar Card", "Bank Account Details (Aadhaar enabled)"],
        "application_steps": ["Village Agriculture Assistant (VAA) at Rythu Bharosa Kendra (RBK) verifies land and crop data", "Social audit list displayed at RBK", "Direct DBT payment"],
        "official_url": "https://ysrrythubharosa.ap.gov.in/",
        "source_url": "https://ap.gov.in/",
        "source_name": "Government of Andhra Pradesh",
        "verification_status": "Verified",
        "active": True,
        "tags": ["agriculture", "farmer", "andhra-pradesh", "rythu-bharosa", "tenant-farmer", "dbt", "crop-input"]
    },
    {
        "slug": "andhra-pradesh-ysr-pension-kanuka",
        "scheme_code": "SCH-AP-PEN-001",
        "name": "YSR Pension Kanuka (Doorstep Social Security Pension)",
        "name_hi": "वाईएसआर पेंशन कनुका (घर-द्वार सामाजिक सुरक्षा पेंशन)",
        "description": "Monthly social security pension of ₹3,000 (up to ₹6,000 to ₹15,000 for disabled/dialysis patients) delivered directly in cash at the beneficiary's doorstep by village volunteers on the 1st of every month.",
        "description_hi": "आंध्र प्रदेश के वृद्धजनों, विधवाओं, बुनकरों, ताड़ी निकालने वालों को ₹3,000 प्रतिमाह तथा गंभीर दिव्यांगों व डायलिसिस मरीजों को ₹6,000 से ₹10,000 प्रतिमाह घर बैठे नकद पेंशन।",
        "primary_category": "Social Security & Pension",
        "category": "Social Security & Pension",
        "ministry": "Panchayat Raj & Rural Development Department, Andhra Pradesh",
        "department": "Society for Elimination of Rural Poverty (SERP)",
        "level": "State",
        "states": ["Andhra Pradesh"],
        "intents": ["pension", "social_welfare"],
        "target_beneficiaries": ["Senior citizens aged 60+, widows, single women, weavers, fishermen, and disabled citizens living in BPL households in AP"],
        "eligibility_rules": {
            "states": ["Andhra Pradesh"],
            "income": {"max": 144000},
            "age": {"min": 18, "max": 110}
        },
        "benefits": ["Monthly pension of ₹3,000 for Old Age, Widow, Weavers, Toddy Tappers, and Single Women", "Monthly pension of ₹6,000 for Persons with Severe Disability; ₹10,000 for Chronic Kidney Disease patients on dialysis", "Delivered directly at home at 6:00 AM on the 1st of every month via biometric authentication"],
        "documents": ["Rice Card / White Ration Card", "Aadhaar Card", "Age Proof (showing age 60+ for OAP)", "SADAREM Disability Certificate (for Divyang pension)"],
        "application_steps": ["Apply at Grama / Ward Sachivalayam", "Welfare and Education Assistant (WEA) verifies documents and eligibility", "Pension sanction card delivered to doorstep"],
        "official_url": "https://sspensions.ap.gov.in/",
        "source_url": "https://ap.gov.in/",
        "source_name": "Government of Andhra Pradesh",
        "verification_status": "Verified",
        "active": True,
        "tags": ["pension", "senior-citizens", "andhra-pradesh", "ysr-pension-kanuka", "doorstep-delivery", "widow", "disability"]
    },

    # -------------------------------------------------------------
    # KERALA (Comprehensive State Schemes)
    # -------------------------------------------------------------
    {
        "slug": "kerala-medisep-health-insurance",
        "scheme_code": "SCH-KL-HLT-002",
        "name": "MEDISEP (Medical Insurance for State Employees and Pensioners Kerala)",
        "name_hi": "मेडिसेप (केरल सरकारी कर्मचारी एवं पेंशनभोगी स्वास्थ्य बीमा)",
        "description": "Comprehensive cashless health insurance providing ₹3,00,000 basic coverage per year (plus catastrophic pool) across 1,920 medical procedures for employees and pensioners in Kerala.",
        "description_hi": "केरल के सरकारी कर्मचारियों एवं पेंशनभोगियों को प्रति परिवार प्रति वर्ष ₹3 लाख (तथा गंभीर बीमारियों हेतु अतिरिक्त ₹35 करोड़ कॉर्पस) का कैशलेस स्वास्थ्य बीमा।",
        "primary_category": "Healthcare",
        "category": "Healthcare",
        "ministry": "Finance Department, Government of Kerala",
        "department": "State Insurance Department / Oriental Insurance",
        "level": "State",
        "states": ["Kerala"],
        "intents": ["healthcare", "pension"],
        "target_beneficiaries": ["All serving state government employees, pensioners, family pensioners, and their eligible dependents in Kerala"],
        "eligibility_rules": {
            "states": ["Kerala"],
            "age": {"min": 0, "max": 100}
        },
        "benefits": ["Cashless hospital coverage of ₹3,00,000 per block period of 3 years (up to ₹1.5 Lakhs per year floater)", "Special catastrophic illness fund providing up to ₹18 Lakhs for heart/liver/kidney transplants and neurosurgeries", "Covers 1,920 medical/surgical procedures at empaneled hospitals"],
        "documents": ["MEDISEP ID Card / PPO Number / Employee PEN Number", "Aadhaar Card"],
        "application_steps": ["Automatic enrollment through SPARK / Treasury payroll system", "Download MEDISEP e-card from medisep.kerala.gov.in", "Present card for cashless hospitalization"],
        "official_url": "https://medisep.kerala.gov.in/",
        "source_url": "https://kerala.gov.in/",
        "source_name": "Government of Kerala",
        "verification_status": "Verified",
        "active": True,
        "tags": ["healthcare", "medisep", "kerala", "pensioners", "government-employees", "cashless", "insurance"]
    },
    {
        "slug": "kerala-vidyakiranam-scheme",
        "scheme_code": "SCH-KL-EDU-001",
        "name": "Vidyakiranam Scheme (Educational Assistance for Children of Disabled Parents)",
        "name_hi": "विद्याकिरणम योजना (दिव्यांग माता-पिता के बच्चों हेतु छात्रवृत्ति)",
        "description": "Provides annual educational scholarships from Class 1 to Post-graduation for children of differently-abled parents (disability of 40% or more) to ensure uninterrupted education.",
        "description_hi": "40% या अधिक दिव्यांगता वाले माता-पिता के बच्चों को पहली कक्षा से लेकर स्नातकोत्तर एवं मेडिकल/इंजीनियरिंग तक ₹3,500 से ₹35,000 की वार्षिक शैक्षणिक छात्रवृत्ति।",
        "primary_category": "Education & Learning",
        "category": "Education & Learning",
        "ministry": "Social Justice Department, Kerala",
        "department": "Directorate of Social Justice",
        "level": "State",
        "states": ["Kerala"],
        "intents": ["education", "disability"],
        "target_beneficiaries": ["Children of parents with benchmark disability of 40% or more who belong to BPL families in Kerala"],
        "eligibility_rules": {
            "states": ["Kerala"],
            "occupation": ["student"],
            "income": {"max": 100000},
            "age": {"min": 6, "max": 25}
        },
        "benefits": ["Annual educational assistance: ₹3,500 for Class 1-5; ₹5,000 for Class 6-10; ₹7,500 for Higher Secondary (+1/+2); ₹10,000 for Degree; up to ₹35,000 for Professional/PG courses", "Credited directly via DBT into student's bank account"],
        "documents": ["Parents' Disability Certificate / UDID Card (≥40% disability)", "BPL Ration Card / Income Certificate", "School / College Bonafide Certificate", "Aadhaar Card & Bank Passbook"],
        "application_steps": ["Apply online on SUNEETHI portal (suneethi.sjd.kerala.gov.in)", "Institution head verifies student attendance", "District Social Justice Officer (DSJO) approves and releases payment"],
        "official_url": "http://suneethi.sjd.kerala.gov.in/",
        "source_url": "http://sjd.kerala.gov.in/",
        "source_name": "Government of Kerala",
        "verification_status": "Verified",
        "active": True,
        "tags": ["education", "scholarship", "kerala", "vidyakiranam", "disability", "differently-abled", "student"]
    }
]
